<?php
    $this->layout('base.phtml', [
        'title' => _('Link collections'),
        'canonical' => url_full('link collections', ['id' => $link->id]),
        'has_errors' => $error || $errors,
    ]);
?>

<div class="section">
    <div class="section__title">
        <h1 id="modal-title"><?= _('Link collections') ?></h1>
    </div>

    <p class="section__intro">
        <?= protect($link->title) ?>
    </p>

    <form method="post" action="<?= url('update link collections', ['id' => $link->id]) ?>">
        <input type="hidden" name="csrf" value="<?= $csrf_token ?>" />
        <input type="hidden" name="from" value="<?= $from ?>" />

        <fieldset aria-describedby="collections-desc">
            <legend><?= _('Collections') ?></legend>

            <div id="collections-desc">
                <?php if (isset($errors['collection_ids'])): ?>
                    <p class="form-group__error">
                        <span class="sr-only"><?= _('Error') ?></span>
                        <?= $errors['collection_ids'] ?>
                    </p>
                <?php endif; ?>
            </div>

            <?= $this->include('collections/_selector.phtml', [
                'collections' => $collections,
                'collection_ids' => $collection_ids,
            ]) ?>
        </fieldset>

        <div class="form__actions">
            <button type="submit" class="button--primary">
                <?= _('Save changes') ?>
            </button>
        </div>
    </form>
</div>
