<?php
    $this->layout('base.phtml', [
        'title' => _('Storing a link'),
        'canonical' => url_full('link collections', ['id' => $link->id]),
        'has_errors' => $error || $errors,
        'modal_enabled' => true,
    ]);
?>

<div class="section">
    <div class="section__title">
        <h1 id="modal-title"><?= _('Storing a link') ?></h1>
    </div>

    <p class="section__intro">
        <?= protect($link->title) ?>
    </p>

    <form
        data-turbo-preserve-scroll
        method="post"
        action="<?= url('update link collections', ['id' => $link->id]) ?>"
        data-controller="autosave"
        data-action="turbo:submit-start@document->autosave#clear"
    >
        <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />
        <input type="hidden" name="from" value="<?= $from ?>" />
        <input type="hidden" name="mark_as_read" value="<?= $mark_as_read ?>" />

        <fieldset aria-describedby="collections-desc">
            <legend><?= _('Collections') ?></legend>

            <div id="collections-desc">
                <?php if (isset($errors['collection_ids'])): ?>
                    <p class="form-group__error">
                        <span class="sr-only"><?= _('Error') ?></span>
                        <?= $errors['collection_ids'] ?>
                    </p>
                <?php endif; ?>

                <?php if (isset($errors['name'])): ?>
                    <p class="form-group__error">
                        <span class="sr-only"><?= _('Error') ?></span>
                        <?= $errors['name'] ?>
                    </p>
                <?php endif; ?>
            </div>

            <?php if ($collections_by_others): ?>
                <?= $this->include('collections/_collections_by_others.phtml', [
                    'collections' => $collections_by_others,
                    'link' => $link,
                ]) ?>
            <?php endif; ?>

            <?= $this->include('collections/_selector.phtml', [
                'groups' => $groups,
                'groups_to_collections' => $groups_to_collections,
                'shared_collections' => $shared_collections,
                'collection_ids' => $collection_ids,
                'new_collection_names' => $new_collection_names,
                'name_max_length' => $name_max_length,
            ]) ?>
        </fieldset>

        <div class="form-group">
            <input
                type="checkbox"
                id="is-hidden"
                name="is_hidden"
                <?= $link->is_hidden ? 'checked' : '' ?>
            />

            <label class="label--checkbox" for="is-hidden">
                <?= _('Hide this link in public collections') ?>
            </label>
        </div>

        <?php $notepad = $link->notepad(); ?>
        <?php if ($notepad): ?>
            <details class="form-details">
                <summary>
                    <?= _('You already annoted this link.') ?>
                </summary>

                <div class="form-details__content flow flow--large">
                    <article class="notepad flow flow--large">
                        <?php foreach ($notepad as $date_iso => $notes): ?>
                            <?php $date = new \DateTimeImmutable($date_iso); ?>
                            <div id="notepad-<?= $date_iso ?>" class="flow">
                                <p>
                                    <span class="notepad__date" href="#notepad-<?= $date_iso ?>">
                                        <time datetime="<?= $date_iso ?>">
                                            <?= _d($date, 'dd MMMM y') ?>
                                        </time>
                                    </span>
                                </p>

                                <?php foreach ($notes as $note): ?>
                                    <div class="notepad__container">
                                        <div class="notepad__note">
                                            <?= $note->contentAsHtml() ?>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                        <?php endforeach; ?>
                    </article>

                    <div class="form-group">
                        <label for="content">
                            <?= _('What do you retain from this content?') ?>
                            <span class="label__help">
                                <?= _('(optional)') ?>
                            </span>
                        </label>

                        <textarea
                            id="content"
                            name="content"
                            data-controller="text-editor"
                            data-action="text-editor#refresh keyup->autosave#save"
                            aria-describedby="content-desc"
                        ><?= $content ?></textarea>

                        <p class="form-group__caption" id="content-desc">
                            <?= _('You can format the content in Markdown and use #tags.') ?>
                        </p>
                    </div>

                    <?php if ($mastodon_configured): ?>
                        <div class="form-group">
                            <input
                                type="checkbox"
                                id="share-on-mastodon"
                                name="share_on_mastodon"
                                <?= $share_on_mastodon ? 'checked' : '' ?>
                            />

                            <label class="label--checkbox" for="share-on-mastodon">
                                <?= _('Share on Mastodon') ?>
                            </label>
                        </div>
                    <?php endif; ?>
                </div>
            </details>
        <?php else: ?>
            <div class="form-group">
                <label for="content">
                    <?= _('What do you retain from this content?') ?>
                    <span class="label__help">
                        <?= _('(optional)') ?>
                    </span>
                </label>

                <textarea
                    id="content"
                    name="content"
                    data-controller="text-editor"
                    data-action="text-editor#refresh keyup->autosave#save"
                    aria-describedby="content-desc"
                ><?= $content ?></textarea>

                <p class="form-group__caption" id="content-desc">
                    <?= _('You can format the content in Markdown and use #tags.') ?>
                </p>
            </div>

            <?php if ($mastodon_configured): ?>
                <div class="form-group">
                    <input
                        type="checkbox"
                        id="share-on-mastodon"
                        name="share_on_mastodon"
                        <?= $share_on_mastodon ? 'checked' : '' ?>
                    />

                    <label class="label--checkbox" for="share-on-mastodon">
                        <?= _('Share on Mastodon') ?>
                    </label>
                </div>
            <?php endif; ?>
        <?php endif; ?>

        <div class="form__actions">
            <button type="submit" class="button--primary">
                <?php if ($mark_as_read): ?>
                    <?= _('Store the link and mark as read') ?>
                <?php else: ?>
                    <?= _('Store the link') ?>
                <?php endif; ?>
            </button>
        </div>
    </form>
</div>
