<?php
    $this->layout('onboarding.phtml', [
        'title' => _('Collections and feeds'),
        'canonical' => url_full('onboarding', ['step' => 4]),
        'current_step' => 4,
    ]);
?>

<div class="section section--small section--longbottom">
    <div class="section__title">
        <h1><?= _('Collections and feeds') ?></h1>
    </div>

    <p class="paragraph--featured">
        <?= _('Create collections and share your passions with the rest of the world.') ?>
    </p>

    <ul class="list--spaced">
        <li class="list__item">
            <?= _('Collections are a convenient way to organize your links;') ?>
        </li>

        <li class="list__item">
            <?= _('they can be about anything: culture, education, cooking recipes, local politics and so on;') ?>
        </li>

        <li class="list__item">
            <?= _f('once published, anyone can follow your collection: directly in %s or via a feed aggregator for external people.', $brand) ?>
        </li>
    </ul>

    <br />

    <p class="paragraph--centered">
        <em><?= _('Speaking of which…') ?></em><br />
        <?= _f('You may have come across <abbr>RSS</abbr> feeds by the past?') ?>
    </p>

    <p class="paragraph--centered">
        <strong>
            <?= _f('Podcasts, news sites, Youtube channels, blogs: all these can be followed in %s as well! Feeds are simply external collections.', $brand) ?>
        </strong>
    </p>

    <figure class="figure--centered">
        <div class="screenshot">
            <img
                alt="<?= _('A screenshot showing the result when searching for the “https://flus.fr” address: a link and a feed to follow') ?>"
                class="illustration illustration--figure screenshot__image"
                src="<?= url_static('onboarding/new-link-with-feed.png') ?>"
             />
        </div>

         <figcaption>
             <?= _('For instance, when you’re searching for “https://flus.fr”, you can add the link to your collections and follow the feed that has been auto-detected.') ?>
         </figcaption>
    </figure>

    <p class="paragraph--centered">
        <a class="anchor--action" href="<?= url('onboarding', ['step' => 5]) ?>">
            <?= _('Continue') ?>
        </a>
    </p>
</div>
