<?php
    $this->layout('onboarding.phtml', [
        'title' => _('Follow content from Internet'),
        'canonical' => url_full('onboarding', ['step' => 4]),
        'current_step' => 4,
    ]);
?>

<div class="section section--longbottom">
    <div class="section__title">
        <h1><?= _('Follow content from Internet') ?></h1>
    </div>

    <p class="section__intro">
        <?= icon('feed') ?>
        <?= _('The <strong>Feeds</strong> list the websites and collections that you follow.') ?>
    </p>

    <p class="paragraph--centered">
        <?= _f('A lot of sites can be followed in %s <strong>as long as they offer a <abbr>RSS</abbr> feed</strong>: most news sites, blogs, podcasts… Even YouTube channels!', $brand) ?>
    </p>

    <p class="paragraph--centered">
        <?= _('What if you could follow everything happening on Internet from one place?') ?>
    </p>

    <p class="paragraph--centered">
        <a class="anchor--action" href="<?= url('onboarding', ['step' => 5]) ?>">
            <?= _('Continue') ?>
        </a>
    </p>
</div>
