<?php
    $this->layout('onboarding.phtml', [
        'title' => _('Understanding the news'),
        'current_step' => 5,
    ]);
?>

<div class="section section--longbottom">
    <div class="section__title">
        <h1><?= _('Understanding the news') ?></h1>
    </div>

    <p class="paragraph--featured">
        <?= _('You might have a lot to read everyday.') ?>
    </p>

    <p class="paragraph--centered">
        <?= _f('The news offers you 3 ways to select links to read:', $brand) ?>
    </p>

    <div class="cards cards--centered">
        <div class="card card--showcase">
            <img
                class="card__image"
                alt=""
                src="<?= url_static('illustrations/newspaper.svg') ?>"
                height="200"
            />

            <span class="news-selection__title"><?= _('the latest publications') ?></span>
            <small class="text--secondary"><?= _('from your followed collections') ?></small>
        </div>

        <div class="card card--showcase">
            <img
                class="card__image"
                alt=""
                src="<?= url_static('illustrations/reading.svg') ?>"
                height="200"
            />

            <span class="news-selection__title"><?= _('3 links of -10 minutes') ?></span>
            <small class="text--secondary"><?= _('from your bookmarks') ?></small>
        </div>

        <div class="card card--showcase">
            <img
                class="card__image"
                alt=""
                src="<?= url_static('illustrations/cup-of-tea.svg') ?>"
                height="200"
            />

            <span class="news-selection__title"><?= _('1 link of +10 minutes') ?></span>
            <small class="text--secondary"><?= _('from your bookmarks') ?></small>
        </div>
    </div>

    <p class="paragraph--centered">
        <?= _f('<strong>These pre-selections keep your reading space pleasant in daily use.</strong> In %s, there is no endless scroll: your <em>peace of mind</em> is what matters most.', $brand) ?>
    </p>

    <p class="paragraph--centered">
        <a class="anchor--action" href="<?= url('onboarding', ['step' => 6]) ?>">
            <?= _('Continue') ?>
        </a>
    </p>
</div>
