<?php
    $this->layout('onboarding.phtml', [
        'title' => _('Share with the rest of Internet'),
        'canonical' => url_full('onboarding', ['step' => 5]),
        'current_step' => 5,
    ]);
?>

<div class="section section--longbottom">
    <div class="section__title">
        <h1><?= _('Share with the rest of Internet') ?></h1>
    </div>

    <p class="section__intro">
        <?= icon('avatar') ?>
        <?= _('The <strong>Profile</strong> is your public page listing all what you share.') ?>
    </p>

    <p class="paragraph--centered">
    <?= _('Every time you share a link in a public collection, it gets added to your profile. <strong>Comment on your reading to add a personal touch.</strong>') ?>
    </p>

    <p class="paragraph--centered">
        <?= _('Nothing like spreading the address to your Flus profile around!') ?>
    </p>

    <p class="paragraph--centered">
        <a class="anchor--action" href="<?= url('onboarding', ['step' => 6]) ?>">
            <?= _('Continue') ?>
        </a>
    </p>
</div>
