<?php
    $this->layout('onboarding.phtml', [
        'title' => _('Stay informed with the news'),
        'canonical' => url_full('onboarding', ['step' => 2]),
        'current_step' => 2,
    ]);
?>

<div class="section section--longbottom">
    <div class="section__title">
        <h1><?= _('Stay informed with the news') ?></h1>
    </div>

    <p class="section__intro">
        <?= icon('news') ?>
        <?= _('The <strong>News</strong> is where you get suggestions of what to read.') ?>
    </p>

    <p class="paragraph--centered">
        <?= _('It suggests you things to read from your bookmarks or from the feeds that you follow. It is volontarily limited in time and size <strong>to keep information overload away from you.</strong>') ?>
    </p>

    <p class="paragraph--centered">
        <?= _('The news is the equivalent of a newsfeed on other social networks, except that it’s not infinite.') ?>
    </p>

    <p class="paragraph--centered">
        <a class="anchor--action" href="<?= url('onboarding', ['step' => 3]) ?>">
            <?= _('Continue') ?>
        </a>
    </p>
</div>
