<?php
    $this->layout('onboarding.phtml', [
        'title' => _('Store your links'),
        'canonical' => url_full('onboarding', ['step' => 3]),
        'current_step' => 3,
    ]);
?>

<div class="section section--small section--longbottom">
    <div class="section__title">
        <h1><?= _('Store your links') ?></h1>
    </div>

    <p class="section__intro">
        <?= icon('link') ?>
        <?= _('<strong>My links</strong> regroup your links organized in collections.') ?>
    </p>

    <p class="paragraph--centered">
        <?= _('By default, you start with 4 collections: <strong>“Bookmarks”, “Links read”, “My favorites” and “My shares”.</strong> Obviously, you can create as many collections as you want!') ?>
    </p>

    <p class="paragraph--centered">
        <?= _('All the links you want to find later have their place in the collections.') ?>
    </p>

    <p class="paragraph--centered">
        <a class="anchor--action" href="<?= url('onboarding', ['step' => 4]) ?>">
            <?= _('Continue') ?>
        </a>
    </p>
</div>
