<?php
    $this->layout('onboarding.phtml', [
        'title' => _('Start exploring'),
        'canonical' => url_full('onboarding', ['step' => 6]),
        'current_step' => 6,
    ]);
?>

<div class="section section--longbottom">
    <div class="section__title">
        <h1><?= _('Start exploring') ?></h1>
    </div>

    <p class="paragraph--centered">
        <?= _f('This is the end of the onboarding. You should now have the keys to use %s in an efficient way.', get_app_configuration('brand')) ?>
    </p>

    <p class="paragraph--centered">
        <?= _('You still have things to discover, stay curious!') ?>
    </p>

    <p class="paragraph--featured">
        <a class="anchor--action" href="<?= url('news') ?>">
            <?= _f('Start using %s', get_app_configuration('brand')) ?>
        </a>
    </p>

    <img
        class="illustration illustration--centered"
        alt=""
        src="<?= url_static('illustrations/completing.svg') ?>"
        height="250"
    />

    <p class="paragraph--contrasted paragraph--centered no-mobile">
        <strong>
            <?= _('Make your life easier by using the Web extension on') ?>
            <a
                target="_blank"
                rel="noopener noreferrer"
                href="https://addons.mozilla.org/fr/firefox/addon/flus/"
            >Firefox</a>
            <?= _('or') ?>
            <a
                target="_blank"
                rel="noopener noreferrer"
                href="https://chrome.google.com/webstore/detail/flus/gikjpohbbimicecbndkefebbpjobokjd?hl=fr"
            >Chrome</a>.
        </strong>
    </p>

    <p class="paragraph--centered">
        <?= _('You can import your feeds if you already use a <abbr>RSS</abbr> aggregator:') ?>
    </p>

    <p class="paragraph--centered">
        <a href="<?= url('opml') ?>">
            <?= _('Import an <abbr>OPML</abbr> file') ?>
        </a>
    </p>
</div>
