<?php
    $this->layout('onboarding.phtml', [
        'title' => _('Start exploring'),
        'current_step' => 5,
    ]);
?>

<div class="section section--small">
    <div class="section__title">
        <h1><?= _('Start exploring') ?></h1>
    </div>

    <p class="paragraph--featured">
        <?= _f('This is the end of the onboarding. You should now have the keys to use %s in an efficient way.', $brand) ?>
    </p>

    <img
        class="illustration illustration--centered"
        alt=""
        src="<?= url_static('illustrations/completed.svg') ?>"
        height="250"
    />

    <p class="paragraph--centered">
        <?= _('All the features weren’t explained and new ones are coming regularly. If you’re lost, stay curious and you should find your way.') ?>
    </p>

    <p class="paragraph--centered">
        <a class="anchor--action" href="<?= url('news') ?>">
            <?= icon('news') ?>
            <?= _('Access the news') ?>
        </a>
    </p>

    <hr />

    <p class="paragraph--centered">
        <?= _f('Tip: if you use Pocket, you can import your links into %s.', $brand) ?>
    </p>

    <p class="paragraph--centered">
        <a href="<?= url('pocket') ?>">
            <?= _('Import from Pocket') ?>
        </a>
    </p>
</div>
