<?php
    $this->layout('onboarding.phtml', [
        'title' => _('Welcome!'),
        'current_step' => 1,
    ]);
?>

<div class="section section--small">
    <div class="section__title">
        <h1><?= _f('Welcome %s!', $this->protect($current_user->username)) ?></h1>
    </div>

    <form
        class="form--centered"
        method="post"
        action="<?= url('onboarding update locale') ?>"
        data-controller="form-autosubmit"
    >
        <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />
        <input type="hidden" name="redirect_to" value="<?= url('onboarding') ?>" />

        <div class="form-group">
            <label for="locale">
                <span class="icon icon--language">
                    <?= _('Choose your language') ?>
                </span>
            </label>

            <select
                id="locale"
                name="locale"
                data-action="form-autosubmit#submit"
            >
                <?php foreach ($available_locales as $locale_value => $locale_name): ?>
                    <option
                        value="<?= $locale_value ?>"
                        <?= $locale_value === $current_locale ? 'selected' : '' ?>
                    >
                        <?= $locale_name ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
    </form>

    <hr />

    <p class="paragraph--featured">
        <strong><?= _f('The few next screens will explain you the main principles of %s.', $brand) ?></strong>
    </p>

    <p class="paragraph--centered">
        <?= _f('There’s not much to know before getting started with %s. This onboarding should take less than 5 minutes of your time.', $brand) ?>
    </p>

    <p class="paragraph--centered">
        <a class="anchor--action" href="<?= url('onboarding', ['step' => 2]) ?>">
            <?= _('Continue') ?>
        </a>
    </p>

    <hr />

    <p class="paragraph--centered">
        <a href="<?= url('home') ?>">
            <?= _('Skip the onboarding') ?>
        </a>
    </p>
</div>
