<?php
    $this->layout('base.phtml', [
        'title' => _('Collection group'),
        'canonical' => url_full('edit group collection', ['id' => $collection->id]),
        'has_errors' => $form->isInvalid(),
        'modal_enabled' => true,
    ]);
?>

<div class="section section--small">
    <div class="section__title">
        <h1 id="modal-title"><?= _('Collection group') ?></h1>
    </div>

    <div class="section__intro">
        <p>
            <?= protect($collection->name) ?>
        </p>

        <p>
            <?= _('Groups help you to organize your collections. They are only visible to you on the main collections page.') ?>
        </p>
    </div>

    <form method="post" action="<?= url('update group collection', ['id' => $collection->id]) ?>">
        <?= $this->include('alerts/_error.phtml', ['message' => $form->error('@base')]) ?>

        <div class="form-group group-selector" data-controller="group-selector">
            <div class="group-selector__group-input" data-group-selector-target="groupInput">
                <label for="name">
                    <?= _('How to name the group?') ?>
                    <span class="label__help">
                        <?= _f('(max. %d characters)', $form->group_name_max_length) ?>
                    </span>
                </label>

                <?php if ($form->isInvalid('name')): ?>
                    <p id="name-error" class="form-group__error">
                        <?= _('Error:') ?>
                        <?= $form->error('name') ?>
                    </p>
                <?php endif; ?>

                <input
                    id="name"
                    name=""
                    type="text"
                    value="<?= protect($form->name) ?>"
                    list="group-names"
                    autocomplete="off"
                    autofocus
                    maxlength="<?= $form->group_name_max_length ?>"
                    data-group-selector-target="input"
                    aria-describedby="name-desc"
                    <?php if ($form->isInvalid('name')): ?>
                        aria-errormessage="name-error"
                        aria-invalid="true"
                    <?php endif; ?>
                />

                <datalist id="group-names">
                    <?php foreach ($form->groups() as $group): ?>
                        <option value="<?= protect($group->name) ?>">
                    <?php endforeach; ?>
                </datalist>
            </div>

            <div class="group-selector__group-select" data-group-selector-target="groupSelect">
                <label for="name">
                    <?= _('Select a group') ?>
                </label>

                <?php if ($form->isInvalid('name')): ?>
                    <p id="name-error" class="form-group__error">
                        <?= _('Error:') ?>
                        <?= $form->error('name') ?>
                    </p>
                <?php endif; ?>

                <div class="form-group__stack">
                    <select
                        id="name"
                        name="name"
                        data-group-selector-target="select"
                        aria-describedby="name-desc"
                     >
                         <option <?= $form->name === '' ? 'selected' : '' ?> value="">
                            <?= _('No groups') ?>
                        </option>

                        <?php foreach ($form->groups() as $group): ?>
                            <option <?= $form->isGroupSelected($group) ? 'selected' : '' ?> value="<?= $group->name ?>">
                                <?= protect($group->name) ?>
                            </option>
                        <?php endforeach; ?>
                    </select>

                    <button type="button" data-action="group-selector#showInput">
                        <?= icon('plus') ?>
                        <?= _('New') ?>
                    </button>
                </div>
            </div>
        </div>

        <div class="form__actions">
            <button type="submit" class="button--primary">
                <?= _('Save changes') ?>
            </button>
        </div>

        <input type="hidden" name="csrf_token" value="<?= csrf_token($form) ?>" />
    </form>
</div>
