<?php
    $this->layout('base.phtml', [
        'title' => _('Collection group'),
        'canonical' => url_full('edit group collection', ['id' => $collection->id]),
        'back' => [
            'href' => url('collection', ['id' => $collection->id]),
            'label' => _('Collection'),
        ],
    ]);
?>

<div class="section">
    <div class="section__title">
        <h1 id="modal-title"><?= _('Collection group') ?></h1>
    </div>

    <div class="section__intro">
        <p>
            <?= protect($collection->name) ?>
        </p>

        <p>
            <?= _('Groups help you to organize your collections. They are only visible to you on the main collections page.') ?>
        </p>
    </div>

    <form method="post" action="<?= url('update group collection', ['id' => $collection->id]) ?>">
        <?php if ($error): ?>
            <p class="form__error">
                <?= $error ?>
            </p>
        <?php endif; ?>

        <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />
        <input type="hidden" name="from" value="<?= $from ?>" />

        <div class="form-group <?= isset($errors['name']) ? 'form-group--invalid' : '' ?>">
            <label for="name">
                <?= _('How to name the group?') ?>
            </label>

            <p class="form-group__caption">
                <?= _f('The name must not be longer than %d characters.', $name_max_length) ?>
            </p>

            <input
                id="name"
                name="name"
                type="text"
                required
                value="<?= $name ?>"
                list="group-names"
                autocomplete="off"
                autofocus
                maxlength="<?= $name_max_length ?>"
            />

            <datalist id="group-names">
                <?php foreach ($groups as $group): ?>
                    <option value="<?= protect($group->name) ?>">
                <?php endforeach; ?>
            </datalist>

            <?php if (isset($errors['name'])): ?>
                <p class="form-group__error">
                    <?= $errors['name'] ?>
                </p>
            <?php endif; ?>
        </div>

        <div class="form__actions">
            <button type="submit" class="button--primary">
                <?= _('Save changes') ?>
            </button>
        </div>
    </form>
</div>
