<?php
    $this->layout('base.phtml', [
        'title' => _('Share a link on Mastodon'),
        'canonical' => url_full('new link mastodon thread', ['id' => $link->id]),
        'has_errors' => $form->isInvalid(),
        'modal_enabled' => true,
    ]);
?>

<div class="section">
    <div class="section__title">
        <h1 id="modal-title"><?= _('Share a link on Mastodon') ?></h1>
    </div>

    <form
        data-turbo-preserve-scroll
        method="post"
        action="<?= url('create link mastodon thread', ['id' => $link->id]) ?>"
        data-controller="items"
        data-items-index-value="<?= count($form->contents) ?>"
    >
        <?= $this->include('alerts/_error.phtml', ['message' => $form->error('@base')]) ?>

        <?php if ($form->isInvalid('contents')): ?>
            <p id="contents-error" class="form-group__error">
                <?= _('Error:') ?>
                <?= $form->error('contents') ?>
            </p>
        <?php endif; ?>

        <div class="thread">
            <div data-items-target="container">
                <?php foreach ($form->contents as $index => $content): ?>
                    <div
                        class="thread__post form-group"
                        data-items-target="item"
                        data-controller="characters-counter"
                        data-characters-counter-max-value="<?= $form->maxCharacters() ?>"
                    >
                        <textarea
                            id="contents-<?= $index ?>"
                            name="contents[]"
                            data-characters-counter-target="source"
                            data-action="characters-counter#updateCounter"
                            aria-label="<?= _('Post #__number__') ?>"
                        ><?= protect($content) ?></textarea>

                        <div class="cols cols--always cols--gap-small cols--center">
                            <p class="thread__post-counter col--extend" aria-live="polite" data-characters-counter-target="counter">
                            </p>

                            <?php if ($index > 0): ?>
                                <div>
                                    <button
                                        type="button"
                                        class="button--icon button--ghost"
                                        data-action="items#removeItem"
                                    >
                                        <?= icon('times') ?>
                                        <span class="sr-only">
                                            <?= _('Remove from thread') ?>
                                        </span>
                                    </button>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>

            <div class="thread__new-button form-group">
                <button type="button" data-action="items#addItem">
                    <?= icon('plus-circle') ?>
                    <?= _('Add a post to thread') ?>
                </button>
            </div>
        </div>

        <template data-items-target="prototype">
            <div
                class="thread__post form-group"
                data-items-target="item"
                data-controller="characters-counter"
                data-characters-counter-max-value="<?= $form->maxCharacters() ?>"
            >
                <textarea
                    id="contents-__index__"
                    name="contents[]"
                    data-characters-counter-target="source"
                    data-action="characters-counter#updateCounter"
                    aria-label="<?= _('Post #__number__') ?>"
                ><?= $form->defaultContent() ?></textarea>

                <div class="cols cols--always cols--gap-small cols--center">
                    <p class="thread__post-counter col--extend" aria-live="polite" data-characters-counter-target="counter">
                    </p>

                    <div>
                        <button
                            type="button"
                            class="button--icon button--ghost"
                            data-action="items#removeItem"
                        >
                            <?= icon('times') ?>
                            <span class="sr-only">
                                <?= _('Remove from thread') ?>
                            </span>
                        </button>
                    </div>
                </div>
            </div>
        </template>

        <div class="form__actions">
            <button type="submit" class="button--primary">
                <?= _('Share on Mastodon') ?>
            </button>
        </div>

        <input type="hidden" name="csrf_token" value="<?= csrf_token($form) ?>" />
    </form>
</div>
