name: flus

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile.php
        restart: unless-stopped
        volumes:
            - ../..:/var/www/html:z
            - composer:/tmp
        environment:
            - SEED
            - MOCK_HOST=http://nginx:8001
        healthcheck:
            test: "php-fpm -t"
            interval: 1s
            retries: 30
        depends_on:
            database:
                condition: service_healthy
        user: $USER

    job_worker:
        build:
            context: .
            dockerfile: Dockerfile.php
        restart: unless-stopped
        command: php cli jobs watch
        volumes:
            - ../..:/var/www/html:z
            - composer:/tmp
        depends_on:
            database:
                condition: service_healthy
        user: $USER

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "${PORT:-8000}:8000"
            - "8001:8001"
        volumes:
            - ../..:/var/www/html:z
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:z
        depends_on:
            php:
                condition: service_healthy

    database:
        image: postgres:13-alpine
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: flus_development
        ports:
            - "5432:5432"
        healthcheck:
            test: "pg_isready -U postgres -d flus_development"
            interval: 1s
            retries: 30

    mailpit:
        image: axllent/mailpit
        restart: unless-stopped
        ports:
            - "8025:8025"
            - "1025:1025"

    bundler:
        build:
            context: .
            dockerfile: Dockerfile.node
        restart: unless-stopped
        command: npm run watch
        working_dir: /app
        volumes:
            - ../..:/app:z
        user: $USER

volumes:
    composer: {}
