<?php
    $this->layout('base.phtml', [
        'title' => _('News'),
        'current_tab' => 'news',
    ]);
?>

<div class="section">
    <div class="section__title">
        <h1><?= _('News') ?></h1>
    </div>

    <p class="section__intro">
        <?= _('Get about 1 hour of reading suggestions from your bookmarks.') ?>
    </p>

    <?php if ($news_links): ?>
        <div class="cards cards--in-column">
            <?php foreach ($news_links as $news_link): ?>
                <div class="card">
                    <div class="card__body">
                        <h2 class="card__title">
                            <?= $this->protect($news_link->title) ?>
                        </h2>

                        <p class="card__details">
                            <?= $this->protect($news_link->host()) ?>&nbsp;·&nbsp;<?= format_reading_time($news_link->reading_time) ?>
                        </p>

                        <?php if ($news_link->url_in_bookmarks): ?>
                            <p>
                                <?= _('In your bookmarks') ?>

                                <?php if ($news_link->url_collections_count > 0): ?>
                                    <?= _nf(
                                        ' and %d collection',
                                        ' and %d collections',
                                        $news_link->url_collections_count,
                                        $news_link->url_collections_count
                                    ) ?>
                                <?php endif; ?>

                                –

                                <a href="<?= url('link', ['id' => $news_link->matchingLink()->id]) ?>">
                                    <?= _('see') ?>
                                </a>
                            </p>
                        <?php elseif ($news_link->url_collections_count > 0): ?>
                            <p>
                                <?= _nf(
                                    'In %d collection',
                                    'In %d collections',
                                    $news_link->url_collections_count,
                                    $news_link->url_collections_count
                                ) ?>

                                –

                                <a href="<?= url('link', ['id' => $news_link->matchingLink()->id]) ?>">
                                    <?= _('see') ?>
                                </a>
                            </p>
                        <?php endif; ?>
                    </div>

                    <div class="card__footer">
                        <form method="post" action="<?= url('read news later', ['id' => $news_link->id]) ?>">
                            <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />

                            <button
                                class="button--ghost button--smaller"
                                title="<?= _('Remove from the news page') ?>"
                                aria-label="<?= _('Remove from the news page') ?>"
                            >
                                <i class="icon icon--only icon--times"></i>
                            </button>
                        </form>

                        <div class="card__footer-group">
                            <a
                                class="anchor--action icon icon--anchor icon--link"
                                target="_blank"
                                rel="noopener noreferrer"
                                href="<?= $news_link->url ?>"
                            >
                                <?= _('open') ?>
                            </a>

                            <form method="post" action="<?= url('read news', ['id' => $news_link->id]) ?>">
                                <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />

                                <button
                                    class="button--small"
                                    title="<?= _('Remove from the news page and bookmarks') ?>"
                                    aria-label="<?= _('Remove from the news page and bookmarks') ?>"
                                >
                                    <?= _('Mark as read') ?>
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    <?php else: ?>
        <form class="form--centered" method="post" action="<?= url('fill news') ?>">
            <?php if ($error): ?>
                <p class="form__error">
                    <?= $error ?>
                </p>
            <?php endif; ?>

            <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />

            <div class="form__actions form__actions--centered">
                <button type="submit" class="button--primary">
                    <?= _('Get new suggestions') ?>
                </button>
            </div>
        </form>
    <?php endif; ?>
</div>
