<?php
    $this->layout('base.phtml', [
        'title' => _('News'),
        'current_tab' => 'news',
    ]);
?>

<div class="section" data-controller="back-storage" data-back-storage-type="link">
    <div class="section__title">
        <h1><?= _('News') ?></h1>
    </div>

    <div class="section__intro">
        <p>
            <?= format_news_preferences($news_preferences) ?>
        </p>

        <?php if (!$news_links): ?>
            <p>
                <a href="<?= url('news preferences') ?>">
                    <?= _('Configure') ?>
                </a>
            </p>
        <?php endif; ?>
    </div>

    <?php if ($news_links): ?>
        <div class="cards cards--in-column">
            <?php foreach ($news_links as $news_link): ?>
                <div class="card card--fluid">
                    <div class="card__body">
                        <h2 class="card__title">
                            <a
                                class="anchor--hidden"
                                target="_blank"
                                rel="noopener noreferrer"
                                tabindex="-1"
                                href="<?= $news_link->url ?>"
                            >
                                <?= $this->protect($news_link->title) ?>
                            </a>
                        </h2>

                        <p class="card__details">
                            <span class="card__ellipsis"><?= $this->protect($news_link->host()) ?></span>&nbsp;·&nbsp;<?= format_reading_time($news_link->reading_time) ?>
                        </p>

                        <?php if ($news_link->url_in_bookmarks): ?>
                            <p>
                                <?= _('In your bookmarks') ?>

                                <?php if ($news_link->url_collections_count > 0): ?>
                                    <?= _nf(
                                        ' and %d collection',
                                        ' and %d collections',
                                        $news_link->url_collections_count,
                                        $news_link->url_collections_count
                                    ) ?>
                                <?php endif; ?>

                                (<a href="<?= url('link', ['id' => $news_link->matchingLink()->id]) ?>"><?= _('see') ?></a>)
                            </p>
                        <?php elseif ($news_link->url_collections_count > 0): ?>
                            <p>
                                <?= _nf(
                                    'In %d collection',
                                    'In %d collections',
                                    $news_link->url_collections_count,
                                    $news_link->url_collections_count
                                ) ?>

                                (<a href="<?= url('link', ['id' => $news_link->matchingLink()->id]) ?>"><?= _('see') ?></a>)
                            </p>
                        <?php endif; ?>

                        <?php $matching_followed_links = $news_link->matchingFollowedLinks(); ?>
                        <?php $count_followed_links = count($matching_followed_links); ?>
                        <?php if ($matching_followed_links): ?>
                            <p>
                                <?php $usernames = array_map(function ($link) { return $link->owner()->username; }, $matching_followed_links); ?>
                                <?= $this->protect(human_implode($usernames, ', ', _(' and '))) ?>

                                <?php if ($news_link->url_in_bookmarks || $news_link->url_collections_count > 0): ?>
                                    <?= _n('also added this link.', 'also added this link.', $count_followed_links) ?>
                                <?php else: ?>
                                    <?= _n('added this link.', 'added this link.', $count_followed_links) ?>
                                <?php endif; ?>
                            </p>
                        <?php endif; ?>
                    </div>

                    <div class="card__footer card__footer--align-end">
                        <details
                            class="popup"
                            data-controller="popup"
                            data-action="click@window->popup#close"
                        >
                            <summary class="popup__opener" title="<?= _('Remove from the news page') ?>" tabindex="-1">
                                <button class="button--ghost button--smaller" type="button" data-action="popup#toggle">
                                    <i class="icon icon--only icon--times"></i>
                                    <span class="sr-only">
                                        <?= _('Remove from the news page') ?>
                                    </span>
                                </button>
                            </summary>

                            <nav class="popup__container popup__container--over">
                                <form method="post" action="<?= url('read news later', ['id' => $news_link->id]) ?>">
                                    <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />

                                    <button class="popup__item popup__item--button icon icon--bookmark">
                                        <?= _('Add to bookmarks') ?>
                                    </button>
                                </form>

                                <form method="post" action="<?= url('hide news', ['id' => $news_link->id]) ?>">
                                    <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />

                                    <button class="popup__item popup__item--button icon icon--times">
                                        <?= _('Remove from the news') ?>
                                    </button>
                                </form>
                            </nav>
                        </details>

                        <div class="card__footer-group">
                            <a
                                class="anchor--action icon icon--anchor icon--link"
                                target="_blank"
                                rel="noopener noreferrer"
                                href="<?= $news_link->url ?>"
                            >
                                <?= _('open') ?>
                            </a>

                            <?php if ($has_collections): ?>
                                <button
                                    class="button--small"
                                    data-controller="modal-opener"
                                    data-action="modal-opener#fetch"
                                    data-modal-opener-href="<?= url('add news', ['id' => $news_link->id]) ?>"
                                    aria-haspopup="dialog"
                                    aria-controls="modal"
                                >
                                    <?= _('Add to collections') ?>
                                </button>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    <?php else: ?>
        <?php if ($no_news): ?>
            <p class="paragraph--centered">
                <em><?= _('We found no relevant news for you, what can you do?') ?></em>
            </p>

            <?php $tip_number = random_int(0, 2); ?>
            <?php if ($tip_number === 0): ?>
                <p class="paragraph--centered">
                    <strong><?= _('As you’re navigating on the Internet, bookmark the links you would like to read later.') ?></strong>
                </p>

                <p class="paragraph--centered">
                    <a href="<?= url('news') ?>">
                        <?= _('Ok, fine') ?>
                    </a>
                </p>
            <?php elseif ($tip_number === 1): ?>
                <p class="paragraph--centered">
                    <strong><?= _('Take a break, disconnect from Internet and go for a walk; news can wait.') ?></strong>
                </p>

                <p class="paragraph--centered">
                    <a href="<?= url('news') ?>">
                        <?= _('Ok, fine') ?>
                    </a>
                </p>
            <?php else: ?>
                <p class="paragraph--centered">
                    <strong><?= _('Discover collections created by the community and follow the ones you are interested in.') ?></strong>
                </p>

                <p class="paragraph--centered">
                    <a class="anchor--action" href="<?= url('discover collections') ?>">
                        <?= _('Discover collections') ?>
                    </a>
                </p>
            <?php endif; ?>
        <?php else: ?>
            <form class="form--centered" method="post" action="<?= url('fill news') ?>">
                <?php if ($error): ?>
                    <p class="form__error">
                        <?= $error ?>
                    </p>
                <?php endif; ?>

                <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />

                <div class="form__actions form__actions--centered">
                    <button type="submit" class="button--primary">
                        <?= _('Get new suggestions') ?>
                    </button>
                </div>
            </form>

            <img
                class="illustration illustration--centered"
                alt=""
                src="<?= url_static('illustrations/reading.svg') ?>"
                height="250"
            />
        <?php endif; ?>
    <?php endif; ?>
</div>
