<?php
    $this->layout('base.phtml', [
        'title' => _('News'),
        'current_tab' => 'news',
    ]);
?>

<div class="section">
    <div class="section__title">
        <h1><?= _('News') ?></h1>
    </div>

    <p class="section__intro">
        <?= _('Get about 1 hour of reading from your bookmarks and followed collections.') ?>
    </p>

    <?php if ($news_links): ?>
        <div class="cards cards--in-column">
            <?php foreach ($news_links as $news_link): ?>
                <div class="card">
                    <div class="card__body">
                        <h2 class="card__title">
                            <a
                                class="anchor--hidden"
                                target="_blank"
                                rel="noopener noreferrer"
                                tabindex="-1"
                                href="<?= $news_link->url ?>"
                            >
                                <?= $this->protect($news_link->title) ?>
                            </a>
                        </h2>

                        <p class="card__details">
                            <?= $this->protect($news_link->host()) ?>&nbsp;·&nbsp;<?= format_reading_time($news_link->reading_time) ?>
                        </p>

                        <?php if ($news_link->url_in_bookmarks): ?>
                            <p>
                                <?= _('In your bookmarks') ?>

                                <?php if ($news_link->url_collections_count > 0): ?>
                                    <?= _nf(
                                        ' and %d collection',
                                        ' and %d collections',
                                        $news_link->url_collections_count,
                                        $news_link->url_collections_count
                                    ) ?>
                                <?php endif; ?>

                                –

                                <a href="<?= url('link', ['id' => $news_link->matchingLink()->id]) ?>">
                                    <?= _('see') ?>
                                </a>
                            </p>
                        <?php elseif ($news_link->url_collections_count > 0): ?>
                            <p>
                                <?= _nf(
                                    'In %d collection',
                                    'In %d collections',
                                    $news_link->url_collections_count,
                                    $news_link->url_collections_count
                                ) ?>

                                –

                                <a href="<?= url('link', ['id' => $news_link->matchingLink()->id]) ?>">
                                    <?= _('see') ?>
                                </a>
                            </p>
                        <?php endif; ?>
                    </div>

                    <div class="card__footer card__footer--align-end">
                        <details
                            class="popup"
                            data-controller="popup"
                            data-action="click@window->popup#close"
                        >
                            <summary class="popup__opener" title="<?= _('Remove from the news page') ?>" tabindex="-1">
                                <button class="button--ghost button--smaller" type="button" data-action="popup#toggle">
                                    <i class="icon icon--only icon--times"></i>
                                    <span class="sr-only">
                                        <?= _('Remove from the news page') ?>
                                    </span>
                                </button>
                            </summary>

                            <nav class="popup__container popup__container--over">
                                <form method="post" action="<?= url('read news later', ['id' => $news_link->id]) ?>">
                                    <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />

                                    <button class="popup__item popup__item--button icon icon--bookmark">
                                        <?= _('I’ll read it later') ?>
                                    </button>
                                </form>

                                <form method="post" action="<?= url('hide news', ['id' => $news_link->id]) ?>">
                                    <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />

                                    <button class="popup__item popup__item--button icon icon--thumbs-down">
                                        <?= _('I’m not interested') ?>
                                    </button>
                                </form>
                            </nav>
                        </details>

                        <div class="card__footer-group">
                            <a
                                class="anchor--action icon icon--anchor icon--link"
                                target="_blank"
                                rel="noopener noreferrer"
                                href="<?= $news_link->url ?>"
                            >
                                <?= _('open') ?>
                            </a>

                            <button
                                class="button--small"
                                data-controller="modal-opener"
                                data-action="modal-opener#fetch"
                                data-modal-opener-href="<?= url('add news', ['id' => $news_link->id]) ?>"
                                aria-haspopup="dialog"
                                aria-controls="modal"
                            >
                                <?= _('Add to collections') ?>
                            </a>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    <?php else: ?>
        <form class="form--centered" method="post" action="<?= url('fill news') ?>">
            <?php if ($error): ?>
                <p class="form__error">
                    <?= $error ?>
                </p>
            <?php endif; ?>

            <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />

            <div class="form__actions form__actions--centered">
                <button type="submit" class="button--primary">
                    <?= _('Get new suggestions') ?>
                </button>
            </div>
        </form>
    <?php endif; ?>
</div>
