<?php
    $this->layout('base.phtml', [
        'title' => _('New link'),
        'current_page' => 'search link',
    ]);
?>

<div class="section" data-controller="back-storage" data-back-storage-type="link,collection">
    <div class="section__title">
        <h1 id="modal-title"><?= _('New link') ?></h1>
    </div>

    <form method="post" action="<?= url('search link') ?>">
        <?php if ($error): ?>
            <p class="form__error">
                <?= $error ?>
            </p>
        <?php endif; ?>

        <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />

        <div class="form-group <?= isset($errors['url']) ? 'form-group--invalid' : '' ?>">
            <label for="url">
                <?= _('What’s the <abbr>URL</abbr> of the link?') ?>
            </label>

            <div class="form-group__stack">
                <input
                    id="url"
                    name="url"
                    type="url"
                    required
                    value="<?= $url ?>"
                    autocomplete="off"
                    autofocus
                />

                <button type="submit" class="button--primary no-mobile">
                    <?= _('Search') ?>
                </button>
            </div>

            <?php if (isset($errors['url'])): ?>
                <p class="form-group__error">
                    <?= $errors['url'] ?>
                </p>
            <?php endif; ?>
        </div>

        <div class="form__actions only-mobile">
            <button type="submit" class="button--primary">
                <?= _('Search') ?>
            </button>
        </div>
    </form>

    <?php if ($existing_link || $default_link): ?>
        <div class="cards cards--centered">
            <?php if ($existing_link): ?>
                <div class="card">
                    <a
                        class="anchor--hidden"
                        target="_blank"
                        rel="noopener noreferrer"
                        tabindex="-1"
                        href="<?= protect($existing_link->url) ?>"
                    >
                        <img class="card__image" alt="" src="<?= url_media('cards', $existing_link->image_filename) ?>" />
                    </a>

                    <div class="card__body">
                        <h2 class="card__title">
                            <a
                                class="anchor--hidden"
                                target="_blank"
                                rel="noopener noreferrer"
                                tabindex="-1"
                                href="<?= protect($existing_link->url) ?>"
                            >
                                <?= protect($existing_link->title) ?>
                            </a>
                        </h2>

                        <p class="card__text card__text--oneline">
                            <?php if (!$existing_link->fetched_at): ?>
                                <span class="icon--spin">
                                    <?= icon('sync') ?>
                                    <?= _('ongoing synchronisation…') ?>
                                </span>
                            <?php else: ?>
                                <span class="card__ellipsis"><?= protect($existing_link->host()) ?></span>&nbsp;·&nbsp;<?= format_reading_time($existing_link->reading_time) ?>
                            <?php endif; ?>
                        </p>

                        <p class="card__text">
                            <a href="<?= url('link', ['id' => $existing_link->id]) ?>">
                                <?= icon('comment') ?>
                                <?= _nf('%d comment', '%d comments', $existing_link->number_comments, $existing_link->number_comments) ?>
                            </a>
                        </p>
                    </div>

                    <div class="card__footer card__footer--centered">
                        <button
                            data-controller="modal-opener"
                            data-action="modal-opener#fetch"
                            data-modal-opener-href="<?= url('link collections', ['id' => $existing_link->id, 'from' => url('show search link', ['url' => $existing_link->url])]) ?>"
                            aria-haspopup="dialog"
                            aria-controls="modal"
                        >
                            <?= icon('collection') ?>
                            <?= _('Edit') ?>
                        </button>
                    </div>
                </div>
            <?php elseif ($default_link && !($default_link->isFeedUrl() && $feeds)): ?>
                <div class="card">
                    <a
                        class="anchor--hidden"
                        target="_blank"
                        rel="noopener noreferrer"
                        tabindex="-1"
                        href="<?= protect($default_link->url) ?>"
                    >
                        <img class="card__image" alt="" src="<?= url_media('cards', $default_link->image_filename) ?>" />
                    </a>

                    <div class="card__body">
                        <h2 class="card__title">
                            <a
                                class="anchor--hidden"
                                target="_blank"
                                rel="noopener noreferrer"
                                tabindex="-1"
                                href="<?= protect($default_link->url) ?>"
                            >
                                <?= protect($default_link->title) ?>
                            </a>
                        </h2>

                        <p class="card__text card__text--oneline">
                            <?php if (!$default_link->fetched_at): ?>
                                <span class="icon--spin">
                                    <?= icon('sync') ?>
                                    <?= _('ongoing synchronisation…') ?>
                                </span>
                            <?php else: ?>
                                <span class="card__ellipsis"><?= protect($default_link->host()) ?></span>&nbsp;·&nbsp;<?= format_reading_time($default_link->reading_time) ?>
                            <?php endif; ?>
                        </p>
                    </div>

                    <div class="card__footer card__footer--centered">
                        <button
                            data-controller="modal-opener"
                            data-action="modal-opener#fetch"
                            data-modal-opener-href="<?= url('obtaining link', ['id' => $default_link->id, 'from' => url('show search link', ['url' => $default_link->url])]) ?>"
                            aria-haspopup="dialog"
                            aria-controls="modal"
                        >
                            <?= icon('collection') ?>
                            <?= _('Add') ?>
                        </button>
                    </div>
                </div>
            <?php endif; ?>

            <?php foreach ($feeds as $feed): ?>
                <div class="card card--illustrated" style="background-image: url('<?= url_media('covers', $feed->image_filename, 'collection-card.svg') ?>');">
                    <a class="card__body card__body--large" href="<?= url('collection', ['id' => $feed->id]) ?>">
                        <div class="card__title">
                            <?= protect($feed->name) ?>
                        </div>

                        <p class="card__text card__text--oneline">
                            <?php
                                $via = _f('Feed %s', protect($feed->feedWebsite()));

                                if ($feed->number_links === 0):
                                    $number_links = _('no links');
                                else:
                                    $number_links = _nf('%d link', '%d links', $feed->number_links, $feed->number_links);
                                endif;
                            ?>

                            <span class="card__ellipsis"><?= $via ?></span>&nbsp;·&nbsp;<?= $number_links ?>
                        </p>
                    </a>

                    <div class="card__footer card__footer--centered">
                        <?php if ($current_user->isFollowing($feed->id)): ?>
                            <form method="post" action="<?= url('unfollow collection', ['id' => $feed->id]) ?>">
                                <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />
                                <input type="hidden" name="from" value="<?= url('show search link', ['url' => $default_link->url]) ?>" />
                                <button>
                                    <?= icon('eye-hide') ?>
                                    <?= _('Unfollow') ?>
                                </button>
                            </form>
                        <?php else: ?>
                            <form method="post" action="<?= url('follow collection', ['id' => $feed->id]) ?>">
                                <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />
                                <input type="hidden" name="from" value="<?= url('show search link', ['url' => $default_link->url]) ?>" />
                                <button>
                                    <?= icon('eye') ?>
                                    <?= _('Follow') ?>
                                </button>
                            </form>
                        <?php endif; ?>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php if (!$existing_link && !$default_link && !$feeds): ?>
        <img
            class="illustration illustration--centered"
            alt=""
            src="<?= url_static('illustrations/search.svg') ?>"
            height="250"
        />
    <?php endif; ?>
</div>
