<!DOCTYPE html>
<html lang="<?= localeToBCP47($current_locale) ?>">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="initial-scale=1.0" />
        <?php if(isset($canonical)): ?>
            <link rel="canonical" href="<?= $canonical ?>">
        <?php elseif($current_action_pointer): ?>
            <link rel="canonical" href="<?= url_full($current_action_pointer) ?>">
        <?php endif; ?>

        <link rel="stylesheet" href="<?= url_static('stylesheets/application.css') ?>" data-turbolinks-track="reload">

        <script id="javascript-configuration" type="application/json">
            <?= $this->safe('javascript_configuration') ?>
        </script>
        <script src="<?= url_static('javascripts/application.js') ?>" data-turbolinks-track="reload" defer></script>

        <title><?= $title ?></title>
    </head>

    <body>
        <div class="layout">
            <header class="layout__header header">
                <nav class="header__container">
                    <a class="header__link header__link--home" href="<?= url('home') ?>">
                        flusio
                    </a>

                    <div class="header__separator"></div>

                    <form class="form--inline" method="post" action="<?= url('change locale') ?>">
                        <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />
                        <input type="hidden" name="redirect_to" value="<?= $current_action_pointer ?>" />

                        <div class="form-group">
                            <label for="locale">
                                <?= _('Language') ?>
                            </label>

                            <select id="locale" name="locale">
                                <?php foreach ($available_locales as $locale_value => $locale_name): ?>
                                    <option
                                        value="<?= $locale_value ?>"
                                        <?= $locale_value === $current_locale ? 'selected' : '' ?>
                                    >
                                        <?= $locale_name ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>

                            <button type="submit"><?= _('Change') ?></button>
                        </div>
                    </form>

                    <?php if ($current_user): ?>
                        <a href="<?= url('user deletion') ?>">
                            <?= $current_user->username ?>
                        </a>
                    <?php else: ?>
                        <a class="header__link" href="<?= url('registration') ?>">
                            <?= _('Sign up') ?>
                        </a>
                    <?php endif; ?>
                </nav>
            </header>

            <main class="layout__content">
                <?= $this->safe('content') ?>
            </main>

            <footer class="layout__footer">
                <p>
                    <a href="<?= url('about') ?>">
                        <?= _('About flusio') ?>
                    </a>
                </p>
            </footer>
        </div>
    </body>
</html>
