<!DOCTYPE html>
<html lang="<?= locale_to_bcp_47($current_locale) ?>">
    <head>
        <meta charset="UTF-8" />
        <title><?= $environment === 'development' ? '[dev] ' : '' ?><?= $has_errors ? _('Error: ') : '' ?><?= $title ?> · <?= $brand ?></title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="canonical" href="<?= $canonical ?>">

        <?php foreach ($alternates as $alternate): ?>
            <link rel="alternate" type="<?= $alternate['type'] ?>" title="<?= protect($alternate['title']) ?>" href="<?= $alternate['url'] ?>" />
        <?php endforeach; ?>

        <meta name="application-name" content="<?= $brand ?>">
        <meta name="theme-color" content="#00d0ad">
        <link rel="manifest" href="<?= url('webmanifest') ?>">
        <link rel="icon" type="image/png" sizes="32x32" href="<?= url_static('icons/icon-32.png') ?>">
        <link rel="icon" type="image/png" sizes="16x16" href="<?= url_static('icons/icon-16.png') ?>">
        <link rel="mask-icon" href="<?= url_static('icons/safari-pinned-tab.svg') ?>" color="#00d0ad">
        <link rel="apple-touch-icon" sizes="180x180" href="<?= url_static('icons/icon-180.png') ?>">
        <meta name="apple-mobile-web-app-title" content="<?= $brand ?>">
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="msapplication-TileImage" content="<?= url_static('icons/icon-144.png') ?>">
        <meta name="msapplication-TileColor" content="#00d0ad">

        <link rel="stylesheet" href="<?= url_asset('stylesheets/application.css') ?>" data-turbo-track="reload">

        <script id="javascript-configuration" type="application/json">
            <?= $this->safe('javascript_configuration') ?>
        </script>
        <script src="<?= url_asset('javascripts/application.js') ?>" data-turbo-track="reload" defer></script>

        <meta name="csrf-param" content="csrf" />
        <meta name="csrf-token" content="<?= $csrf_token ?>" />
    </head>

    <body>
        <a
            class="no-mobile accessibility-nav anchor--action"
            href="#main-content"
            tabindex="0"
            data-turbo="false"
        >
            <?= _('Skip to main content') ?>
        </a>

        <div class="layout layout--connected" id="layout">
            <noscript>
                <div class="layout__banner layout__banner--alert">
                    <div class="banner__container">
                        <?= _f('You need to activate JavaScript in order to use %s.', $brand) ?>
                    </div>
                </div>
            </noscript>

            <?php if ($demo): ?>
                <div class="layout__banner">
                    <div class="banner__container">
                        <?= _f('You’re using a demo version of %s, the data are reset every night.', $brand) ?>
                    </div>
                </div>
            <?php endif; ?>

            <?php if (!$current_user->validated_at && $current_page !== 'account validation'): ?>
                <div class="layout__banner">
                    <a class="banner__container banner__container--anchor" href="<?= url('account validation') ?>">
                        <?= _('You must validate your account&nbsp;→') ?>
                    </a>
                </div>
            <?php endif; ?>

            <header class="layout__header header">
                <nav class="header__container">
                    <div class="header__separator"></div>

                    <a
                        class="header__link <?= $current_tab === 'news' ? 'header__link--active' : '' ?>"
                        <?= $current_page === 'news' ? 'aria-current="page"' : '' ?>
                        href="<?= url('news') ?>"
                    >
                        <?= icon('news') ?>
                        <span class="no-mobile">
                            <?= _('News') ?>
                        </span>
                    </a>

                    <a
                        class="header__link <?= $current_tab === 'links' ? 'header__link--active' : '' ?>"
                        <?= $current_page === 'links' ? 'aria-current="page"' : '' ?>
                        href="<?= url('links') ?>"
                    >
                        <?= icon('link') ?>
                        <span class="no-mobile">
                            <?= _('My links') ?>
                        </span>
                    </a>

                    <a
                        class="header__link <?= $current_tab === 'feeds' ? 'header__link--active' : '' ?>"
                        <?= $current_page === 'feeds' ? 'aria-current="page"' : '' ?>
                        href="<?= url('feeds') ?>"
                    >
                        <?= icon('feed') ?>
                        <span class="no-mobile">
                            <?= _('Feeds') ?>
                        </span>
                    </a>

                    <div class="header__separator no-mobile"></div>

                    <a
                        class="header__action"
                        <?= $current_page === 'search link' ? 'aria-current="page"' : '' ?>
                        href="<?= url('show search link') ?>"
                    >
                        <?= icon('plus') ?>
                        <span class="no-mobile">
                            <?= _('New') ?>
                        </span>
                    </a>

                    <details
                        class="header__avatar-container header__secondary popup"
                        data-controller="popup"
                        data-action="toggle->popup#update click@window->popup#closeOnClickOutside keydown->popup#closeOnEscape"
                    >
                        <summary class="popup__opener" title="<?= _f('Menu of %s', protect($current_user->username)) ?>">
                            <img class="header__avatar avatar" src="<?= url_avatar($current_user->avatar_filename) ?>" alt="" />
                            <span class="sr-only">
                                <?= _f('Menu of %s', protect($current_user->username)) ?>
                            </span>
                        </summary>

                        <nav class="popup__container popup__container--left" role="menu">
                            <div class="popup__title"><?= protect($current_user->username) ?></div>

                            <a
                                class="popup__item popup__item--link"
                                <?= $current_page === 'profile' ? 'aria-current="page"' : '' ?>
                                href="<?= url('profile', ['id' => $current_user->id]) ?>"
                                role="menuitem"
                            >
                                <?= icon('avatar') ?>
                                <?= _('Profile') ?>
                            </a>

                            <a
                                class="popup__item popup__item--link"
                                <?= $current_page === 'account' ? 'aria-current="page"' : '' ?>
                                href="<?= url('account') ?>"
                                role="menuitem"
                            >
                                <?= icon('cog') ?>
                                <?= _('Account & data') ?>
                            </a>

                            <a
                                class="popup__item popup__item--link"
                                <?= $current_page === 'security' ? 'aria-current="page"' : '' ?>
                                href="<?= url('security') ?>"
                                role="menuitem"
                            >
                                <?= icon('key') ?>
                                <?= _('Login & security') ?>
                            </a>

                            <div class="popup__separator"></div>

                            <a
                                class="popup__item popup__item--link"
                                <?= $current_page === 'addons' ? 'aria-current="page"' : '' ?>
                                href="<?= url('addons') ?>"
                                role="menuitem"
                            >
                                <?= icon('plugin') ?>
                                <?= _('Add-ons') ?>
                            </a>

                            <a
                                class="popup__item popup__item--link"
                                <?= $current_page === 'support' ? 'aria-current="page"' : '' ?>
                                href="<?= url('support') ?>"
                                role="menuitem"
                            >
                                <?= icon('help') ?>
                                <?= _('Support') ?>
                            </a>

                            <a
                                class="popup__item popup__item--link"
                                <?= $current_page === 'about' ? 'aria-current="page"' : '' ?>
                                href="<?= url('about') ?>"
                                role="menuitem"
                            >
                                <?= icon('info') ?>
                                <?= _('About') ?>
                            </a>

                            <form method="post" action="<?= url('logout') ?>" role="menuitem">
                                <input type="hidden" name="csrf" value="<?= $csrf_token ?>" />
                                <button type="submit" class="popup__item popup__item--button">
                                    <?= icon('logout') ?>
                                    <?= _('Log out') ?>
                                </button>
                            </form>
                        </nav>
                    </details>
                </nav>
            </header>

            <main id="main-content" class="layout__main" tabindex="-1">
                <nav
                    class="layout__back"
                    data-controller="back-button"
                    data-action="popstate@window->back-button#handlePopstate"
                    data-back-button-title-value="<?= $back_options['title'] ?>"
                    data-back-button-reset-value="<?= $back_options['reset'] ? 'true' : 'false' ?>"
                    data-back-button-track-value="<?= $back_options['track'] ? 'true' : 'false' ?>"
                >
                    <a
                        href="#"
                        data-back-button-target="button"
                        data-action="back-button#handleClick"
                    >
                        <?= icon('arrow-left') ?>
                        <?= _('Back') ?>
                    </a>
                </nav>

                <?php if ($search_options['enabled']): ?>
                    <form class="layout__search" method="get" action="">
                        <div class="form-group">
                            <input
                                id="query"
                                name="q"
                                type="text"
                                aria-label="<?= _('Search links by words or URL') ?>"
                                placeholder="<?= _('Search links by words or URL') ?>"
                                required
                                value="<?= $search_options['query'] ?>"
                            />

                            <button type="submit" class="button--ghost">
                                <?= icon('search') ?>
                                <span class="sr-only">
                                    <?= _('Search') ?>
                                </span>
                            </button>
                        </div>
                    </form>
                <?php endif; ?>

                <section class="layout__content">
                    <?= $this->safe('content') ?>
                </section>
            </main>
        </div>

        <div
            id="modal"
            class="modal modal--opened"
            role="dialog"
            data-controller="modal"
            data-action="click->modal#closeOnMask"
            <?php if ($autoload_modal_url): ?>
                data-modal-autoload-value="<?= $autoload_modal_url ?>"
            <?php endif; ?>
            aria-labelledby="modal-title"
            aria-modal="true"
            aria-hidden="true"
            tabindex="-1"
        >
            <section
                class="modal__box"
                data-modal-target="box"
                role="document"
            >
                <header class="modal__header">
                    <button
                        type="button"
                        class="button--ghost button--smaller"
                        data-action="modal#close"
                        aria-label="<?= _('Close') ?>"
                        title="<?= _('Close this window') ?>"
                    >
                        <?= icon('times') ?>
                    </button>
                </header>

                <div data-modal-target="body" class="modal__body">
                    <turbo-frame id="modal-content" data-modal-target="content" target="_top">
                        <div class="spinner"></div>
                    </turbo-frame>
                </div>
            </section>
        </div>
    </body>
</html>
