<!DOCTYPE html>
<html lang="<?= localeToBCP47($current_locale) ?>">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="initial-scale=1.0" />
        <?php if($canonical): ?>
            <link rel="canonical" href="<?= $canonical ?>">
        <?php elseif($current_action_pointer): ?>
            <link rel="canonical" href="<?= url_full($current_action_pointer) ?>">
        <?php endif; ?>
        <link rel="shortcut icon" href="<?= url_static('favicon-32px.png') ?>">

        <link rel="stylesheet" href="<?= url_asset('stylesheets/application.css') ?>" data-turbolinks-track="reload">
        <?php foreach ($styles as $style_name): ?>
            <link rel="stylesheet" href="<?= url_asset("stylesheets/{$style_name}.css") ?>" data-turbolinks-track="reload">
        <?php endforeach; ?>

        <script id="javascript-configuration" type="application/json">
            <?= $this->safe('javascript_configuration') ?>
        </script>
        <script src="<?= url_asset('javascripts/application.js') ?>" data-turbolinks-track="reload" defer></script>

        <title><?= $title ?></title>
    </head>

    <body>
        <div class="layout">
            <?php if ($demo): ?>
                <div class="layout__banner">
                    <div class="banner__container">
                        <?= _('You’re using a demo version of flusio, the data are reset every night.') ?>
                    </div>
                </div>
            <?php endif; ?>

            <?php if (!$current_user->validated_at && $banner): ?>
                <div class="layout__banner">
                    <a class="banner__container banner__container--anchor" href="<?= url('registration validation') ?>">
                        <?= _('You must validate your registration&nbsp;→') ?>
                    </a>
                </div>
            <?php endif; ?>

            <header class="layout__header header header--turquoise">
                <nav class="header__container">
                    <div class="header__separator"></div>

                    <a
                        class="header__link header__link--icon icon icon--anchor icon--bookmark <?= $current_tab === 'bookmarks' ? 'header__link--active' : '' ?>"
                        href="<?= url('bookmarks') ?>"
                    >
                        <?= _('Bookmarks') ?>
                    </a>

                    <a
                        class="header__link header__link--icon icon icon--anchor icon--collection <?= $current_tab === 'collections' ? 'header__link--active' : '' ?>"
                        href="<?= url('collections') ?>"
                    >
                        <?= _('Collections') ?>
                    </a>

                    <div class="header__separator"></div>

                    <details class="header__link popup" data-controller="popup" data-action="click@window->popup#close">
                        <summary class="popup__opener">
                            <img class="header__image" src="<?= url_static('default-avatar.svg') ?>" alt="" />
                        </summary>

                        <nav class="popup__container">
                            <div class="popup__title"><?= $this->protect($current_user->username) ?></div>

                            <a class="popup__item popup__item--link icon icon--avatar" href="<?= url('account') ?>">
                                <?= _('Account') ?>
                            </a>

                            <div class="popup__separator"></div>

                            <form method="post" action="<?= url('logout') ?>">
                                <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />
                                <button type="submit" class="popup__item popup__item--button icon icon--logout">
                                    <?= _('Log out') ?>
                                </button>
                            </form>
                        </nav>
                    </details>

                    <a
                        class="header__link header__link--featured"
                        href="<?= url('new link') ?>"
                        title="<?= _('Add a link') ?>"
                        aria-label="<?= _('Add a link') ?>"
                    >
                        <i class="icon icon--plus-circle icon--anchor"></i>
                    </a>
                </nav>
            </header>

            <main class="layout__content">
                <?= $this->safe('content') ?>
            </main>
        </div>
    </body>
</html>
