<!DOCTYPE html>
<html lang="<?= locale_to_bcp_47($current_locale) ?>">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="shortcut icon" href="<?= url_static('favicon-32px.png') ?>">
        <meta name="robots" content="noindex">

        <link rel="stylesheet" href="<?= url_asset('stylesheets/application.css') ?>" data-turbo-track="reload">

        <title><?= $title ?> · <?= $brand ?></title>
    </head>

    <body>
        <div class="layout layout--error">
            <header class="layout__header">
                <nav>
                    <a class="layout__link" href="<?= url('home') ?>">
                        <?= _('Oh no&nbsp;😟') ?>
                    </a>
                </nav>
            </header>

            <main class="layout__main">
                <?= $this->safe('content') ?>

                <img
                    class="illustration illustration--centered"
                    alt=""
                    src="<?= url_static('illustrations/not-found.svg') ?>"
                    height="250"
                />

                <?php if ($environment !== 'production' && $error): ?>
                    <pre class="layout--error__box"><?= (string)$error ?></pre>
                <?php endif; ?>
            </main>
        </div>
    </body>
</html>
