<!DOCTYPE html>
<html lang="<?= localeToBCP47($current_locale) ?>">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="initial-scale=1.0" />
        <?php if($canonical): ?>
            <link rel="canonical" href="<?= $canonical ?>">
        <?php elseif($current_action_pointer): ?>
            <link rel="canonical" href="<?= url_full($current_action_pointer) ?>">
        <?php endif; ?>

        <meta name="application-name" content="<?= $brand ?>">
        <meta name="theme-color" content="#00d0ad">
        <link rel="manifest" href="<?= url('webmanifest') ?>">
        <link rel="icon" type="image/png" sizes="32x32" href="<?= url_static('icons/icon-32.png') ?>">
        <link rel="icon" type="image/png" sizes="16x16" href="<?= url_static('icons/icon-16.png') ?>">
        <link rel="mask-icon" href="<?= url_static('icons/safari-pinned-tab.svg') ?>" color="#00d0ad">
        <link rel="apple-touch-icon" sizes="180x180" href="<?= url_static('icons/icon-180.png') ?>">
        <meta name="apple-mobile-web-app-title" content="<?= $brand ?>">
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="msapplication-TileImage" content="<?= url_static('icons/icon-144.png') ?>">
        <meta name="msapplication-TileColor" content="#00d0ad">

        <link rel="stylesheet" href="<?= url_asset('stylesheets/application.css') ?>" data-turbolinks-track="reload">
        <?php foreach ($styles as $style_name): ?>
            <link rel="stylesheet" href="<?= url_asset("stylesheets/{$style_name}.css") ?>" data-turbolinks-track="reload">
        <?php endforeach; ?>

        <script id="javascript-configuration" type="application/json">
            <?= $this->safe('javascript_configuration') ?>
        </script>
        <script src="<?= url_asset('javascripts/application.js') ?>" data-turbolinks-track="reload" defer></script>

        <title><?php if ($environment === 'development'): ?>[devmode] <?php endif; ?><?= $title ?> · <?= $brand ?></title>
    </head>

    <body>
        <a
            class="no-mobile accessibility-nav anchor--action"
            href="#main-content"
            tabindex="0"
            data-turbolinks="false"
            data-controller="skip-nav"
            data-action="skip-nav#skip"
        >
            <?= _('Skip to main content') ?>
        </a>

        <div class="layout layout--not-connected" id="layout">
            <noscript>
                <div class="layout__banner layout__banner--alert">
                    <div class="banner__container">
                        <?= _f('You need to activate JavaScript in order to use %s.', $brand) ?>
                    </div>
                </div>
            </noscript>

            <?php if ($demo): ?>
                <div class="layout__banner">
                    <div class="banner__container">
                        <?= _f('You’re using a demo version of %s, the data are reset every night.', $brand) ?>
                    </div>
                </div>
            <?php endif; ?>

            <header class="layout__header header">
                <nav class="header__container">
                    <a class="header__link header__link--home" href="<?= url('home') ?>">
                        <img
                            alt="flus"
                            src="<?= url_static('logo.svg') ?>"
                            width="120"
                            height="40.6"
                        />
                    </a>

                    <div class="header__separator"></div>

                    <?php if ($registrations_opened): ?>
                        <a class="header__link no-mobile" href="<?= url('registration') ?>">
                            <?= _('Sign up') ?>
                        </a>
                    <?php endif; ?>

                    <form
                        class="header__locale-form"
                        method="post"
                        action="<?= url('change locale') ?>"
                        data-controller="form-autosubmit"
                    >
                        <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />
                        <?php if(isset($canonical)): ?>
                            <input type="hidden" name="redirect_to" value="<?= $canonical ?>" />
                        <?php elseif($current_action_pointer): ?>
                            <input type="hidden" name="redirect_to" value="<?= url($current_action_pointer) ?>" />
                        <?php endif; ?>

                        <div class="form-group">
                            <label for="locale" class="icon icon--language" aria-label="<?= _('Choose your language') ?>">
                                <select
                                    id="locale"
                                    name="locale"
                                    data-action="form-autosubmit#submit"
                                >
                                    <?php foreach ($available_locales as $locale_value => $locale_name): ?>
                                        <option
                                            value="<?= $locale_value ?>"
                                            <?= $locale_value === $current_locale ? 'selected' : '' ?>
                                        >
                                            <?= $locale_name ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            </label>
                        </div>
                    </form>
                </nav>
            </header>

            <main id="main-content" class="layout__main" tabindex="-1">
                <?php if ($back): ?>
                    <nav class="layout__back">
                        <?php if (isset($back['js-back-anchor-type'])): ?>
                            <a
                                class="icon icon--anchor icon--left icon--arrow"
                                href="<?= $back['href'] ?>"
                                data-controller="back-anchor"
                                data-back-anchor-type="<?= $back['js-back-anchor-type'] ?>"
                                data-back-anchor-replace="href"
                                <?php if (isset($back['js-back-anchor-mode'])): ?>
                                    data-back-anchor-mode="<?= $back['js-back-anchor-mode'] ?>"
                                <?php endif; ?>
                            >
                                <?= $back['label'] ?>
                            </a>
                        <?php else: ?>
                            <a class="icon icon--anchor icon--left icon--arrow" href="<?= $back['href'] ?>">
                                <?= $back['label'] ?>
                            </a>
                        <?php endif; ?>
                    </nav>
                <?php endif; ?>

                <section class="layout__content">
                    <?= $this->safe('content') ?>
                </section>
            </main>

            <footer class="layout__footer">
                <p>
                    <a href="https://flus.fr">
                        <?= _f('About %s', $brand) ?>
                    </a>
                </p>
            </footer>
        </div>
    </body>
</html>
