<!DOCTYPE html>
<html lang="<?= localeToBCP47($current_locale) ?>">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="canonical" href="<?= url_full($current_action_pointer) ?>">

        <meta name="application-name" content="<?= $brand ?>">
        <meta name="theme-color" content="#00d0ad">
        <link rel="manifest" href="<?= url('webmanifest') ?>">
        <link rel="icon" type="image/png" sizes="32x32" href="<?= url_static('icons/icon-32.png') ?>">
        <link rel="icon" type="image/png" sizes="16x16" href="<?= url_static('icons/icon-16.png') ?>">
        <link rel="mask-icon" href="<?= url_static('icons/safari-pinned-tab.svg') ?>" color="#00d0ad">
        <link rel="apple-touch-icon" sizes="180x180" href="<?= url_static('icons/icon-180.png') ?>">
        <meta name="apple-mobile-web-app-title" content="<?= $brand ?>">
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="msapplication-TileImage" content="<?= url_static('icons/icon-144.png') ?>">
        <meta name="msapplication-TileColor" content="#00d0ad">

        <link rel="stylesheet" href="<?= url_asset('stylesheets/application.css') ?>" data-turbolinks-track="reload">

        <script id="javascript-configuration" type="application/json">
            <?= $this->safe('javascript_configuration') ?>
        </script>
        <script src="<?= url_asset('javascripts/application.js') ?>" data-turbolinks-track="reload" defer></script>

        <meta name="csrf-param" content="csrf" />
        <meta name="csrf-token" content="<?= csrf_token() ?>" />

        <title><?php if ($environment === 'development'): ?>[devmode] <?php endif; ?><?= $title ?></title>
    </head>

    <body>
        <a
            class="no-mobile accessibility-nav anchor--action"
            href="#main-content"
            tabindex="0"
            data-turbolinks="false"
            data-controller="skip-nav"
            data-action="skip-nav#skip"
        >
            <?= _('Skip to main content') ?>
        </a>

        <div class="layout layout--onboarding" id="layout">
            <noscript>
                <div class="layout__banner layout__banner--alert">
                    <div class="banner__container">
                        <?= _f('You need to activate JavaScript in order to use %s.', $brand) ?>
                    </div>
                </div>
            </noscript>

            <header class="layout__header layout__header--not-connected header">
                <nav class="header__container">
                    <a class="header__link header__link--home" href="<?= url('onboarding') ?>">
                        <img
                            alt="flus"
                            src="<?= url_static('logo.svg') ?>"
                            width="120"
                            height="40.6"
                        />
                    </a>

                    <div class="header__separator"></div>

                    <p class="text--secondary">
                        <?= _f('Step %d on %d', $current_step, 6) ?>
                        <?php if ($current_step < 6): ?>
                            (<a href="<?= url('onboarding', ['step' => $current_step + 1]) ?>"><?= _('skip') ?></a>)
                        <?php else: ?>
                            (<?= _('finished') ?>)
                        <?php endif; ?>
                    </p>
                </nav>
            </header>

            <main id="main-content" class="layout__main" tabindex="-1">
                <section class="layout__content">
                    <?= $this->safe('content') ?>
                </section>
            </main>
        </div>
    </body>
</html>
