<?php
    $this->layout('base.phtml', [
        'title' => $title,
        'canonical' => $canonical,
        'current_tab' => $current_tab,
        'current_page' => $current_page,
        'back_options' => [
            'reset' => $reset_back_options,
        ],
    ]);
?>

<div class="section <?= $beta_enabled ? '' : 'section--longbottom' ?>">
    <?php if ($beta_enabled): ?>
        <nav class="reading-nav">
            <ul class="reading-nav__container">
                <li class="reading-nav__item">
                    <a
                        class="reading-nav__anchor"
                        href="<?= url('news') ?>"
                        <?= $current_page === 'news' ? 'aria-current="page"' : '' ?>
                    >
                        <?= _('News') ?>
                    </a>
                </li>

                <li class="reading-nav__item">
                    <a
                        class="reading-nav__anchor"
                        href="<?= url('bookmarks') ?>"
                        <?= $current_page === 'bookmarks' ? 'aria-current="page"' : '' ?>
                    >
                        <?= _('Bookmarks') ?>
                    </a>
                </li>

                <li class="reading-nav__item">
                    <a
                        class="reading-nav__anchor"
                        href="<?= url('read list') ?>"
                        <?= $current_page === 'read' ? 'aria-current="page"' : '' ?>
                    >
                        <?= _('Links read') ?>
                    </a>
                </li>
            </ul>
        </nav>
    <?php endif; ?>

    <?= $this->safe('content') ?>
</div>
