<?php
    if ($pagination->isCurrentFirstPage()) {
        $current_url_params = [];
    } else {
        $current_url_params = [
            'page' => $pagination->currentPage(),
        ];
    }

    if ($beta_enabled) {
        $current_tab = 'links';
        $back = [
            'href' => url('links'),
            'label' => _('Back'),
        ];
    } else {
        $current_tab = 'collections';
        $back = [
            'href' => url('collections'),
            'label' => _('Back'),
        ];
    }

    $this->layout('base.phtml', [
        'title' => $collection->name(),
        'canonical' => url_full('read list', $current_url_params),
        'current_tab' => $current_tab,
        'current_page' => 'collections',
        'back' => $back,
    ]);
?>

<div class="section" data-controller="back-storage" data-back-storage-type-value="link">
    <div class="section__title">
        <h1><?= protect($collection->name()) ?></h1>
    </div>

    <p class="section__intro">
        <?= _('Find here all the links you’ve marked as read.') ?>
    </p>

    <div class="cards">
        <?php foreach ($links as $link): ?>
            <?= $this->include('links/_link.phtml', [
                'link' => $link,
                'from' => url_full('read list', $current_url_params),
                'display_comments' => true,
                'display_edit' => true,
                'display_mark_as_unread' => true,
                'collections_mode' => 'managing',
            ]); ?>
        <?php endforeach; ?>

        <?php for ($i = 0; $i < max(3, (3 - (count($links) % 3))); $i++): ?>
            <div class="card card--shadow no-mobile"></div>
        <?php endfor; ?>
    </div>

    <?= $this->include('_pagination.phtml', ['pagination' => $pagination, 'url' => url('read list')]) ?>

    <img
        class="illustration illustration--centered"
        alt=""
        src="<?= url_static('illustrations/collecting.svg') ?>"
        height="250"
    />
</div>
