<?php
    $this->layout('base.phtml', [
        'title' => _('Importation from an OPML file'),
        'canonical' => url_full('opml'),
        'has_errors' => $form->isInvalid(),
        'back_options' => [
            'track' => false,
        ],
    ]);

    $importation = $form->currentImportation();
?>

<div class="section section--small section--longbottom">
    <div class="section__title">
        <h1><?= _('Importation from an <abbr>OPML</abbr> file') ?></h1>
    </div>

    <p class="section__intro">
        <?= _('<abbr>OPML</abbr> enables you to import your feeds from another software.') ?>
    </p>

    <?php if ($importation && $importation->isOngoing()): ?>
        <p class="paragraph--featured" role="alert">
            <?= _('We’re importing your data…') ?>
        </p>

        <div class="spinner"></div>

        <p class="paragraph--placeholder">
            <?= _('This might take several minutes, please wait.') ?>
        </p>

        <form
             method="get"
             action="<?= url('opml') ?>"
             data-controller="autosubmit"
             data-autosubmit-mode-value="timeout"
             data-autosubmit-timeout-value="4000"
        >
        </form>
    <?php elseif ($importation && $importation->isFinished()): ?>
        <?= $this->include('alerts/_success.phtml', [
            'message' => _('We’ve imported your data from your <abbr>OPML</abbr> file. We’re now going to fetch their links in background.')
        ]) ?>

        <form method="post" action="<?= url('delete importation', ['id' => $importation->id]) ?>">
            <div class="form__actions">
                <button type="submit" class="button--primary">
                    <?= _('Ok!') ?>
                </button>
            </div>

            <input type="hidden" name="csrf_token" value="<?= csrf_token('DeleteImportation') ?>" />
            <input type="hidden" name="redirect_to" value="<?= url('feeds') ?>" />
        </form>
    <?php elseif ($importation && $importation->isInError()): ?>
        <?= $this->include('alerts/_error.phtml', ['message' => protect($importation->error)]) ?>

        <form method="post" action="<?= url('delete importation', ['id' => $importation->id]) ?>">
            <div class="form__actions">
                <button type="submit" class="button--primary">
                    <?= _('Ok!') ?>
                </button>
            </div>

            <input type="hidden" name="csrf_token" value="<?= csrf_token('DeleteImportation') ?>" />
            <input type="hidden" name="redirect_to" value="<?= url('feeds') ?>" />
        </form>
    <?php else: ?>
        <form
            method="post"
            action="<?= url('import opml') ?>"
            data-controller="autosubmit form-file"
            enctype="multipart/form-data"
        >
            <?= $this->include('alerts/_error.phtml', ['message' => $form->error('@base')]) ?>

            <?php if ($form->isInvalid('opml')): ?>
                <p id="opml-error" class="form-group__error text--center">
                    <?= _('Error:') ?>
                    <?= $form->error('opml') ?>
                </p>
            <?php endif; ?>

            <input
                type="file"
                name="opml"
                id="opml"
                accept="<?= $form->acceptedMimetypes() ?>"
                data-action="autosubmit#submit"
                data-form-file-target="file"
                hidden
            />

            <div class="form__actions">
                <button
                    type="button"
                    class="button--primary"
                    data-action="form-file#openFile"
                    aria-describedby="opml-desc"
                    data-autosubmit-target="actionButton"
                >
                    <?= _('Import a file') ?>
                </button>
            </div>

            <input type="hidden" name="csrf_token" value="<?= csrf_token($form) ?>" />
        </form>
    <?php endif; ?>
</div>
