<?php
    $this->layout('base.phtml', [
        'title' => $group->name,
        'current_tab' => 'collections',
        'canonical' => url('group collections', ['id' => $group->id]),
        'back' => [
            'href' => url('collections'),
            'label' => _('Collections'),
        ],
    ]);
?>

<?php if ($collections): ?>
    <div class="cards">
        <?php foreach ($collections as $collection): ?>
            <div class="card card--illustrated" style="background-image: url('<?= url_media('covers', $collection->image_filename, 'collection-card.svg') ?>');">
                <a class="card__body" href="<?= url('collection', ['id' => $collection->id]) ?>">
                    <div class="card__title">
                        <?= protect($collection->name) ?>
                    </div>

                    <p class="card__text">
                        <?php if ($collection->number_links === 0): ?>
                            <?= _('no links') ?>
                        <?php else: ?>
                            <?= _nf('%d link', '%d links', $collection->number_links, $collection->number_links) ?>
                        <?php endif; ?>

                        <?php if ($collection->is_public): ?>
                            <span class="sticker sticker--right">
                                <?= _('public') ?>
                            </span>
                        <?php endif; ?>
                    </p>
                </a>
            </div>
        <?php endforeach; ?>

        <?php for ($i = 0; $i < (3 - (count($collections) % 3)); $i++): ?>
            <div class="card card--shadow no-mobile"></div>
        <?php endfor; ?>
    </div>
<?php endif; ?>

<?php if ($followed_collections): ?>
    <h3 class="group__subtitle">
        <?= _('Followed collections') ?>
    </h3>

    <div class="cards">
        <?php foreach ($followed_collections as $collection): ?>
            <div class="card card--illustrated" style="background-image: url('<?= url_media('covers', $collection->image_filename, 'collection-card.svg') ?>');">
                <a class="card__body" href="<?= url('collection', ['id' => $collection->id]) ?>">
                    <div class="card__title">
                        <?= protect($collection->name) ?>
                    </div>

                    <p class="card__text card__text--oneline">
                        <?php
                            if ($collection->type === 'feed'):
                                $via = _f('Feed %s', protect($collection->feedWebsite()));
                            else:
                                $via = _f('By %s', protect($collection->owner()->username));
                            endif;

                            if ($collection->number_links === 0):
                                $number_links = _('no links');
                            else:
                                $number_links = _nf('%d link', '%d links', $collection->number_links, $collection->number_links);
                            endif;
                        ?>

                        <span class="card__ellipsis"><?= $via ?></span>&nbsp;·&nbsp;<?= $number_links ?>
                    </p>
                </a>
            </div>
        <?php endforeach; ?>

        <?php for ($i = 0; $i < (3 - (count($followed_collections) % 3)); $i++): ?>
            <div class="card card--shadow no-mobile"></div>
        <?php endfor; ?>
    </div>
<?php endif; ?>
