<?php
    $this->layout('base.phtml', [
        'title' => _('Account validation'),
        'current_page' => 'account validation',
        'back' => [
            'href' => url('account'),
            'label' => _('Account'),
        ],
    ]);
?>

<div class="section">
    <div class="section__title">
        <h1><?= _('Account validation') ?></h1>
    </div>

    <?php if (isset($success) && $success): ?>
        <p class="section__intro">
            <?= _('Your account is now validated.') ?>
        </p>

        <p class="paragraph--centered">
            <a class="anchor--action" href="<?= url('home') ?>">
                <?= _('Nice! Go to the home page') ?>
            </a>
        </p>
    <?php else: ?>
        <p class="section__intro">
            <?= _('You must validate your account so we can contact you in case of a change in our end-user license agreement or a problem concerning your account. <strong>You should have received an email containing a link intended to this purpose.</strong>') ?>
        </p>

        <?php if ($status === 'validation_email_sent'): ?>
            <p class="paragraph--featured">
                <?= _f('We’ve just sent you an email at %s', $current_user->email) ?>
            </p>

            <p class="paragraph--centered paragraph--secondary">
                <?= _('Still nothing? Did you check your spam?') ?>
            </p>
        <?php else: ?>
            <?php if ($error): ?>
                <p class="paragraph--centered form__error">
                    <?= $error ?>
                </p>
            <?php endif; ?>

            <form class="form--centered" method="post" action="<?= url('resend validation email') ?>">
                <input type="hidden" name="csrf" value="<?= $csrf_token ?>" />
                <input type="hidden" name="from" value="<?= url('account validation') ?>" />
                <button class="button--primary" type="submit">
                    <?= _('Didn’t receive the email? Resend it') ?>
                </button>
            </form>
        <?php endif; ?>

        <img
            class="illustration illustration--centered"
            alt=""
            src="<?= url_static('illustrations/contact.svg') ?>"
            height="250"
        />
    <?php endif; ?>
</div>
