<?php
    if ($beta_enabled) {
        $current_tab = 'links';
        $back = [
            'href' => url('links'),
            'label' => _('Back'),
        ];
    } else {
        $current_tab = 'bookmarks';
        $back = [];
    }

    $this->layout('base.phtml', [
        'title' => _('Bookmarks'),
        'canonical' => url_full('bookmarks'),
        'current_tab' => $current_tab,
        'current_page' => 'bookmarks',
        'back' => $back,
    ]);
?>

<div class="section" data-controller="back-storage" data-back-storage-type-value="link">
    <div class="section__title">
        <h1><?= protect($collection->name()) ?></h1>
    </div>

    <p class="section__intro">
        <?= _('Place here the links you want to consult later on.') ?>
    </p>

    <div class="cards">
        <div class="card card--action">
            <button
                class="card__button card__button--link"
                data-controller="modal-opener"
                data-action="modal-opener#fetch"
                data-modal-opener-href-value="<?= url('new link', ['collection_id' => $collection->id, 'from' => url('bookmarks')]) ?>"
                aria-haspopup="dialog"
                aria-controls="modal"
            >
                <?= icon('plus-circle') ?><br />
                <?= _('Add a link') ?>
            </button>
        </div>

        <?php foreach ($links as $link): ?>
            <?= $this->include('links/_link.phtml', [
                'link' => $link,
                'from' => url('bookmarks'),
                'display_comments' => true,
                'display_edit' => true,
                'display_mark_as_read' => true,
                'collections_mode' => 'managing',
            ]); ?>
        <?php endforeach; ?>

        <?php for ($i = 0; $i < (3 - ((count($links) + 1) % 3)); $i++): ?>
            <div class="card card--shadow no-mobile"></div>
        <?php endfor; ?>
    </div>

    <img
        class="illustration illustration--centered"
        alt=""
        src="<?= url_static('illustrations/save_to_bookmarks.svg') ?>"
        height="250"
    />
</div>
