<section class="group">
    <header class="group__header">
        <div class="group__icon">
            <?= icon('directory') ?>
        </div>

        <h2 class="group__title">
            <?= protect($group->name) ?>
        </h2>

        <div class="group__separator"></div>

        <button
            class="button--small button--ghost no-mobile"
            type="button"
            data-controller="modal-opener"
            data-action="modal-opener#fetch"
            data-modal-opener-href-value="<?= url('edit group', ['id' => $group->id, 'from' => $from]) ?>"
            aria-haspopup="dialog"
            aria-controls="modal"
        >
            <?= icon('pencil') ?>
            <?= _('Edit') ?>
        </button>

        <button
            class="button--smaller button--ghost only-mobile"
            type="button"
            data-controller="modal-opener"
            data-action="modal-opener#fetch"
            data-modal-opener-href-value="<?= url('edit group', ['id' => $group->id, 'from' => $from]) ?>"
            aria-haspopup="dialog"
            aria-controls="modal"
        >
            <?= icon('pencil') ?>
            <span class="sr-only">
                <?= _('Edit') ?>
            </span>
        </button>
    </header>

    <?php if ($collections): ?>
        <div class="cards">
            <?php foreach ($collections as $collection): ?>
                <?= $this->include('collections/_collection.phtml', [
                    'display_mode' => 'owned',
                    'collection' => $collection,
                ]) ?>
            <?php endforeach; ?>

            <?php for ($i = 0; $i < (3 - (count($collections) % 3)); $i++): ?>
                <div class="card card--shadow no-mobile"></div>
            <?php endfor; ?>
        </div>
    <?php endif; ?>

    <?php if ($followed_collections): ?>
        <h3 class="group__subtitle">
            <?= _('Followed collections') ?>
        </h3>

        <div class="cards">
            <?php foreach ($followed_collections as $collection): ?>
                <?= $this->include('collections/_collection.phtml', [
                    'display_mode' => 'public',
                    'collection' => $collection,
                ]) ?>
            <?php endforeach; ?>

            <?php for ($i = 0; $i < (3 - (count($followed_collections) % 3)); $i++): ?>
                <div class="card card--shadow no-mobile"></div>
            <?php endfor; ?>
        </div>
    <?php endif; ?>
</section>
