<?php
    $this->layout('base.phtml', [
        'title' => _('Group edition'),
        'canonical' => url_full('edit group', ['id' => $group->id]),
        'has_errors' => $form->isInvalid(),
        'modal_enabled' => true,
    ]);
?>

<div class="section">
    <div class="section__title">
        <h1 id="modal-title"><?= _('Group edition') ?></h1>
    </div>

    <form method="post" action="<?= url('update group', ['id' => $group->id]) ?>">
        <?= $this->include('alerts/_error.phtml', ['message' => $form->error('@base')]) ?>

        <div class="form-group">
            <label for="name">
                <?= _('The name of your group') ?>
                <span class="label__help">
                    <?= _f('(max. %d characters)', $form->group_name_max_length) ?>
                </span>
            </label>

            <?php if ($form->isInvalid('name')): ?>
                <p id="name-error" class="form-group__error">
                    <?= _('Error:') ?>
                    <?= $form->error('name') ?>
                </p>
            <?php endif; ?>

            <input
                id="name"
                name="name"
                type="text"
                required
                value="<?= protect($form->name) ?>"
                autocomplete="off"
                autofocus
                maxlength="<?= $form->group_name_max_length ?>"
                <?php if ($form->isInvalid('name')): ?>
                    aria-errormessage="name-error"
                    aria-invalid="true"
                <?php endif; ?>
            />
        </div>

        <div class="form__actions">
            <button type="submit" class="button--primary">
                <?= _('Save changes') ?>
            </button>
        </div>

        <input type="hidden" name="csrf_token" value="<?= csrf_token($form) ?>" />
    </form>

    <form
        class="form--danger"
        method="post"
        action="<?= url('delete group', ['id' => $group->id]) ?>"
        data-turbo-confirm="<?= _('Are you sure that you want to delete this group? The associated collections will NOT be deleted.') ?>"
    >
        <button type="submit" class="button--danger">
            <?= icon('trash') ?>
            <?= _('Delete the group') ?>
        </button>

        <input type="hidden" name="csrf_token" value="<?= csrf_token('groups\\DeleteGroup') ?>" />
    </form>
</div>
