<?php
    $this->layout('base.phtml', [
        'title' => _('Home'),
    ]);
?>

<?php if ($current_user && !$current_user->validated_at): ?>
    <p>
        <?= _('You must validate your registration: you should have received an email containing a link intended to this purpose.') ?>
    </p>

    <?php if ($status === 'validation_email_sent'): ?>
        <p>
            <?= _('We’ve just sent you an email!') ?>
        </p>
    <?php else: ?>
        <form method="post" action="<?= url('resend validation email') ?>">
            <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />
            <button type="submit">
                <?= _('Didn’t receive the email? Resend it') ?>
            </button>
        </form>
    <?php endif; ?>
<?php endif; ?>
