services:
    php:
        image: flus_php:dev
        build:
            context: .
            dockerfile: Dockerfile.php
        restart: unless-stopped
        volumes:
            - ..:/var/www/html:z
            - composer:/tmp
        environment:
            - SEED
            - MOCK_HOST=http://nginx:8001
        user: $USER

    job_worker:
        image: flus_php:dev
        build:
            context: .
            dockerfile: Dockerfile.php
        restart: unless-stopped
        command: php cli jobs watch
        volumes:
            - ..:/var/www/html:z
            - composer:/tmp
        user: $USER

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8000:8000"
            - "8001:8001"
        volumes:
            - ..:/var/www/html:z
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:z

    database:
        image: postgres:13-alpine
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"

    mailpit:
        image: axllent/mailpit
        restart: unless-stopped
        ports:
            - "8025:8025"
            - "1025:1025"

    bundler:
        image: flus_node:dev
        build:
            context: .
            dockerfile: Dockerfile.node
        restart: unless-stopped
        command: npm run watch
        working_dir: /app
        volumes:
            - ..:/app:z
        user: $USER

volumes:
    composer: {}
