<?php
    $this->layout('base.phtml', [
        'title' => _('Importation from Pocket'),
        'canonical' => url_full('pocket'),
        'back_options' => [
            'track' => false,
        ],
    ]);
?>

<div class="section section--small section--longbottom">
    <div class="section__title">
        <h1><?= _('Importation from Pocket') ?></h1>
    </div>

    <p class="section__intro">
        <?= _f('%s enables you to import your links saved in Pocket.', $brand) ?>
    </p>

    <?= $this->include('alerts/_error.phtml', ['message' => $error]) ?>

    <?php if ($importation && $importation->status === 'ongoing'): ?>
        <p class="paragraph--featured">
            <?= _('We’re importing your data from Pocket…') ?>
        </p>

        <div class="spinner"></div>

        <p class="paragraph--placeholder">
            <?= _('This might take several minutes, please wait.') ?>
        </p>

        <form
             method="get"
             action="<?= url('pocket') ?>"
             data-controller="autosubmit"
             data-autosubmit-mode-value="timeout"
             data-autosubmit-timeout-value="4000"
        >
        </form>
    <?php elseif ($importation && $importation->status === 'finished'): ?>
        <p class="paragraph--featured">
            <?= _('We’ve imported your data from Pocket.') ?>
        </p>

        <p class="paragraph--centered">
            <?= _('You should see new links in your collections and/or bookmarks. We’ll fetch their illustrations in background.') ?>
        </p>

        <form method="post" action="<?= url('delete importation', ['id' => $importation->id]) ?>">
            <input type="hidden" name="csrf" value="<?= $csrf_token ?>" />
            <input type="hidden" name="from" value="<?= url('pocket') ?>" />

            <div class="form__actions">
                <button type="submit" class="button--primary">
                    <?= _('Ok!') ?>
                </button>
            </div>
        </form>
    <?php elseif ($importation && $importation->status === 'error'): ?>
        <p class="paragraph--featured">
            <?= _('Oops, a problem occured during your importation.') ?>
        </p>

        <p class="paragraph--centered">
            <?= protect($importation->error) ?>
        </p>

        <form method="post" action="<?= url('delete importation', ['id' => $importation->id]) ?>">
            <input type="hidden" name="csrf" value="<?= $csrf_token ?>" />
            <input type="hidden" name="from" value="<?= url('pocket') ?>" />

            <div class="form__actions">
                <button type="submit" class="button--primary">
                    <?= _('Ok!') ?>
                </button>
            </div>
        </form>
    <?php elseif ($current_user->pocket_access_token): ?>
        <form method="post" action="<?= url('import pocket') ?>">
            <input type="hidden" name="csrf" value="<?= $csrf_token ?>" />

            <div class="form-group pocket-option" data-controller="pocket-option">
                <input
                    type="checkbox"
                    id="ignore-tags"
                    name="ignore_tags"
                    checked
                    data-pocket-option-target="checkbox"
                    data-action="pocket-option#changeCaption"
                    aria-describedby="ignore-tags-caption"
                />

                <label class="label--checkbox" for="ignore-tags">
                    <?= _('Import your links by ignoring the tags') ?>
                </label>

                <p class="form-group__caption form-group__caption--alt" id="ignore-tags-caption">
                    <span data-pocket-option-target="captionTrue">
                        <?= _f('%s will import your links in a collection named “Pocket links”, your tags will be ignored.', $brand) ?>
                    </span>

                    <span data-pocket-option-target="captionFalse">
                        <?= _f('%s will import your links in a collection named “Pocket links” and in collections named after your tags (not recommended if you have a lot of tags).', $brand) ?>
                    </span>
                </p>
            </div>

            <div class="form-group pocket-option" data-controller="pocket-option">
                <input
                    type="checkbox"
                    id="import-bookmarks"
                    name="import_bookmarks"
                    checked
                    data-pocket-option-target="checkbox"
                    data-action="pocket-option#changeCaption"
                    aria-describedby="import-bookmarks-caption"
                />

                <label class="label--checkbox" for="import-bookmarks">
                    <?= _('Import non-archived links in your bookmarks') ?>
                </label>

                <p class="form-group__caption form-group__caption--alt" id="import-bookmarks-caption">
                    <span data-pocket-option-target="captionTrue">
                        <?= _f('%s will import your non-archived Pocket links in your bookmarks.', $brand) ?>
                    </span>

                    <span data-pocket-option-target="captionFalse">
                        <?= _f('%s will leave your bookmarks unchanged.', $brand) ?>
                    </span>
                </p>
            </div>

            <div class="form-group pocket-option" data-controller="pocket-option">
                <input
                    type="checkbox"
                    id="import-favorites"
                    name="import_favorites"
                    checked
                    data-pocket-option-target="checkbox"
                    data-action="pocket-option#changeCaption"
                    aria-describedby="import-favorites-caption"
                />

                <label class="label--checkbox" for="import-favorites">
                    <?= _('Import your Pocket favorites in a dedicated collection') ?>
                </label>

                <p class="form-group__caption form-group__caption--alt" id="import-favorites-caption">
                    <span data-pocket-option-target="captionTrue">
                        <?= _f('%s doesn’t provide favorites, but it’ll import them in a collection named “Pocket favorites”.', $brand) ?>
                    </span>

                    <span data-pocket-option-target="captionFalse">
                        <?= _f('%s doesn’t provide favorites, so they’ll be ignored.', $brand) ?>
                    </span>
                </p>
            </div>

            <div class="form__actions">
                <button type="submit" class="button--primary">
                    <?= _('Start the import') ?>
                </button>
            </div>
        </form>

        <p class="paragraph--centered paragraph--secondary">
            <small>
                <?= _f('connected with account <em>%s</em>', protect($current_user->pocket_username)) ?>
            </small>
        </p>
    <?php else: ?>
        <form method="post" action="<?= url('request pocket access') ?>" data-turbo="false">
            <input type="hidden" name="csrf" value="<?= $csrf_token ?>" />

            <div class="form__actions">
                <button type="submit" class="button--primary">
                    <?= _('Connect to Pocket') ?>
                </button>
            </div>
        </form>
    <?php endif; ?>
</div>
