<turbo-frame id="modal-feeds-new" target="_top">
    <div class="section">
        <div class="section__title">
            <h1 id="modal-title"><?= _('New feed') ?></h1>
        </div>

        <form method="post" action="<?= url('create feed') ?>">
            <?= $this->include('alerts/_error.phtml', ['message' => $error]) ?>

            <input type="hidden" name="csrf" value="<?= $csrf_token ?>" />
            <input type="hidden" name="from" value="<?= $from ?>" />

            <div class="form-group <?= isset($errors['url']) ? 'form-group--invalid' : '' ?>">
                <label for="url">
                    <?= _('What’s the address of the website or feed to follow?') ?>
                </label>

                <input
                    id="url"
                    name="url"
                    type="url"
                    placeholder="https://…"
                    required
                    value="<?= $url ?>"
                    autocomplete="off"
                    autofocus
                    aria-describedby="url-caption"
                />

                <?php if (isset($errors['url'])): ?>
                    <p class="form-group__error">
                        <?= icon('error') ?>
                        <?= $errors['url'] ?>
                    </p>
                <?php endif; ?>

                <p class="form-group__caption" id="url-caption">
                    <?= _('It can be copy-paste from the <abbr>URL</abbr> bar, at the top of your browser.') ?>
                </p>
            </div>

            <div class="form__actions">
                <button type="submit" class="button--primary">
                    <?= _('Add the feed') ?>
                </button>
            </div>
        </form>
    </div>
</turbo-frame>
