<?php
    $this->layout('base.phtml', [
        'title' => _('Feeds'),
        'canonical' => url_full('feeds'),
        'current_tab' => 'feeds',
        'current_page' => 'feeds',
    ]);
?>

<div class="section" data-controller="back-storage" data-back-storage-type-value="collection">
    <div class="section__title">
        <h1><?= _('Feeds') ?></h1>
    </div>

    <p class="section__intro">
        <?= _('All the feeds that you follow are listed here.') ?>
    </p>

    <section class="group">
        <div class="cards">
            <div class="card card--action">
                <button
                    class="card__button"
                    data-controller="modal-opener"
                    data-action="modal-opener#fetch"
                    data-modal-opener-href-value="<?= url('new feed', ['from' => url('feeds')]) ?>"
                    aria-haspopup="dialog"
                    aria-controls="modal"
                >
                    <?= icon('plus') ?><br />
                    <?= _('Add a feed') ?>
                </button>
            </div>

            <?php foreach ($collections_no_group as $collection): ?>
                <div class="card card--illustrated" style="background-image: url('<?= url_media('covers', $collection->image_filename, 'collection-card.svg') ?>');">
                    <a class="card__body" href="<?= url('collection', ['id' => $collection->id]) ?>">
                        <div class="card__title">
                            <?= protect($collection->name) ?>
                        </div>

                        <p class="card__text card__text--oneline">
                            <?php
                                if ($collection->type === 'feed'):
                                    $via = _f('Feed %s', protect($collection->feedWebsite()));
                                else:
                                    $via = _f('By %s', protect($collection->owner()->username));
                                endif;

                                if ($collection->number_links === 0):
                                    $number_links = _('no links');
                                else:
                                    $number_links = _nf('%d link', '%d links', $collection->number_links, $collection->number_links);
                                endif;
                            ?>

                            <span class="card__ellipsis"><?= $via ?></span>&nbsp;·&nbsp;<?= $number_links ?>
                        </p>
                    </a>
                </div>
            <?php endforeach; ?>

            <?php for ($i = 0; $i < (3 - ((count($collections_no_group) + 1) % 3)); $i++): ?>
                <div class="card card--shadow no-mobile"></div>
            <?php endfor; ?>
        </div>
    </section>

    <?php foreach ($groups as $group): ?>
        <?php if (isset($collections_by_group_ids[$group->id])): ?>
            <?php
                echo $this->include('groups/_group.phtml', [
                    'display_mode' => 'followed',
                    'group' => $group,
                    'collections' => $collections_by_group_ids[$group->id],
                    'from' => url('feeds'),
                ]);
            ?>
        <?php endif; ?>
    <?php endforeach; ?>
</div>
