<?php
    $this->layout('base.phtml', [
        'title' => _('Feeds'),
        'canonical' => url_full('feeds'),
        'current_tab' => 'feeds',
        'current_page' => 'feeds',
    ]);
?>

<div class="section" data-controller="back-storage" data-back-storage-type-value="collection">
    <div class="section__title">
        <h1><?= _('Feeds') ?></h1>
    </div>

    <p class="section__intro">
        <?= _('All the feeds that you follow are listed here.') ?>
    </p>

    <section class="group">
        <div class="cards">
            <?php foreach ($no_group_followed_collections as $collection): ?>
                <div class="card card--illustrated" style="background-image: url('<?= url_media('covers', $collection->image_filename, 'collection-card.svg') ?>');">
                    <a class="card__body" href="<?= url('collection', ['id' => $collection->id]) ?>">
                        <div class="card__title">
                            <?= protect($collection->name) ?>
                        </div>

                        <p class="card__text card__text--oneline">
                            <?php
                                if ($collection->type === 'feed'):
                                    $via = _f('Feed %s', protect($collection->feedWebsite()));
                                else:
                                    $via = _f('By %s', protect($collection->owner()->username));
                                endif;

                                if ($collection->number_links === 0):
                                    $number_links = _('no links');
                                else:
                                    $number_links = _nf('%d link', '%d links', $collection->number_links, $collection->number_links);
                                endif;
                            ?>

                            <span class="card__ellipsis"><?= $via ?></span>&nbsp;·&nbsp;<?= $number_links ?>
                        </p>
                    </a>
                </div>
            <?php endforeach; ?>

            <?php for ($i = 0; $i < (3 - (count($no_group_followed_collections) % 3)); $i++): ?>
                <div class="card card--shadow no-mobile"></div>
            <?php endfor; ?>
        </div>
    </section>

    <?php foreach ($groups as $group): ?>
        <section class="group">
            <header class="group__header">
                <div class="group__icon">
                    <?= icon('directory') ?>
                </div>

                <h2 class="group__title">
                    <?= protect($group->name) ?>
                </h2>

                <div class="group__separator"></div>

                <button
                    class="button--small button--ghost no-mobile"
                    type="button"
                    data-controller="modal-opener"
                    data-action="modal-opener#fetch"
                    data-modal-opener-href-value="<?= url('edit group', ['id' => $group->id, 'from' => url('collections')]) ?>"
                    aria-haspopup="dialog"
                    aria-controls="modal"
                >
                    <?= icon('pencil') ?>
                    <?= _('Edit') ?>
                </button>

                <button
                    class="button--smaller button--ghost only-mobile"
                    type="button"
                    data-controller="modal-opener"
                    data-action="modal-opener#fetch"
                    data-modal-opener-href-value="<?= url('edit group', ['id' => $group->id, 'from' => url('collections')]) ?>"
                    aria-haspopup="dialog"
                    aria-controls="modal"
                >
                    <?= icon('pencil') ?>
                    <span class="sr-only">
                        <?= _('Edit') ?>
                    </span>
                </button>
            </header>

            <turbo-frame id="group-<?= $group->id ?>" src="<?= url('group collections', ['id' => $group->id, 'only' => 'followed']) ?>" target="_top">
                <div class="spinner"></div>
            </turbo-frame>
        </section>
    <?php endforeach; ?>
</div>
