<?php
    $this->layout('base.phtml', [
        'title' => _('New feed'),
        'canonical' => url_full('new feed'),
        'current_page' => 'new feed',
        'has_errors' => $error || $errors,
        'modal_enabled' => true,
    ]);
?>

<div class="section">
    <div class="section__title">
        <h1 id="modal-title"><?= _('New feed') ?></h1>
    </div>

    <form method="post" action="<?= url('create feed') ?>">
        <?= $this->include('alerts/_error.phtml', ['message' => $form->error('@base')]) ?>

        <div class="form-group">
            <label for="url">
                <?= _('What’s the address of the website or feed to follow?') ?>
            </label>

            <?php if ($form->isInvalid('url')): ?>
                <p id="url-error" class="form-group__error">
                    <?= _('Error:') ?>
                    <?= $form->error('url') ?>
                </p>
            <?php endif; ?>

            <input
                id="url"
                name="url"
                type="url"
                placeholder="https://…"
                required
                value="<?= protect($form->url) ?>"
                autocomplete="off"
                autofocus
                aria-describedby="url-caption"
                <?php if ($form->isInvalid('url')): ?>
                    aria-errormessage="url-error"
                    aria-invalid="true"
                <?php endif; ?>
            />

            <p id="url-caption" class="form-group__caption">
                <?= _('It can be copy-paste from the <abbr>URL</abbr> bar, at the top of your browser.') ?>
            </p>
        </div>

        <div class="form__actions">
            <button type="submit" class="button--primary">
                <?= _('Add the feed') ?>
            </button>
        </div>

        <input type="hidden" name="csrf_token" value="<?= csrf_token($form) ?>" />
    </form>
</div>
