<?php
    $this->layout('base.phtml', [
        'title' => _('New feed'),
        'canonical' => url_full('new feed'),
        'current_page' => 'new feed',
        'back' => [
            'href' => url('feeds'),
            'label' => _('Back'),
        ],
    ]);
?>

<?= $this->include('feeds/_new.phtml', [
    'url' => $url,
    'from' => $from,
    'errors' => $errors,
    'error' => $error,
]); ?>
