<?php
    $this->layout('base.phtml', [
        'title' => _('News time filter'),
        'canonical' => url_full('edit collection filter', ['id' => $collection->id]),
        'back' => [
            'href' => url('collection', ['id' => $collection->id]),
            'label' => _('Collection'),
        ],
    ]);
?>

<div class="section section--small">
    <div class="section__title">
        <h1 id="modal-title"><?= _('News time filter') ?></h1>
    </div>

    <div class="section__intro">
        <p>
            <?= protect($collection->name) ?>
        </p>

        <p>
            <?= _('Choose how to filter links of the current collection in the news.') ?>
        </p>
    </div>

    <form method="post" action="<?= url('update collection filter', ['id' => $collection->id]) ?>">
        <?php if ($error): ?>
            <p class="form__error">
                <?= $error ?>
            </p>
        <?php endif; ?>

        <?php if (isset($errors['time_filter'])): ?>
            <p class="form__error">
                <?= $errors['time_filter'] ?>
            </p>
        <?php endif; ?>

        <input type="hidden" name="csrf" value="<?= $csrf_token ?>" />
        <input type="hidden" name="from" value="<?= $from ?>" />

        <div class="form-group">
            <input
                type="radio"
                id="time-filter-strict"
                name="time_filter"
                value="strict"
                <?= $time_filter === 'strict' ? 'checked' : '' ?>
                aria-describedby="time-filter-strict-caption"
            />

            <label class="label--radio" for="time-filter-strict">
                <?= _('Strict') ?>
            </label>

            <p class="form-group__caption form-group__caption--alt" id="time-filter-strict-caption">
                <?= _('You’ll receive the links published during the last 24 hours (recommended for high-traffic feeds).') ?>
            </p>
        </div>

        <div class="form-group">
            <input
                type="radio"
                id="time-filter-normal"
                name="time_filter"
                value="normal"
                <?= $time_filter === 'normal' ? 'checked' : '' ?>
                aria-describedby="time-filter-normal-caption"
            />

            <label class="label--radio" for="time-filter-normal">
                <?= _('Normal') ?>
            </label>

            <p class="form-group__caption form-group__caption--alt" id="time-filter-normal-caption">
                <?= _('You’ll receive the links published during the last 3 days (recommended for most of the feeds).') ?>
            </p>
        </div>

        <div class="form-group">
            <input
                type="radio"
                id="time-filter-all"
                name="time_filter"
                value="all"
                <?= $time_filter === 'all' ? 'checked' : '' ?>
                aria-describedby="time-filter-all-caption"
            />

            <label class="label--radio" for="time-filter-all">
                <?= _('All') ?>
            </label>

            <p class="form-group__caption form-group__caption--alt" id="time-filter-all-caption">
                <?= _('You’ll receive all the published links (recommended if you don’t want to miss anything).') ?>
            </p>
        </div>

        <div class="form__actions">
            <button type="submit" class="button--primary">
                <?= _('Save changes') ?>
            </button>
        </div>
    </form>
</div>
