<?php
    if ($pagination->isCurrentFirstPage()) {
        $current_url_params = ['id' => $topic->id];
    } else {
        $current_url_params = [
            'id' => $topic->id,
            'page' => $pagination->currentPage(),
        ];
    }

    $open_graph = [
        'title' => $topic->label,
        'description' => _f('The collections about %s, on %s.', $topic->label, $brand),
        'locale' => $current_locale,
        'url' => url_full('topic', $current_url_params),
    ];
    if ($topic->image_filename) {
        $open_graph['image'] = url_media_full('cards', $topic->image_filename);
    }

    $this->layout('base.phtml', [
        'title' => $topic->label,
        'canonical' => url_full('topic', $current_url_params),
        'current_tab' => 'collections',
        'open_graph' => $open_graph,
        'back' => [
            'href' => url('discovery'),
            'label' => _('Discover'),
        ],
    ]);
?>

<div class="section section--longbottom" data-controller="back-storage" data-back-storage-type="collection">
    <?php if ($topic->image_filename): ?>
        <img
            class="section__image"
            alt=""
            src="<?= url_media('large', $topic->image_filename) ?>"
        />
    <?php endif; ?>

    <div class="section__title">
        <h1><?= protect($topic->label) ?></h1>
    </div>

    <?php if ($collections): ?>
        <div class="cards cards--centered">
            <?php foreach ($collections as $collection): ?>
                <div class="card card--illustrated" style="background-image: url('<?= url_static('collection-card.svg') ?>');">
                    <a class="card__body" href="<?= url('collection', ['id' => $collection->id]) ?>">
                        <div class="card__title">
                            <?= protect($collection->name) ?>
                        </div>

                        <p class="card__text card__text--oneline">
                            <?php
                                if ($collection->type === 'feed'):
                                    $via = _f('Feed %s', protect($collection->feedWebsite()));
                                else:
                                    $via = _f('By %s', protect($collection->owner()->username));
                                endif;

                                if ($collection->number_links === 0):
                                    $number_links = _('no links');
                                else:
                                    $number_links = _nf('%d link', '%d links', $collection->number_links, $collection->number_links);
                                endif;
                            ?>

                            <span class="card__ellipsis"><?= $via ?></span>&nbsp;·&nbsp;<?= $number_links ?>
                        </p>
                    </a>
                </div>
            <?php endforeach; ?>
        </div>

        <?= $this->include('_pagination.phtml', ['pagination' => $pagination, 'url' => url('topic', ['id' => $topic->id])]) ?>
    <?php else: ?>
        <p class="paragraph--placeholder">
            <?= _('The community didn’t publish any collection in this topic yet. Will you be the first?') ?>
        </p>
    <?php endif; ?>
</div>
