<?php
    $this->layout('base.phtml', [
        'title' => _('Password confirmation'),
        'canonical' => url_full('security'),
        'current_page' => 'security',
        'has_errors' => $form->isInvalid(),
        'back_options' => [
            'track' => false,
        ],
    ]);
?>

<div class="section section--small section--longbottom">
    <div class="section__title">
        <h1><?= _('Password confirmation') ?></h1>
    </div>

    <p class="section__intro">
        <?= _('We need you to confirm your password before giving you access to sensitive actions.') ?>
    </p>

    <form method="post" action="<?= url('confirm password') ?>">
        <?= $this->include('alerts/_error.phtml', ['message' => $form->error('@base')]) ?>

        <div class="form-group">
            <label for="current-password">
                <?= _('Your current password') ?>
            </label>

            <?php if ($form->isInvalid('password')): ?>
                <p id="password-error" class="form-group__error">
                    <?= _('Error:') ?>
                    <?= $form->error('password') ?>
                </p>
            <?php endif; ?>

            <div class="form-group__stack" data-controller="input-password">
                <input
                    id="current-password"
                    name="password"
                    type="password"
                    required
                    data-input-password-target="input"
                    autocomplete="current-password"
                    <?php if ($form->isInvalid('password')): ?>
                        aria-errormessage="password-error"
                        aria-invalid="true"
                    <?php endif; ?>
                />

                <button
                    type="button"
                    class="no-mobile js-only"
                    data-action="input-password#toggle"
                    data-input-password-target="button"
                    aria-label="<?= _('Show password as plain text. Note: this will visually expose your password.') ?>"
                >
                    <?= icon('eye') ?>
                    <?= _('Show') ?>
                </button>
            </div>
        </div>

        <div class="form__actions">
            <button type="submit" class="button--primary">
                <?= _('Confirm your password') ?>
            </button>
        </div>

        <input type="hidden" name="redirect_to" value="<?= protect($form->redirect_to) ?>" />
        <input type="hidden" name="csrf_token" value="<?= csrf_token($form) ?>" />
    </form>
</div>
