<?php
    $this->layout('base.phtml', [
        'title' => _('Login & security'),
        'canonical' => url_full('security'),
        'current_page' => 'security',
        'has_errors' => $form->isInvalid(),
    ]);
?>

<div class="section section--small section--longbottom">
    <div class="section__title">
        <h1><?= _('Login & security') ?></h1>
    </div>

    <p class="section__intro">
        <?= _('You can change your login details here.') ?>
    </p>

    <form method="post" action="<?= url('update security') ?>">
        <?= $this->include('alerts/_error.phtml', ['message' => $form->error('@base')]) ?>

        <div class="form-group">
            <label for="email">
                <?= _('Your email address') ?>
            </label>

            <?php if ($form->isInvalid('email')): ?>
                <p id="email-error" class="form-group__error">
                    <?= _('Error:') ?>
                    <?= $form->error('email') ?>
                </p>
            <?php endif; ?>

            <input
                id="email"
                name="email"
                type="email"
                value="<?= protect($form->email) ?>"
                required
                <?php if ($form->isInvalid('email')): ?>
                    aria-errormessage="email-error"
                    aria-invalid="true"
                <?php endif; ?>
            />
        </div>

        <div class="form-group">
            <label for="new-password">
                <?= _('New password') ?>
                <span class="label__help">
                    <?= _('(optional)') ?>
                </span>
            </label>

            <?php if ($form->isInvalid('password_hash')): ?>
                <p id="password-error" class="form-group__error">
                    <?= _('Error:') ?>
                    <?= $form->error('password_hash') ?>
                </p>
            <?php endif; ?>

            <div class="form-group__stack" data-controller="input-password">
                <input
                    id="new-password"
                    name="password"
                    type="password"
                    data-input-password-target="input"
                    autocomplete="new-password"
                    aria-describedby="new-password-caption"
                    <?php if ($form->isInvalid('password_hash')): ?>
                        aria-errormessage="password-error"
                        aria-invalid="true"
                    <?php endif; ?>
                />

                <button
                    type="button"
                    class="no-mobile js-only"
                    data-action="input-password#toggle"
                    data-input-password-target="button"
                    aria-label="<?= _('Show password as plain text. Note: this will visually expose your password.') ?>"
                >
                    <?= icon('eye') ?>
                    <?= _('Show') ?>
                </button>
            </div>

            <p id="new-password-caption" class="form-group__caption">
                <?= _('Leave this field empty if you want to keep your current password.') ?>
            </p>
        </div>

        <div class="form__actions">
            <button type="submit" class="button--primary">
                <?= _('Save changes') ?>
            </button>
        </div>

        <input type="hidden" name="csrf_token" value="<?= csrf_token($form) ?>" />
    </form>
</div>
