<?php
    $this->layout('base.phtml', [
        'title' => _('Login & security'),
        'canonical' => url_full('security'),
        'current_page' => 'security',
    ]);
?>

<div class="section section--small section--longbottom">
    <div class="section__title">
        <h1><?= _('Login & security') ?></h1>
    </div>

    <p class="section__intro">
        <?= _('We need you to confirm your password before giving you access to sensitive actions.') ?>
    </p>

    <form method="post" action="<?= url('confirm password') ?>">
        <?= $this->include('alerts/_error.phtml', ['message' => $error]) ?>

        <input type="hidden" name="csrf" value="<?= $csrf_token ?>" />

        <div class="form-group <?= isset($errors['password_hash']) ? 'form-group--invalid' : '' ?>">
            <label for="current-password">
                <?= _('Your current password') ?>
            </label>

            <div class="form-group__stack" data-controller="input-password">
                <input
                    id="current-password"
                    name="password"
                    type="password"
                    required
                    data-input-password-target="input"
                    autocomplete="current-password"
                    aria-describedby="password-desc"
                />

                <button
                    type="button"
                    class="no-mobile js-only"
                    data-action="input-password#toggle"
                    data-input-password-target="button"
                    aria-label="<?= _('Show password as plain text. Note: this will visually expose your password.') ?>"
                >
                    <?= icon('eye') ?>
                    <?= _('Show') ?>
                </button>
            </div>

            <div id="password-desc">
                <?php if (isset($errors['password_hash'])): ?>
                    <p class="form-group__error">
                        <span class="sr-only"><?= _('Error') ?></span>
                        <?= $errors['password_hash'] ?>
                    </p>
                <?php endif; ?>
            </div>
        </div>

        <div class="form__actions">
            <button type="submit" class="button--primary">
                <?= _('Confirm your password') ?>
            </button>
        </div>
    </form>
</div>
