<?php $this->layout('emails/default.phtml', [
    'username' => $username,
    'logo_cid' => $logo_cid,
]) ?>

<p>
    <?= _f('Thank you for your inscription on %s. To finish, you’ll have to confirm your email address. You just have to click on the following link, and you should be all good then:', get_app_configuration('brand')) ?></br />
    <a href="<?= url_full('new account validation', ['t' => $token]) ?>">
        <?= url_full('new account validation', ['t' => $token]) ?>
    </a>
</p>
