<p>
    <?= _f('Hi %s,', $username) ?>
</p>

<p>
    <?= _f('You receive this email because you’ve asked to reset your password on %s. You just have to click on the following link and follow the instructions:', $brand) ?></br />
    <a href="<?= url_full('edit password', ['t' => $token]) ?>">
        <?= url_full('edit password', ['t' => $token]) ?>
    </a>
</p>

<p>
    <?= _('Have a nice day!') ?>
</p>

<p>
    <em><?= _('P.S. – If you didn’t ask to reset your password, please ignore this email.') ?></em>
</p>
