<?php $this->layout('emails/default.phtml', [
    'username' => $username,
    'logo_cid' => $logo_cid,
]) ?>

<p>
    <?= _f('You receive this email because you’ve asked to reset your password on %s. You just have to click on the following link and follow the instructions:', get_app_configuration('brand')) ?></br />
    <a href="<?= url_full('edit password', ['t' => $token]) ?>">
        <?= url_full('edit password', ['t' => $token]) ?>
    </a>
</p>

<p>
    <?= _('If you didn’t ask to reset your password, please ignore this email.') ?>
</p>
