<?php
    $this->layout('error.phtml', [
        'title' => _('Page not found'),
        'error' => $error,
    ]);
?>

<div class="section">
    <h1>
        <?= _('This page doesn’t exist.') ?>
    </h1>

    <?php if (isset($details)): ?>
        <p class="section__intro">
            <?= $details ?>
        </p>
    <?php endif; ?>

    <p>
        <?php if (isset($link_to)): ?>
            <a class="button button--primary" href="<?= $link_to ?>">
                <?= _('Back to the previous page') ?>
            </a>
        <?php else: ?>
            <a class="button button--primary" href="<?= url('home') ?>">
                <?= _('Back to the home page') ?>
            </a>
        <?php endif; ?>
    </p>

    <img
        class="illustration illustration--centered"
        alt=""
        src="<?= url_static('illustrations/taken.svg') ?>"
        height="250"
    />
</div>
