<?php
    $this->layout('base.phtml', [
        'title' => _('Page not found'),
    ]);
?>

<p>
    <?= _('This page doesn’t exist.') ?>
</p>

<p>
    <?php if (isset($link_to)): ?>
        <a href="<?= $link_to ?>">
            <?= _('Back to the previous page') ?>
        </a>
    <?php else: ?>
        <a href="<?= url('home') ?>">
            <?= _('Back to the home page') ?>
        </a>
    <?php endif; ?>
</p>
