<?php
    $this->layout('base.phtml', [
        'title' => _('Registration'),
        'canonical' => url_full('registration'),
        'current_page' => 'registration',
        'back_options' => [
            'reset' => true,
            'track' => false,
        ],
        'has_errors' => $form->isInvalid(),
    ]);
?>

<div class="section section--small">
    <div class="section__title">
        <h1><?= _('Registration') ?></h1>
    </div>

    <?php if (get_app_configuration('subscriptions_enabled')): ?>
        <p class="section__intro">
            <?= _f('First month is free. <a href="%s">Learn more about pricing.</a>', get_app_configuration('subscriptions_host') . '/tarifs') ?>
        </p>
    <?php endif; ?>

    <form
        method="post"
        action="<?= url('create user') ?>"
        data-controller="csrf"
        data-csrf-name-value="csrf_token"
        data-csrf-token-value="<?= csrf_token($form) ?>"
    >
        <?= $this->include('alerts/_error.phtml', ['message' => $form->error('@base')]) ?>

        <div class="form-group">
            <label for="username">
                <?= _('How should we name you?') ?>
                <span class="label__help">
                    <?= _f('(public, max. %d characters)', $form->username_max_length) ?>
                </span>
            </label>

            <?php if ($form->isInvalid('username')): ?>
                <p id="username-error" class="form-group__error">
                    <?= _('Error:') ?>
                    <?= $form->error('username') ?>
                </p>
            <?php endif; ?>

            <input
                id="username"
                name="username"
                type="text"
                value="<?= protect($form->username) ?>"
                maxlength="<?= $form->username_max_length ?>"
                required
                autofocus
                autocomplete="nickname"
                <?php if ($form->isInvalid('username')): ?>
                    aria-errormessage="username-error"
                    aria-invalid="true"
                <?php endif; ?>
            />
        </div>

        <div class="form-group">
            <label for="email">
                <?= _('Your email address') ?>
            </label>

            <?php if ($form->isInvalid('email')): ?>
                <p id="email-error" class="form-group__error">
                    <?= _('Error:') ?>
                    <?= $form->error('email') ?>
                </p>
            <?php endif; ?>

            <input
                id="email"
                name="email"
                type="email"
                value="<?= protect($form->email) ?>"
                required
                autocomplete="email"
                aria-describedby="email-caption"
                <?php if ($form->isInvalid('email')): ?>
                    aria-errormessage="email-error"
                    aria-invalid="true"
                <?php endif; ?>
            />

            <p id="email-caption" class="form-group__caption">
                <?= _('We only send emails necessary for the operation of the service, or in the event of a problem with your account.') ?>
            </p>
        </div>

        <div class="form-group">
            <label for="new-password">
                <?= _('And a password') ?>
                <span class="label__help">
                    <?= _('(recommended at least 8 characters)') ?>
                </span>
            </label>

            <?php if ($form->isInvalid('password_hash')): ?>
                <p id="password-error" class="form-group__error">
                    <?= _('Error:') ?>
                    <?= $form->error('password_hash') ?>
                </p>
            <?php endif; ?>

            <div class="form-group__stack" data-controller="input-password">
                <input
                    id="new-password"
                    name="password"
                    type="password"
                    value=""
                    required
                    data-input-password-target="input"
                    autocomplete="new-password"
                    <?php if ($form->isInvalid('password_hash')): ?>
                        aria-errormessage="password-error"
                        aria-invalid="true"
                    <?php endif; ?>
                />

                <button
                    type="button"
                    class="no-mobile js-only"
                    data-action="input-password#toggle"
                    data-input-password-target="button"
                    aria-label="<?= _('Show password as plain text. Note: this will visually expose your password.') ?>"
                >
                    <?= icon('eye') ?>
                    <?= _('Show') ?>
                </button>
            </div>
        </div>

        <div class="form-group">
            <input
                type="checkbox"
                id="accept-contact"
                name="accept_contact"
            />

            <label class="label--checkbox" for="accept-contact">
                <?= _('Accept to be contacted by email to help improve the service (optional).') ?>
            </label>
        </div>

        <?php if ($form->hasTerms()): ?>
            <div class="form-group form-group--terms">
                <?php if ($form->isInvalid('accept_terms')): ?>
                    <p id="accept-terms-error" class="form-group__error">
                        <?= _('Error:') ?>
                        <?= $form->error('accept_terms') ?>
                    </p>
                <?php endif; ?>

                <p id="accept-terms-caption" class="form-group__caption">
                    <?= _f('Before going any further, please read <a href="%s" target="_blank">the general terms and conditions of service and use</a> to make sure they are suitable for you.', url('terms')) ?>
                </p>

                <input
                    type="checkbox"
                    id="accept-terms"
                    name="accept_terms"
                    required
                    aria-describedby="accept-terms-caption"
                    <?php if ($form->isInvalid('accept_terms')): ?>
                        aria-errormessage="accept-terms-error"
                        aria-invalid="true"
                    <?php endif; ?>
                />

                <label class="label--checkbox" for="accept-terms">
                    <?= _('I acknowledge that I have read and accepted the general terms and conditions of service and use') ?>
                </label>
            </div>
        <?php endif; ?>

        <div class="form__actions">
            <button type="submit" class="button--primary">
                <?= _('Sign up') ?>
            </button>
        </div>
    </form>

    <p class="paragraph--centered">
        <a href="<?= url('login') ?>">
            <?= _('Already an account?') ?>
        </a>
    </p>
</div>
