<?php
    $this->layout('base.phtml', [
        'title' => _('Registration validation'),
    ]);
?>

<?php if (!$error): ?>
    <p>
        <?= _('Your registration is now validated.') ?>
    </p>

    <p>
        <a href="<?= url('home') ?>">
            <?= _('Back to home') ?>
        </a>
    </p>
<?php else: ?>
    <p>
        <?= $error ?>
    </p>

    <?php if ($current_user && !$current_user->validated_at): ?>
        <form method="post" action="<?= url('resend validation email') ?>">
            <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />
            <button type="submit">
                <?= _('Send an email with a valid token') ?>
            </button>
        </form>
    <?php endif; ?>
<?php endif; ?>
