<?php
    $this->layout('base.phtml', [
        'title' => _('Registration validation'),
        'banner' => false,
    ]);
?>

<div class="section">
    <div class="section__title">
        <h1><?= _('Registration validation') ?></h1>
    </div>

    <?php if (isset($success) && $success): ?>
        <p class="section__intro">
            <?= _('Your registration is now validated.') ?>
        </p>

        <p class="paragraph--centered">
            <a class="anchor--action" href="<?= url('home') ?>">
                <?= _('Nice! Go to the home page') ?>
            </a>
        </p>
    <?php else: ?>
        <p class="section__intro">
            <?= _('You must validate your registration so we can contact you in case of a change in our end-user license agreement or a problem concerning your account. <strong>You should have received an email containing a link intended to this purpose.</strong>') ?>
        </p>

        <?php if ($status === 'validation_email_sent'): ?>
            <p class="paragraph--featured">
                <?= _('We’ve just sent you an email!') ?>
            </p>

            <p class="paragraph--centered paragraph--secondary">
                <?= _('Still nothing? Did you check your spam?') ?>
            </p>
        <?php else: ?>
            <?php if ($error): ?>
                <p class="paragraph--centered form__error">
                    <?= $error ?>
                </p>
            <?php endif; ?>

            <form class="form--centered" method="post" action="<?= url('resend validation email') ?>">
                <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />
                <input type="hidden" name="from" value="<?= url('registration validation') ?>" />
                <button class="button--primary" type="submit">
                    <?= _('Didn’t receive the email? Resend it') ?>
                </button>
            </form>
        <?php endif; ?>
    <?php endif; ?>
</div>
