<?php
    $this->layout('base.phtml', [
        'title' => _('Note edition'),
        'canonical' => url_full('edit note', ['id' => $note->id]),
        'has_errors' => $error || $errors,
        'modal_enabled' => true,
    ]);
?>

<div class="section section--small">
    <div class="section__title">
        <h1 id="modal-title"><?= _('Note edition') ?></h1>
    </div>

    <form
        data-turbo-preserve-scroll
        method="post"
        action="<?= url('update note', ['id' => $note->id]) ?>"
        data-controller="autosave"
        data-action="turbo:submit-start@document->autosave#clear"
    >
        <?= $this->include('alerts/_error.phtml', ['message' => $error]) ?>

        <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />
        <input type="hidden" name="from" value="<?= $from ?>" />

        <div class="form-group <?= isset($errors['content']) ? 'form-group--invalid' : '' ?>">
            <label for="content">
                <?= _('Your note') ?>
            </label>

            <textarea
                id="content"
                name="content"
                required
                data-controller="text-editor"
                data-action="text-editor#refresh keyup->autosave#save"
                aria-describedby="content-desc"
            ><?= $content ?></textarea>

            <div id="content-desc">
                <?php if (isset($errors['content'])): ?>
                    <p class="form-group__error">
                        <span class="sr-only"><?= _('Error') ?></span>
                        <?= $errors['content'] ?>
                    </p>
                <?php endif; ?>

                <p class="form-group__caption">
                    <?= _('You can format the content in Markdown and use #tags.') ?>
                </p>
            </div>
        </div>

        <div class="form__actions">
            <button type="submit" class="button--primary">
                <?= _('Save changes') ?>
            </button>
        </div>
    </form>
</div>
