<ul class="list--collections-others list list--no-style">
    <?php foreach ($collections as $collection): ?>
        <?php $other_link = $collection->linkNotOwnedByUrl($current_user->id, $link->url_hash); ?>
        <?php $owner = $other_link->owner(); ?>
        <li class="list__item" data-link-id="<?= $other_link->id ?>">
            <img class="avatar" src="<?= url_avatar($owner->avatar_filename) ?>" alt="" />

            <?php if ($collection->user_id === $current_user->id): ?>
                <?= _f('<strong>%s</strong> added this link to <strong>%s</strong>.', protect($owner->username), protect($collection->name)) ?>
            <?php else: ?>
                <?= _f('<strong>%s</strong> added this link to <strong>%s</strong> (shared by %s).', protect($owner->username), protect($collection->name), protect($collection->owner()->username)) ?>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
</ul>
