<form
    method="post"
    action="<?= $this->safe('action') ?>"
    data-controller="autosave"
    data-action="turbo:submit-start@document->autosave#clear"
>
    <?= $this->include('alerts/_error.phtml', ['message' => $form->error('@base')]) ?>

    <div class="form-group">
        <label for="name">
            <?= _('What do you want to name this collection?') ?>
            <span class="label__help">
                <?= _f('(max. %d characters)', $form->collection_name_max_length) ?>
            </span>
        </label>

        <?php if ($form->isInvalid('name')): ?>
            <p id="name-error" class="form-group__error">
                <?= _('Error:') ?>
                <?= $form->error('name') ?>
            </p>
        <?php endif; ?>

        <input
            id="name"
            name="name"
            type="text"
            required
            value="<?= protect($form->name) ?>"
            autofocus
            maxlength="<?= $form->collection_name_max_length ?>"
            data-action="keyup->autosave#save"
            <?php if ($form->isInvalid('name')): ?>
                aria-errormessage="name-error"
                aria-invalid="true"
            <?php endif; ?>
        />
    </div>

    <div class="form-group">
        <label for="description">
            <?= _('What’s the purpose of this collection?') ?>
            <span class="label__help">
                <?= _('(optional)') ?>
            </span>
        </label>

        <?php if ($form->isInvalid('description')): ?>
            <p id="description-error" class="form-group__error">
                <?= _('Error:') ?>
                <?= $form->error('description') ?>
            </p>
        <?php endif; ?>

        <textarea
            id="description"
            name="description"
            data-controller="text-editor"
            data-action="text-editor#refresh keyup->autosave#save"
            aria-describedby="description-caption"
            <?php if ($form->isInvalid('description')): ?>
                aria-errormessage="description-error"
                aria-invalid="true"
            <?php endif; ?>
        ><?= protect($form->description) ?></textarea>

        <p id="description-caption" class="form-group__caption">
            <?= _('You can format the description in Markdown.') ?>
        </p>
    </div>

    <?php $topics = $form->topicsValues(); ?>
    <?php if ($topics): ?>
        <fieldset aria-describedby="topics-desc">
            <legend><?= _('What topics will be covered?') ?></legend>

            <?php if ($form->isInvalid('topic_ids')): ?>
                <p id="topic-ids-error" class="form-group__error">
                    <?= _('Error:') ?>
                    <?= $form->error('topic_ids') ?>
                </p>
            <?php endif; ?>

            <div class="topics-selector">
                <?php foreach ($topics as $topic): ?>
                    <div class="topics-selector__item">
                        <input
                            type="checkbox"
                            id="topic-<?= $topic->id ?>"
                            class="topics-selector__checkbox"
                            name="topic_ids[]"
                            value="<?= $topic->id ?>"
                            <?= $form->isTopicSelected($topic) ? 'checked' : '' ?>
                        />

                        <label class="topics-selector__label" for="topic-<?= $topic->id ?>">
                            <?= protect($topic->label) ?>
                        </label>
                    </div>
                <?php endforeach; ?>
            </div>
        </fieldset>
    <?php endif; ?>

    <div class="form-group">
        <input
            type="checkbox"
            id="is_public"
            name="is_public"
            <?= $form->is_public ? 'checked' : '' ?>
        />

        <label class="label--checkbox" for="is_public">
            <?= _('Show the collection publicly') ?>
        </label>
    </div>

    <div class="form__actions">
        <button type="submit" class="button--primary">
            <?= $submit_label ?>
        </button>
    </div>

    <input type="hidden" name="csrf_token" value="<?= csrf_token($form) ?>" />
</form>
