<div class="collections-selector" data-controller="collections-selector">
    <select
        id="collection-ids"
        class="collections-selector__data"
        name="collection_ids[]"
        data-collections-selector-target="data"
        multiple
        tabindex="-1"
    >
        <?php $collections = $groups_to_collections[null] ?? []; ?>
        <?php foreach ($collections as $collection): ?>
            <option
                value="<?= $collection->id ?>"
                <?= in_array($collection->id, $collection_ids) ? 'selected' : '' ?>
                <?= $collection->is_public ? 'data-public' : '' ?>
            >
                <?= protect($collection->name()) ?>
            </option>
        <?php endforeach; ?>

        <?php foreach ($groups as $group): ?>
            <?php if (isset($groups_to_collections[$group->id])): ?>
                <optgroup label="<?= protect($group->name) ?>">
                    <?php $collections = $groups_to_collections[$group->id]; ?>
                    <?php foreach ($collections as $collection): ?>
                        <option
                            value="<?= $collection->id ?>"
                            <?= in_array($collection->id, $collection_ids) ? 'selected' : '' ?>
                            <?= $collection->is_public ? 'data-public' : '' ?>
                        >
                            <?= protect($collection->name()) ?>
                        </option>
                    <?php endforeach; ?>
                </optgroup>
            <?php endif; ?>
        <?php endforeach; ?>

        <?php if ($shared_collections): ?>
            <optgroup label="<?= _('Shared with me') ?>">
                <?php foreach ($shared_collections as $collection): ?>
                    <option
                        value="<?= $collection->id ?>"
                        <?= in_array($collection->id, $collection_ids) ? 'selected' : '' ?>
                        <?= $collection->is_public ? 'data-public' : '' ?>
                    >
                        <?= protect($collection->name()) ?>
                        <?= _f('(by %s)', protect($collection->owner()->username)) ?>
                    </option>
                <?php endforeach; ?>
            </optgroup>
        <?php endif; ?>
    </select>

    <ul class="collections-selector__list" data-collections-selector-target="list"></ul>

    <select
        data-collections-selector-target="select"
        data-action="collections-selector#attach"
        aria-label="<?= _('Select a collection') ?>"
    ></select>
</div>
