<?php
    $this->layout('base.phtml', [
        'title' => _('Discover collections'),
        'current_tab' => 'collections',
        'back' => [
            'href' => url('collections'),
            'label' => _('Your collections'),
        ],
    ]);
?>

<div class="section" data-controller="back-storage" data-back-storage-type="collection">
    <div class="section__title">
        <h1><?= _('Discover collections') ?></h1>
    </div>

    <p class="section__intro">
        <?= _('Discover collections created by the community and follow the ones you are interested in.') ?>
    </p>

    <?php if ($collections): ?>
        <div class="cards cards--centered">
            <?php foreach ($collections as $collection): ?>
                <div class="card">
                    <div class="card__body">
                        <h2 class="card__title icon icon--collection">
                            <a class="anchor--hidden" href="<?= url('collection', ['id' => $collection->id]) ?>" tabindex="-1">
                                <?= $this->protect($collection->name) ?>
                            </a>
                        </h2>

                        <p class="card__ellipsis">
                            <?= _f('Created by %s', $this->protect($collection->owner()->username)) ?>
                        </p>
                    </div>

                    <div class="card__footer">
                        <p class="card__details">
                            <?php if ($collection->number_links === 0): ?>
                                <?= _('no links') ?>
                            <?php else: ?>
                                <?= _nf('%d link', '%d links', $collection->number_links, $collection->number_links) ?>
                            <?php endif; ?>

                            <?php if ($current_user->isFollowing($collection->id)): ?>
                                · <?= _('followed') ?>
                            <?php endif; ?>
                        </p>

                        <a class="anchor--action" href="<?= url('collection', ['id' => $collection->id]) ?>">
                            <?= _('see') ?>
                        </a>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    <?php else: ?>
        <p class="paragraph--placeholder">
            <?= _('The community didn’t publish any collection yet. Will you be the first?') ?>
        </p>
    <?php endif; ?>
</div>
