<?php
    $this->layout('base.phtml', [
        'title' => _('Collection edition'),
        'current_tab' => 'collections',
        'canonical' => url('edit collection', ['id' => $collection->id]),
    ]);
?>

<div class="section">
    <div class="section__title">
        <h1><?= _('Collection edition') ?></h1>
    </div>

    <form method="post" action="<?= url('update collection', ['id' => $collection->id]) ?>">
        <?php if ($error): ?>
            <p class="form__error">
                <?= $error ?>
            </p>
        <?php endif; ?>

        <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />

        <div class="form-group <?= isset($errors['name']) ? 'form-group--invalid' : '' ?>">
            <label for="name">
                <?= _('Name') ?>
            </label>

            <input
                id="name"
                name="name"
                type="text"
                required
                value="<?= $name ?>"
            />

            <?php if (isset($errors['name'])): ?>
                <p class="form-group__error">
                    <?= $errors['name'] ?>
                </p>
            <?php endif; ?>
        </div>

        <div class="form-group">
            <label>
                <input
                    type="checkbox"
                    name="is_public"
                    <?= $is_public ? 'checked' : '' ?>
                />
                <?= _('Public collection') ?>
            </label>
        </div>

        <div class="form-group <?= isset($errors['description']) ? 'form-group--invalid' : '' ?>">
            <label for="description">
                <?= _('Description') ?>
                <span class="text--secondary">
                    <?= _('(optional)') ?>
                </span>
            </label>

            <textarea
                id="description"
                name="description"
            ><?= $description ?></textarea>

            <?php if (isset($errors['description'])): ?>
                <p class="form-group__error">
                    <?= $errors['description'] ?>
                </p>
            <?php endif; ?>
        </div>

        <div class="form__actions">
            <button type="submit" class="button--primary">
                <?= _('Update') ?>
            </button>

            <a href="<?= url('collection', ['id' => $collection->id]) ?>">
                <?= _('Cancel and go back to the collection') ?>
            </a>
        </div>
    </form>
</div>

<hr />

<div class="section">
    <form
        method="post"
        action="<?= url('delete collection', ['id' => $collection->id]) ?>"
        data-controller="confirmation"
        data-action="confirmation#confirm"
        data-message="<?= _('Are you sure that you want to delete this collection? You may lose the links that are attached only to this collection.') ?>"
    >
        <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />
        <input type="hidden" name="from" value="<?= url('edit collection', ['id' => $collection->id]) ?>" />

        <div class="form__actions form__actions--centered">
            <button type="submit">
                <?= _('Delete the collection') ?>
            </button>
        </div>
    </form>
</div>
