<?php
    $this->layout('base.phtml', [
        'title' => _('Collection edition'),
        'current_tab' => 'collections',
        'canonical' => url('edit collection', ['id' => $collection->id]),
        'has_errors' => $form->isInvalid(),
        'modal_enabled' => true,
    ]);
?>

<div class="section">
    <div class="section__title">
        <h1 id="modal-title"><?= _('Collection edition') ?></h1>
    </div>

    <?= $this->include('collections/_form.phtml', [
        'form' => $form,
        'action' => url('update collection', ['id' => $collection->id]),
        'submit_label' => _('Save changes'),
    ]) ?>
</div>
