<?php
    $this->layout('base.phtml', [
        'title' => _('Collections'),
        'canonical' => url_full('collections'),
        'current_tab' => 'collections',
        'current_page' => 'collections',
    ]);
?>

<div class="section">
    <div class="section__title">
        <h1><?= _('Collections') ?></h1>
    </div>

    <div class="section__intro">
        <p>
            <?= _('Collections allow to group links by topics and to find them easily.') ?>
        </p>

        <p>
            <?= _f('<a href="%s">Discover more collections</a>', url('discovery')) ?>
        </p>
    </div>

    <section class="group">
        <div class="cards">
            <div class="card card--action">
                <button
                    class="card__button card__button--collection"
                    data-controller="modal-opener"
                    data-action="modal-opener#fetch"
                    data-modal-opener-href-value="<?= url('new collection') ?>"
                    aria-haspopup="dialog"
                    aria-controls="modal"
                >
                    <?= icon('plus') ?><br />
                    <?= _('Create a collection') ?>
                </button>
            </div>

            <?php $collections = $groups_to_collections[null] ?? []; ?>

            <?php foreach ($collections as $collection): ?>
                <?= $this->include('collections/_collection.phtml', [
                    'display_mode' => 'owned',
                    'collection' => $collection,
                ]) ?>
            <?php endforeach; ?>

            <div class="card card--illustrated card--illustrated-alt" style="background-image: url('<?= url_static('read-card.png') ?>');">
                <a class="card__body" href="<?= url('read list') ?>">
                    <div class="card__title">
                        <?= protect($read_list->name()) ?>
                    </div>

                    <p class="card__text">
                        <?= _('All your links marked as read') ?>
                    </p>
                </a>
            </div>

            <?php for ($i = 0; $i < (3 - ((count($collections) + 2) % 3)); $i++): ?>
                <div class="card card--shadow no-mobile"></div>
            <?php endfor; ?>
        </div>

        <?php $collections = $groups_to_followed_collections[null] ?? []; ?>

        <?php if ($collections): ?>
            <h2 class="group__subtitle">
                <?= _('Followed collections') ?>
            </h2>

            <div class="cards">
                <?php foreach ($collections as $collection): ?>
                    <?= $this->include('collections/_collection.phtml', [
                        'display_mode' => 'public',
                        'collection' => $collection,
                    ]) ?>
                <?php endforeach; ?>

                <?php for ($i = 0; $i < (3 - (count($collections) % 3)); $i++): ?>
                    <div class="card card--shadow no-mobile"></div>
                <?php endfor; ?>
            </div>
        <?php endif; ?>
    </section>

    <?php foreach ($groups as $group): ?>
        <?= $this->include('groups/_group_deprecated.phtml', [
            'group' => $group,
            'collections' => $groups_to_collections[$group->id] ?? [],
            'followed_collections' => $groups_to_followed_collections[$group->id] ?? [],
            'from' => url('collections'),
        ]) ?>
    <?php endforeach; ?>

    <img
        class="illustration illustration--centered"
        alt=""
        src="<?= url_static('illustrations/my_collections.svg') ?>"
        height="250"
    />
</div>
