<?php
    $this->layout('base.phtml', [
        'title' => _('Collections'),
        'current_tab' => 'collections',
        'current_page' => 'collections',
    ]);
?>

<div class="section" data-controller="back-storage" data-back-storage-type="collection">
    <div class="section__title">
        <h1><?= _('Collections') ?></h1>
    </div>

    <p class="section__intro">
        <?= _('Collections allow to group links by topics, find them later and share them with the community.') ?>
    </p>

    <div class="cards">
        <div class="card card--action">
            <button
                class="card__button card__button--collection"
                data-controller="modal-opener"
                data-action="modal-opener#fetch"
                data-modal-opener-href="<?= url('new collection') ?>"
                aria-haspopup="dialog"
                aria-controls="modal"
            >
                <i class="icon icon--only icon--plus"></i><br />
                <?= _('Create a collection') ?>
            </button>
        </div>

        <?php foreach ($collections as $collection): ?>
            <div class="card">
                <div class="card__body">
                    <h2 class="card__title">
                        <a class="anchor--hidden" href="<?= url('collection', ['id' => $collection->id]) ?>" tabindex="-1">
                            <?= protect($collection->name) ?>
                        </a>
                    </h2>

                    <p class="card__text">
                        <?php if ($collection->number_links === 0): ?>
                            <?= _('no links') ?>
                        <?php else: ?>
                            <?= _nf('%d link', '%d links', $collection->number_links, $collection->number_links) ?>
                        <?php endif; ?>

                        <?php if ($collection->is_public): ?>
                            <span class="sticker sticker--right">
                                <?= _('public') ?>
                            </span>
                        <?php endif; ?>
                    </p>
                </div>

                <div class="card__footer">
                    <div></div>

                    <a class="anchor--action" href="<?= url('collection', ['id' => $collection->id]) ?>">
                        <?= _('see') ?>
                    </a>
                </div>
            </div>
        <?php endforeach; ?>

        <?php for ($i = 0; $i < (3 - ((count($collections) + 1) % 3)); $i++): ?>
            <div class="card card--shadow no-mobile"></div>
        <?php endfor; ?>
    </div>

    <div class="section__title">
        <h2><?= _('Followed collections') ?></h2>
    </div>

    <?php if ($followed_collections): ?>
        <p class="paragraph--centered">
            <a href="<?= url('discover collections') ?>">
                <?= _('Discover more collections') ?>
            </a>
        </p>

        <div class="cards">
            <?php foreach ($followed_collections as $collection): ?>
                <div class="card">
                    <div class="card__body">
                        <h2 class="card__title">
                            <a class="anchor--hidden" href="<?= url('collection', ['id' => $collection->id]) ?>" tabindex="-1">
                                <?= protect($collection->name) ?>
                            </a>
                        </h2>

                        <?php if ($collection->type === 'feed'): ?>
                            <p class="card__text">
                                <?= _f('Feed from %s', protect($collection->feedWebsite())) ?>
                            </p>
                        <?php elseif ($collection->type === 'collection'): ?>
                            <p class="card__text">
                                <?= _f('Created by %s', protect($collection->owner()->username)) ?>
                            </p>
                        <?php endif; ?>

                        <p class="card__text">
                            <?php if ($collection->number_links === 0): ?>
                                <?= _('no links') ?>
                            <?php else: ?>
                                <?= _nf('%d link', '%d links', $collection->number_links, $collection->number_links) ?>
                            <?php endif; ?>
                        </p>
                    </div>

                    <div class="card__footer">
                        <div></div>

                        <a class="anchor--action" href="<?= url('collection', ['id' => $collection->id]) ?>">
                            <?= _('see') ?>
                        </a>
                    </div>
                </div>
            <?php endforeach; ?>

            <?php for ($i = 0; $i < (3 - (count($followed_collections) % 3)); $i++): ?>
                <div class="card card--shadow no-mobile"></div>
            <?php endfor; ?>
        </div>
    <?php else: ?>
        <p class="paragraph--placeholder">
            <?= _('You don’t follow any collection. Start by discovering collections created by the community.') ?>
        </p>

        <p class="paragraph--centered">
            <a class="anchor--action" href="<?= url('discover collections') ?>">
                <?= _('Discover collections') ?>
            </a>
        </p>
    <?php endif; ?>

    <img
        class="illustration illustration--centered"
        alt=""
        src="<?= url_static('illustrations/my_collections.svg') ?>"
        height="250"
    />
</div>
