<?php
    $this->layout('base.phtml', [
        'title' => _('Collections'),
        'current_tab' => 'collections',
        'current_page' => 'collections',
    ]);
?>

<div class="section" data-controller="back-storage" data-back-storage-type="collection">
    <div class="section__title">
        <h1><?= _('Collections') ?></h1>
    </div>

    <p class="section__intro">
        <?= _('Collections allow to group links by topics, find them later and share them with the community.') ?>
    </p>

    <div class="cards">
        <div class="card card--action">
            <button
                class="card__button card__button--collection"
                data-controller="modal-opener"
                data-action="modal-opener#fetch"
                data-modal-opener-href="<?= url('new collection') ?>"
                aria-haspopup="dialog"
                aria-controls="modal"
            >
                <?= icon('plus') ?><br />
                <?= _('Create a collection') ?>
            </button>
        </div>

        <?php foreach ($no_group_collections as $collection): ?>
            <div class="card">
                <div class="card__body">
                    <h2 class="card__title">
                        <a class="anchor--hidden" href="<?= url('collection', ['id' => $collection->id]) ?>" tabindex="-1">
                            <?= protect($collection->name) ?>
                        </a>
                    </h2>

                    <p class="card__text">
                        <?php if ($collection->number_links === 0): ?>
                            <?= _('no links') ?>
                        <?php else: ?>
                            <?= _nf('%d link', '%d links', $collection->number_links, $collection->number_links) ?>
                        <?php endif; ?>

                        <?php if ($collection->is_public): ?>
                            <span class="sticker sticker--right">
                                <?= _('public') ?>
                            </span>
                        <?php endif; ?>
                    </p>
                </div>

                <div class="card__footer">
                    <div></div>

                    <a class="anchor--action" href="<?= url('collection', ['id' => $collection->id]) ?>">
                        <?= _('see') ?>
                    </a>
                </div>
            </div>
        <?php endforeach; ?>

        <?php for ($i = 0; $i < (3 - ((count($no_group_collections) + 1) % 3)); $i++): ?>
            <div class="card card--shadow no-mobile"></div>
        <?php endfor; ?>
    </div>

    <div class="cards">
        <?php foreach ($no_group_followed_collections as $collection): ?>
            <div class="card">
                <div class="card__body">
                    <h2 class="card__title">
                        <a class="anchor--hidden" href="<?= url('collection', ['id' => $collection->id]) ?>" tabindex="-1">
                            <?= protect($collection->name) ?>
                        </a>
                    </h2>

                    <?php if ($collection->type === 'feed'): ?>
                        <p class="card__text">
                            <?= _f('Feed from %s', protect($collection->feedWebsite())) ?>
                        </p>
                    <?php elseif ($collection->type === 'collection'): ?>
                        <p class="card__text">
                            <?= _f('Created by %s', protect($collection->owner()->username)) ?>
                        </p>
                    <?php endif; ?>

                    <p class="card__text">
                        <?php if ($collection->number_links === 0): ?>
                            <?= _('no links') ?>
                        <?php else: ?>
                            <?= _nf('%d link', '%d links', $collection->number_links, $collection->number_links) ?>
                        <?php endif; ?>
                    </p>
                </div>

                <div class="card__footer">
                    <div></div>

                    <a class="anchor--action" href="<?= url('collection', ['id' => $collection->id]) ?>">
                        <?= _('see') ?>
                    </a>
                </div>
            </div>
        <?php endforeach; ?>

        <?php for ($i = 0; $i < (3 - (count($no_group_followed_collections) % 3)); $i++): ?>
            <div class="card card--shadow no-mobile"></div>
        <?php endfor; ?>
    </div>

    <?php foreach ($groups as $group): ?>
        <section class="group">
            <header class="group__header">
                <div class="group__icon">
                    <?= icon('directory') ?>
                </div>

                <h2 class="group__title">
                    <?= protect($group->name) ?>
                </h2>

                <div class="group__separator"></div>

                <button
                    class="button--small button--ghost no-mobile"
                    type="button"
                    data-controller="modal-opener"
                    data-action="modal-opener#fetch"
                    data-modal-opener-href="<?= url('edit group', ['id' => $group->id, 'from' => url('collections')]) ?>"
                    aria-haspopup="dialog"
                    aria-controls="modal"
                >
                    <?= icon('pencil') ?>
                    <?= _('Edit') ?>
                </button>

                <button
                    class="button--smaller button--ghost only-mobile"
                    type="button"
                    data-controller="modal-opener"
                    data-action="modal-opener#fetch"
                    data-modal-opener-href="<?= url('edit group', ['id' => $group->id, 'from' => url('collections')]) ?>"
                    aria-haspopup="dialog"
                    aria-controls="modal"
                >
                    <?= icon('pencil') ?>
                    <span class="sr-only">
                        <?= _('Edit') ?>
                    </span>
                </button>
            </header>

            <?php $collections = $group->collections(); ?>
            <?php if ($collections): ?>
                <div class="cards">
                    <?php foreach ($collections as $collection): ?>
                        <div class="card">
                            <div class="card__body">
                                <h3 class="card__title">
                                    <a class="anchor--hidden" href="<?= url('collection', ['id' => $collection->id]) ?>" tabindex="-1">
                                        <?= protect($collection->name) ?>
                                    </a>
                                </h3>

                                <p class="card__text">
                                    <?php if ($collection->number_links === 0): ?>
                                        <?= _('no links') ?>
                                    <?php else: ?>
                                        <?= _nf('%d link', '%d links', $collection->number_links, $collection->number_links) ?>
                                    <?php endif; ?>

                                    <?php if ($collection->is_public): ?>
                                        <span class="sticker sticker--right">
                                            <?= _('public') ?>
                                        </span>
                                    <?php endif; ?>
                                </p>
                            </div>

                            <div class="card__footer">
                                <div></div>

                                <a class="anchor--action" href="<?= url('collection', ['id' => $collection->id]) ?>">
                                    <?= _('see') ?>
                                </a>
                            </div>
                        </div>
                    <?php endforeach; ?>

                    <?php for ($i = 0; $i < (3 - (count($collections) % 3)); $i++): ?>
                        <div class="card card--shadow no-mobile"></div>
                    <?php endfor; ?>
                </div>
            <?php endif; ?>

            <?php $followed_collections = $group->followedCollections(); ?>
            <?php if ($followed_collections): ?>
                <div class="cards">
                    <?php foreach ($followed_collections as $collection): ?>
                        <div class="card">
                            <div class="card__body">
                                <h3 class="card__title">
                                    <a class="anchor--hidden" href="<?= url('collection', ['id' => $collection->id]) ?>" tabindex="-1">
                                        <?= protect($collection->name) ?>
                                    </a>
                                </h3>

                                <?php if ($collection->type === 'feed'): ?>
                                    <p class="card__text">
                                        <?= _f('Feed from %s', protect($collection->feedWebsite())) ?>
                                    </p>
                                <?php elseif ($collection->type === 'collection'): ?>
                                    <p class="card__text">
                                        <?= _f('Created by %s', protect($collection->owner()->username)) ?>
                                    </p>
                                <?php endif; ?>

                                <p class="card__text">
                                    <?php if ($collection->number_links === 0): ?>
                                        <?= _('no links') ?>
                                    <?php else: ?>
                                        <?= _nf('%d link', '%d links', $collection->number_links, $collection->number_links) ?>
                                    <?php endif; ?>
                                </p>
                            </div>

                            <div class="card__footer">
                                <div></div>

                                <a class="anchor--action" href="<?= url('collection', ['id' => $collection->id]) ?>">
                                    <?= _('see') ?>
                                </a>
                            </div>
                        </div>
                    <?php endforeach; ?>

                    <?php for ($i = 0; $i < (3 - (count($followed_collections) % 3)); $i++): ?>
                        <div class="card card--shadow no-mobile"></div>
                    <?php endfor; ?>
                </div>
            <?php endif; ?>
        </section>
    <?php endforeach; ?>

    <img
        class="illustration illustration--centered"
        alt=""
        src="<?= url_static('illustrations/my_collections.svg') ?>"
        height="250"
    />
</div>
