<?php
    $this->layout('base.phtml', [
        'title' => _('New collection'),
        'canonical' => url_full('new collection'),
        'current_tab' => 'collections',
        'has_errors' => $form->isInvalid(),
        'modal_enabled' => true,
    ]);
?>

<div class="section">
    <div class="section__title">
        <h1 id="modal-title"><?= _('New collection') ?></h1>
    </div>

    <?= $this->include('collections/_form.phtml', [
        'form' => $form,
        'action' => url('create collection'),
        'submit_label' => _('Create the collection'),
    ]) ?>
</div>
