<?php
    $current_tab = 'collections';
    if ($collection->type === 'feed') {
        $feed = [
            'url' => $collection->feed_url,
            'title' => _f('Syndication feed of %s', $collection->name),
        ];

        if ($beta_enabled) {
            $current_tab = 'feeds';
        }
    } else {
        $feed = [
            'url' => url_full('collection feed', ['id' => $collection->id]),
            'title' => _f('Syndication feed of %s', $collection->name),
        ];

        if ($beta_enabled) {
            $current_tab = 'links';
        }
    }

    if ($pagination->isCurrentFirstPage()) {
        $current_url_params = ['id' => $collection->id];
    } else {
        $current_url_params = [
            'id' => $collection->id,
            'page' => $pagination->currentPage(),
        ];
    }

    $this->layout('base.phtml', [
        'title' => $collection->name,
        'canonical' => url_full('collection', $current_url_params),
        'current_tab' => $current_tab,
        'feed' => $feed,
        'back' => [
            'href' => url('collections'),
            'label' => _('Back'),
            'js-back-anchor-type' => 'collection',
            'js-back-anchor-mode' => 'hide-if-none',
        ],
    ]);
?>

<div class="section" data-controller="back-storage" data-back-storage-type-value="link,profile">
    <?php if ($collection->image_filename): ?>
        <img
            class="section__image"
            alt=""
            src="<?= url_media('large', $collection->image_filename) ?>"
        />
    <?php endif; ?>

    <div class="section__title">
        <h1><?= protect($collection->name) ?></h1>
    </div>

    <?php if ($topics): ?>
        <p class="collection__topics">
            <?= implode('&nbsp;·&nbsp;', array_column($topics, 'label')) ?>
        </p>
    <?php endif; ?>

    <div class="collection__meta">
        <div class="collection__details">
            <p class="collection__owner">
                <?php if ($collection->is_public): ?>
                    <span class="collection__public sticker">
                        <?= _('public') ?>
                    </span>
                <?php endif; ?>

                <?php if ($beta_enabled): ?>
                    <?= _f('created by <a href="%s">you</a>', url('profile', ['id' => $current_user->id])) ?>
                <?php else: ?>
                    <?= _f('created by you') ?>
                <?php endif; ?>
            </p>
        </div>

        <div class="collection__actions">
            <details
                class="popup"
                data-controller="popup"
                data-action="click@window->popup#close"
            >
                <summary class="popup__opener" title="<?= _('Open the menu') ?>" tabindex="-1">
                    <button class="button--small" type="button" data-action="popup#toggle">
                        <?= icon('menu') ?>
                        <?= _('Actions') ?>
                    </button>
                </summary>

                <nav class="popup__container popup__container--left">
                    <button
                        class="popup__item popup__item--button"
                        data-controller="modal-opener"
                        data-action="modal-opener#fetch"
                        data-modal-opener-href-value="<?= url('edit collection', ['id' => $collection->id, 'from' => url('collection', $current_url_params)]) ?>"
                        aria-haspopup="dialog"
                        aria-controls="modal"
                    >
                        <?= icon('pencil') ?>
                        <?= _('Edit') ?>
                    </button>

                    <button
                        class="popup__item popup__item--button"
                        data-controller="modal-opener"
                        data-action="modal-opener#fetch"
                        data-modal-opener-href-value="<?= url('edit group collection', ['id' => $collection->id, 'from' => url('collection', $current_url_params)]) ?>"
                        aria-haspopup="dialog"
                        aria-controls="modal"
                    >
                        <?= icon('directory') ?>
                        <?= _('Put in a group') ?>
                    </button>

                    <button
                        class="popup__item popup__item--button"
                        data-controller="modal-opener"
                        data-action="modal-opener#fetch"
                        data-modal-opener-href-value="<?= url('edit image collection', ['id' => $collection->id, 'from' => url('collection', $current_url_params)]) ?>"
                        aria-haspopup="dialog"
                        aria-controls="modal"
                    >
                        <?= icon('image') ?>
                        <?= _('Change the illustration') ?>
                    </button>

                    <?php if ($collection->is_public): ?>
                        <div data-controller="copy-to-clipboard">
                            <input type="hidden" value="<?= url_full('collection', ['id' => $collection->id]) ?>" data-copy-to-clipboard-target="copyable" />

                            <button
                                class="popup__item popup__item--button share__button"
                                data-action="copy-to-clipboard#copy"
                                data-copy-to-clipboard-target="feedback"
                            >
                                <?= icon('copy-to-clipboard') ?>
                                <?= _('Copy the link') ?>
                            </button>
                        </div>
                    <?php endif; ?>
                </nav>
            </details>
        </div>
    </div>

    <?php if ($collection->description): ?>
        <p class="collection__description">
            <?= nl2br(protect($collection->description)) ?>
        </p>
    <?php endif; ?>

    <div class="cards">
        <div class="card card--action">
            <button
                class="card__button card__button--link"
                data-controller="modal-opener"
                data-action="modal-opener#fetch"
                data-modal-opener-href-value="<?= url('new link', ['collection_id' => $collection->id, 'from' => url('collection', $current_url_params)]) ?>"
                aria-haspopup="dialog"
                aria-controls="modal"
            >
                <?= icon('plus-circle') ?><br />
                <?= _('Add a link') ?>
            </button>
        </div>

        <?php foreach ($links as $link): ?>
            <?php $has_read_url = $link->hasUserReadUrl($current_user->id); ?>
            <div class="card">
                <a
                    class="anchor--hidden"
                    target="_blank"
                    rel="noopener noreferrer"
                    tabindex="-1"
                    href="<?= protect($link->url) ?>"
                >
                    <img class="card__image" alt="" src="<?= url_media('cards', $link->image_filename) ?>" loading="lazy" />
                </a>

                <time class="card__image-overlay" datetime="<?= _d($link->published_at, '%Y-%m-%d') ?>">
                    <?php if ($now->format('Y') === $link->published_at->format('Y')): ?>
                        <?= _d($link->published_at, '%d %b') ?>
                    <?php else: ?>
                        <?= _d($link->published_at, '%d %b %Y') ?>
                    <?php endif; ?>
                </time>

                <div class="card__body">
                    <h2 class="card__title">
                        <a
                            class="anchor--hidden"
                            target="_blank"
                            rel="noopener noreferrer"
                            tabindex="-1"
                            href="<?= protect($link->url) ?>"
                        >
                            <?= protect($link->title) ?>
                        </a>
                    </h2>

                    <p class="card__text card__text--oneline">
                        <?php if (!$link->fetched_at): ?>
                            <span class="icon--spin">
                                <?= icon('sync') ?>
                                <?= _('ongoing synchronisation…') ?>
                            </span>
                        <?php else: ?>
                            <span class="card__ellipsis"><?= protect($link->host()) ?></span>&nbsp;·&nbsp;<?= format_reading_time($link->reading_time) ?>
                        <?php endif; ?>

                        <?php if ($has_read_url): ?>
                            &nbsp;<span title="<?= _('You read this link.') ?>" aria-label="<?= _('You read this link.') ?>"><?= icon('check') ?></span>
                        <?php endif; ?>
                    </p>

                    <p class="card__text">
                        <a href="<?= url('link', ['id' => $link->id]) ?>">
                            <?= icon('comment') ?>
                            <?= _nf('%d comment', '%d comments', $link->number_comments, $link->number_comments) ?>
                        </a>

                        <?php if ($collection->is_public && $link->is_hidden): ?>
                            <span class="sticker sticker--right">
                                <?= _('hidden') ?>
                            </span>
                        <?php endif; ?>
                    </p>
                </div>

                <div class="card__footer">
                    <div class="card__footer-group">
                        <details
                            class="popup"
                            data-controller="popup"
                            data-action="click@window->popup#close"
                        >
                            <summary class="popup__opener" title="<?= _('Open the menu') ?>" tabindex="-1">
                                <button class="button--ghost button--smaller" type="button" data-action="popup#toggle">
                                    <?= icon('menu') ?>
                                    <span class="sr-only">
                                        <?= _('Open the menu') ?>
                                    </span>
                                </button>
                            </summary>

                            <nav class="popup__container popup__container--over">
                                <button
                                    class="popup__item popup__item--button"
                                    data-controller="modal-opener"
                                    data-action="modal-opener#fetch"
                                    data-modal-opener-href-value="<?= url('edit link', ['id' => $link->id, 'from' => url('collection', $current_url_params)]) ?>"
                                    aria-haspopup="dialog"
                                    aria-controls="modal"
                                >
                                    <?= icon('pencil') ?>
                                    <?= _('Edit') ?>
                                </button>

                                <div data-controller="copy-to-clipboard">
                                    <input type="hidden" value="<?= protect($link->url) ?>" data-copy-to-clipboard-target="copyable" />

                                    <button
                                        class="popup__item popup__item--button share__button"
                                        data-action="copy-to-clipboard#copy"
                                        data-copy-to-clipboard-target="feedback"
                                    >
                                        <?= icon('copy-to-clipboard') ?>
                                        <?= _('Copy the external link') ?>
                                    </button>
                                </div>

                                <?php if (!$has_read_url): ?>
                                    <form method="post" action="<?= url('mark link as read', ['id' => $link->id, 'from' => url('collection', $current_url_params)]) ?>">
                                        <input type="hidden" name="csrf" value="<?= $csrf_token ?>" />

                                        <button class="popup__item popup__item--button">
                                            <?= icon('check') ?>
                                            <?= _('Mark as read') ?>
                                        </button>
                                    </form>
                                <?php endif; ?>
                            </nav>
                        </details>

                        <button
                            class="button--ghost button--smaller"
                            data-controller="modal-opener"
                            data-action="modal-opener#fetch"
                            data-modal-opener-href-value="<?= url('link collections', ['id' => $link->id, 'from' => url('collection', $current_url_params)]) ?>"
                            aria-haspopup="dialog"
                            aria-controls="modal"
                            title="<?= _('Manage collections') ?>"
                        >
                            <?= icon('collection') ?>
                            <span class="sr-only">
                                <?= _('Manage collections') ?>
                            </span>
                        </button>
                    </div>

                    <a
                        class="anchor--action"
                        target="_blank"
                        rel="noopener noreferrer"
                        href="<?= protect($link->url) ?>"
                    >
                        <?= icon('pop-out') ?>
                        <?= _('read') ?>
                    </a>
                </div>
            </div>
        <?php endforeach; ?>

        <?php for ($i = 0; $i < (3 - ((count($links) + 1) % 3)); $i++): ?>
            <div class="card card--shadow no-mobile"></div>
        <?php endfor; ?>
    </div>

    <?= $this->include('_pagination.phtml', ['pagination' => $pagination, 'url' => url('collection', ['id' => $collection->id])]) ?>
</div>
