<?php
    $owner = $collection->owner();

    if ($collection->type === 'feed') {
        $open_graph = [
            'title' => $collection->name,
            'description' => _f('A feed from %s, on %s.', protect($collection->feedWebsite()), $brand),
            'locale' => $owner->locale,
            'url' => url_full('collection', ['id' => $collection->id]),
        ];

        $feed = [
            'url' => $collection->feed_url,
            'title' => _f('Syndication feed of %s', $collection->name),
        ];
    } else {
        $open_graph = [
            'title' => $collection->name,
            'description' => _f('A collection created by %s on %s.', $owner->username, $brand),
            'locale' => $owner->locale,
            'url' => url_full('collection', ['id' => $collection->id]),
        ];

        $feed = [
            'url' => url_full('collection feed', ['id' => $collection->id]),
            'title' => _f('Syndication feed of %s', $collection->name),
        ];
    }

    if ($pagination->isCurrentFirstPage()) {
        $current_url_params = ['id' => $collection->id];
    } else {
        $current_url_params = [
            'id' => $collection->id,
            'page' => $pagination->currentPage(),
        ];
    }

    $this->layout('base.phtml', [
        'title' => $collection->name,
        'canonical' => url_full('collection', $current_url_params),
        'current_tab' => 'collections',
        'feed' => $feed,
        'open_graph' => $open_graph,
        'back' => [
            'href' => url('home'),
            'label' => _('Back'),
            'js-back-anchor-type' => 'collection',
            'js-back-anchor-mode' => 'hide-if-none',
        ],
    ]);
?>

<div class="section" data-controller="back-storage" data-back-storage-type="link">
    <div class="section__title">
        <h1><?= protect($collection->name) ?></h1>
    </div>

    <?php if ($error): ?>
        <p class="form__error">
            <?= $error ?>
        </p>
    <?php endif; ?>

    <?php if ($topics): ?>
        <p class="collection__topics">
            <?= implode('&nbsp;·&nbsp;', array_column($topics, 'label')) ?>
        </p>
    <?php endif; ?>

    <div class="collection__meta">
        <?php if ($collection->type === 'feed'): ?>
            <div class="collection__details">
                <p class="collection__feed">
                    <?= icon('feed') ?>
                    <?php if ($collection->feed_site_url): ?>
                        <?= _f('Feed from <a target="_blank" rel="noopener noreferrer" href="%s">%s</a>', protect($collection->feed_site_url), protect($collection->feedWebsite())) ?>
                    <?php else: ?>
                        <?= _f('Feed from <a target="_blank" rel="noopener noreferrer" href="%s">%s</a>', protect($collection->feed_url), protect($collection->feedWebsite())) ?>
                    <?php endif; ?>
                </p>
            </div>
        <?php else: ?>
            <div class="collection__details">
                <p class="collection__owner">
                    <?= _f('Created by %s', protect($owner->username)) ?>
                </p>
            </div>
        <?php endif; ?>

        <div class="collection__actions">
            <?php if ($current_user): ?>
                <?php if ($current_user->isFollowing($collection->id)): ?>
                    <details
                        class="popup"
                        data-controller="popup"
                        data-action="click@window->popup#close"
                    >
                        <summary class="popup__opener" title="<?= _('Open the menu') ?>" tabindex="-1">
                            <button class="button--small" type="button" data-action="popup#toggle">
                                <?= icon('menu') ?>
                                <?= _('Actions') ?>
                            </button>
                        </summary>

                        <nav class="popup__container popup__container--left">
                            <button
                                class="popup__item popup__item--button"
                                data-controller="modal-opener"
                                data-action="modal-opener#fetch"
                                data-modal-opener-href="<?= url('edit group collection', ['id' => $collection->id, 'from' => url('collection', $current_url_params)]) ?>"
                                aria-haspopup="dialog"
                                aria-controls="modal"
                            >
                                <?= icon('directory') ?>
                                <?= _('Put in a group') ?>
                            </button>

                            <form method="post" action="<?= url('unfollow collection', ['id' => $collection->id]) ?>">
                                <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />
                                <input type="hidden" name="from" value="<?= url('collection', $current_url_params) ?>" />

                                <button class="popup__item popup__item--button">
                                    <?= icon('eye-hide') ?>
                                    <?= _('Unfollow') ?>
                                </button>
                            </form>
                        </nav>
                    </details>
                <?php else: ?>
                    <form method="post" action="<?= url('follow collection', ['id' => $collection->id]) ?>">
                        <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />
                        <input type="hidden" name="from" value="<?= url('collection', $current_url_params) ?>" />
                        <button class="button--small">
                            <?= icon('eye') ?>
                            <?= _('Follow') ?>
                        </button>
                    </form>
                <?php endif; ?>
            <?php else: ?>
                <button
                    class="button--small"
                    data-controller="modal-opener"
                    data-action="modal-opener#fetch"
                    data-modal-opener-href="<?= url('login to follow collection', ['id' => $collection->id]) ?>"
                    aria-haspopup="dialog"
                    aria-controls="modal"
                >
                    <?= icon('eye') ?>
                    <?= _('Follow') ?>
                </button>
            <?php endif; ?>
        </div>
    </div>

    <p class="collection__description">
        <?= nl2br(protect($collection->description)) ?>
    </p>

    <?php if ($links): ?>
        <div class="cards cards--centered">
            <?php foreach ($links as $link): ?>
                <div class="card">
                    <a
                        class="anchor--hidden"
                        target="_blank"
                        rel="noopener noreferrer"
                        tabindex="-1"
                        href="<?= protect($link->url) ?>"
                    >
                        <img class="card__image" alt="" src="<?= url_media('cards', $link->image_filename) ?>" />
                    </a>

                    <time class="card__image-overlay" datetime="<?= format_date($link->created_at, '%Y-%m-%d') ?>">
                        <?php if ($now->format('Y') === $link->created_at->format('Y')): ?>
                            <?= format_date($link->created_at, '%d %b') ?>
                        <?php else: ?>
                            <?= format_date($link->created_at, '%d %b %Y') ?>
                        <?php endif; ?>
                    </time>

                    <div class="card__body">
                        <h2 class="card__title">
                            <a
                                class="anchor--hidden"
                                target="_blank"
                                rel="noopener noreferrer"
                                tabindex="-1"
                                href="<?= protect($link->url) ?>"
                            >
                                <?= protect($link->title) ?>
                            </a>
                        </h2>

                        <p class="card__text card__text--oneline">
                            <span class="card__ellipsis"><?= protect($link->host()) ?></span>&nbsp;·&nbsp;<?= format_reading_time($link->reading_time) ?>
                        </p>

                        <?php if ($collection->type !== 'feed'): ?>
                            <p class="card__text">
                                <a href="<?= url('link', ['id' => $link->id]) ?>">
                                    <?= icon('comment') ?>
                                    <?= _nf('%d comment', '%d comments', $link->number_comments, $link->number_comments) ?>
                                </a>
                            </p>
                        <?php endif; ?>
                    </div>

                    <div class="card__footer">
                        <div></div>

                        <a
                            class="anchor--action"
                            target="_blank"
                            rel="noopener noreferrer"
                            href="<?= protect($link->url) ?>"
                        >
                            <?= icon('pop-out') ?>
                            <?= _('read') ?>
                        </a>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>

        <?= $this->include('_pagination.phtml', ['pagination' => $pagination, 'url' => url('collection', ['id' => $collection->id])]) ?>
    <?php else: ?>
        <p class="paragraph--placeholder">
            <?= _('This collection is empty.') ?>
        </p>
    <?php endif; ?>
</div>
