<?php
    $this->layout('base.phtml', [
        'title' => $collection->name,
        'canonical' => url('collection', ['id' => $collection->id]),
        'current_tab' => 'collections',
        'back' => [
            'href' => url('collections'),
            'label' => _('Your collections'),
        ],
    ]);
?>

<div class="section" data-controller="back-storage" data-back-storage-type="link">
    <div class="section__title">
        <h1><?= $this->protect($collection->name) ?></h1>
    </div>

    <?php if ($topics): ?>
        <p class="collection__topics">
            <?= implode('&nbsp;·&nbsp;', array_column($topics, 'label')) ?>
        </p>
    <?php endif; ?>

    <div class="collection__meta">
        <div class="collection__details">
            <p class="collection__owner">
                <?php if ($collection->is_public): ?>
                    <span class="collection__public sticker">
                        <?= _('public') ?>
                    </span>
                <?php endif; ?>

                <?= _f('created by you') ?>
            </p>
        </div>

        <div class="collection__actions">
            <button
                class="button--small"
                data-controller="modal-opener"
                data-action="modal-opener#fetch"
                data-modal-opener-href="<?= url('edit collection', ['id' => $collection->id]) ?>"
                aria-haspopup="dialog"
                aria-controls="modal"
            >
                <?= _('Edit') ?>
            </button>
        </div>
    </div>

    <p class="collection__description">
        <?= nl2br($this->protect($collection->description)) ?>
    </p>

    <div class="cards">
        <div class="card card--action">
            <button
                class="card__button card__button--link"
                data-controller="modal-opener"
                data-action="modal-opener#fetch"
                data-modal-opener-href="<?= url('new link', ['collection' => $collection->id]) ?>"
                aria-haspopup="dialog"
                aria-controls="modal"
            >
                <i class="icon icon--only icon--plus-circle"></i><br />
                <?= _('Add a link') ?>
            </button>
        </div>

        <?php foreach ($links as $link): ?>
            <div class="card">
                <a
                    class="anchor--hidden"
                    target="_blank"
                    rel="noopener noreferrer"
                    tabindex="-1"
                    href="<?= $link->url ?>"
                >
                    <?php if ($link->image_filename): ?>
                        <img class="card__image" alt="" src="<?= url_link_image('cards', $link->image_filename) ?>" />
                    <?php else: ?>
                        <img class="card__image" alt="" src="<?= url_static('default-card.png') ?>" />
                    <?php endif; ?>
                </a>

                <div class="card__body">
                    <h2 class="card__title">
                        <a
                            class="anchor--hidden"
                            target="_blank"
                            rel="noopener noreferrer"
                            tabindex="-1"
                            href="<?= $link->url ?>"
                        >
                            <?= $this->protect($link->title) ?>
                        </a>
                    </h2>

                    <p class="card__text card__text--oneline">
                        <span class="card__ellipsis"><?= $this->protect($link->host()) ?></span>&nbsp;·&nbsp;<?= format_reading_time($link->reading_time) ?>
                    </p>

                    <p class="card__text">
                        <a class="icon icon--inline icon--ghost icon--anchor icon--comments" href="<?= url('link', ['id' => $link->id]) ?>">
                            <?= _nf('%d comment', '%d comments', $link->number_comments, $link->number_comments) ?>
                        </a>

                        <?php if ($collection->is_public && $link->is_hidden): ?>
                            <span class="sticker sticker--right">
                                <?= _('hidden') ?>
                            </span>
                        <?php endif; ?>
                    </p>
                </div>

                <div class="card__footer">
                    <div class="card__footer-group">
                        <details
                            class="popup"
                            data-controller="popup"
                            data-action="click@window->popup#close"
                        >
                            <summary class="popup__opener" title="<?= _('Open the menu') ?>" tabindex="-1">
                                <button class="button--ghost button--smaller" type="button" data-action="popup#toggle">
                                    <i class="icon icon--only icon--ellipsis-horizontal"></i>
                                    <span class="sr-only">
                                        <?= _('Open the menu') ?>
                                    </span>
                                </button>
                            </summary>

                            <nav class="popup__container popup__container--over">
                                <button
                                    class="popup__item popup__item--button icon icon--pencil"
                                    data-controller="modal-opener"
                                    data-action="modal-opener#fetch"
                                    data-modal-opener-href="<?= url('edit link', ['id' => $link->id, 'from' => url('collection', ['id' => $collection->id])]) ?>"
                                    aria-haspopup="dialog"
                                    aria-controls="modal"
                                >
                                    <?= _('Edit') ?>
                                </button>

                                <div data-controller="copy-to-clipboard">
                                    <input type="hidden" value="<?= $link->url ?>" data-target="copy-to-clipboard.copyable" />

                                    <button
                                        class="popup__item popup__item--button share__button icon icon--copy-to-clipboard"
                                        data-action="copy-to-clipboard#copy"
                                        data-target="copy-to-clipboard.feedback"
                                    >
                                        <?= _('Copy the external link') ?>
                                    </button>
                                </div>
                            </nav>
                        </details>

                        <button
                            class="button--ghost button--smaller"
                            data-controller="modal-opener"
                            data-action="modal-opener#fetch"
                            data-modal-opener-href="<?= url('link collections', ['id' => $link->id, 'from' => url('collection', ['id' => $collection->id])]) ?>"
                            aria-haspopup="dialog"
                            aria-controls="modal"
                            title="<?= _('Manage collections') ?>"
                        >
                            <i class="icon icon--only icon--collection"></i>
                            <span class="sr-only">
                                <?= _('Manage collections') ?>
                            </span>
                        </button>
                    </div>

                    <a
                        class="anchor--action icon icon--anchor icon--pop-out"
                        target="_blank"
                        rel="noopener noreferrer"
                        href="<?= $link->url ?>"
                    >
                        <?= _('read') ?>
                    </a>
                </div>
            </div>
        <?php endforeach; ?>

        <?php for ($i = 0; $i < (3 - ((count($links) + 1) % 3)); $i++): ?>
            <div class="card card--shadow no-mobile"></div>
        <?php endfor; ?>
    </div>
</div>
