<?php
    $this->layout('base.phtml', [
        'title' => $collection->name,
        'canonical' => url('collection', ['id' => $collection->id]),
        'current_tab' => 'collections',
    ]);
?>

<div class="section" data-controller="back-storage" data-back-storage-type="link">
    <?php if ($current_user): ?>
        <nav class="section__nav">
            <a class="anchor--action icon icon--anchor icon--undo" href="<?= url('discover collections') ?>">
                <?= _('Discover collections') ?>
            </a>

            <div class="section__nav-separator"></div>
        </nav>
    <?php endif; ?>

    <div class="section__title section__title--nolowercase">
        <h1><?= $this->protect($collection->name) ?></h1>
    </div>

    <?php if ($error): ?>
        <p class="form__error">
            <?= $error ?>
        </p>
    <?php endif; ?>

    <div class="collection__meta">
        <div class="collection__details">
            <p class="collection__owner">
                <?= _f('Collection created by %s', $this->protect($collection->owner()->username)) ?>
            </p>

            <?php if ($topics): ?>
                <p class="collection__topics">
                    <?= implode('&nbsp;·&nbsp;', array_column($topics, 'label')) ?>
                </p>
            <?php endif; ?>
        </div>

        <div class="collection__actions">
            <?php if ($current_user): ?>
                <?php if ($current_user->isFollowing($collection->id)): ?>
                    <form method="post" action="<?= url('unfollow collection', ['id' => $collection->id]) ?>">
                        <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />
                        <button>
                            <?= _('Unfollow') ?>
                        </button>
                    </form>
                <?php else: ?>
                    <form method="post" action="<?= url('follow collection', ['id' => $collection->id]) ?>">
                        <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />
                        <button>
                            <?= _('Follow') ?>
                        </button>
                    </form>
                <?php endif; ?>
            <?php endif; ?>
        </div>
    </div>

    <p class="collection__description">
        <?= nl2br($this->protect($collection->description)) ?>
    </p>

    <?php if ($links): ?>
        <div class="cards">
            <?php foreach ($links as $link): ?>
                <div class="card">
                    <div class="card__body">
                        <h2 class="card__title">
                            <a class="anchor--hidden" href="<?= url('link', ['id' => $link->id]) ?>" tabindex="-1">
                                <?= $this->protect($link->title) ?>
                            </a>
                        </h2>

                        <p class="card__details">
                            <span class="card__ellipsis"><?= $this->protect($link->host()) ?></span>&nbsp;·&nbsp;<?= format_reading_time($link->reading_time) ?>
                        </p>
                    </div>

                    <div class="card__footer">
                        <div></div>

                        <a class="anchor--action" href="<?= url('link', ['id' => $link->id]) ?>">
                            <?= _('see') ?>
                        </a>
                    </div>
                </div>
            <?php endforeach; ?>

            <?php for ($i = 0; $i < (3 - (count($links) % 3)); $i++): ?>
                <div class="card card--shadow"></div>
            <?php endfor; ?>
        </div>
    <?php else: ?>
        <p class="paragraph--placeholder">
            <?= _('This collection is empty.') ?>
        </p>
    <?php endif; ?>
</div>
