<?php
    $this->layout('base.phtml', [
        'title' => _('Bookmarked'),
    ]);
?>

<div class="title">
    <h1><?= _('Bookmarked') ?></h1>
</div>

<form method="post" action="<?= url('add link') ?>">
    <?php if ($error): ?>
        <p class="form__error">
            <?= $error ?>
        </p>
    <?php endif; ?>

    <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />
    <input type="hidden" name="collection_ids[]" value="<?= $bookmarked_collection->id ?>" />
    <input type="hidden" name="from" value="<?= url('show bookmarked') ?>" />

    <div class="form-group <?= isset($errors['url']) ? 'form-group--invalid' : '' ?>">
        <label for="url">
            <?= _('New link') ?>
        </label>

        <div class="form-group__stack">
            <input id="url" name="url" type="url" required />

            <button type="submit" class="button--primary">
                <?= _('Add') ?>
            </button>
        </div>

        <?php if (isset($errors['url'])): ?>
            <p class="form-group__error">
                <?= $errors['url'] ?>
            </p>
        <?php endif; ?>
    </div>
</form>

<div class="links">
    <?php foreach ($links as $link): ?>
        <div class="link">
            <div class="link__body">
                <h2 class="link__title">
                    <a class="anchor--discreet" href="<?= url('show link', ['id' => $link->id]) ?>">
                        <?= $this->protect($link->title) ?>
                    </a>
                </h2>
            </div>
        </div>
    <?php endforeach; ?>

    <?php if (!$links): ?>
        <p>
            <?= _('You have no links here yet.') ?>
        </p>
    <?php endif; ?>
</div>
