<?php
    $this->layout('base.phtml', [
        'title' => _('Bookmarks'),
        'current_tab' => 'bookmarks',
    ]);
?>

<div class="section">
    <div class="section__title">
        <h1><?= $this->protect($collection->name()) ?></h1>
    </div>

    <p class="section__intro">
        <?= _('Place here the links you want to consult later on.') ?>
    </p>

    <p class="paragraph--centered">
        <button
            class="icon icon--plus-circle"
            data-controller="modal-opener"
            data-action="modal-opener#fetch"
            data-modal-opener-href="<?= url('new link', ['collection' => $collection->id]) ?>"
            aria-haspopup="dialog"
            aria-controls="modal"
        >
            <?= _('Add a link') ?>
        </button>
    </p>

    <div class="cards">
        <?php foreach ($links as $link): ?>
            <div
                class="card"
                data-controller="link-card"
                data-link-card-bookmarked="true"
                data-link-card-bookmark-action="<?= url('bookmark link', ['id' => $link->id]) ?>"
                data-link-card-unbookmark-action="<?= url('unbookmark link', ['id' => $link->id]) ?>"
            >
                <div class="card__body">
                    <h2 class="card__title">
                        <a class="anchor--hidden" href="<?= url('link', ['id' => $link->id]) ?>" tabindex="-1">
                            <?= $this->protect($link->title) ?>
                        </a>
                    </h2>

                    <p class="card__details">
                        <?= $this->protect($link->host()) ?>&nbsp;·&nbsp;<?= format_reading_time($link->reading_time) ?>
                    </p>
                </div>

                <div class="card__footer">
                    <form
                        method="post"
                        action="<?= url('unbookmark link', ['id' => $link->id]) ?>"
                        data-action="link-card#toggleBookmarked"
                        data-target="link-card.bookmarkForm"
                    >
                        <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />

                        <button
                            class="button--ghost button--smaller"
                            title="<?= _('Remove from bookmarks') ?>"
                            aria-label="<?= _('Remove from bookmarks') ?>"
                        >
                            <i class="icon icon--only icon--solid icon--ghost icon--bookmark"></i>
                        </button>
                    </form>

                    <a class="anchor--action" href="<?= url('link', ['id' => $link->id]) ?>">
                        <?= _('see') ?>
                    </a>
                </div>
            </div>
        <?php endforeach; ?>
    </div>

    <?php if (!$links): ?>
        <p class="paragraph--placeholder">
            <?= _('This collection is empty. The links will appear here once you start adding them.') ?><br />
        </p>
    <?php endif; ?>
</div>
