<?php
    $this->layout('base.phtml', [
        'title' => _('Read Later'),
    ]);
?>

<div class="title">
    <h1><?= _('Read Later') ?></h1>
</div>

<?php if($bookmarked_collection): ?>
    <p>
        <?= _('You have no links here yet.') ?>
    </p>
<?php else: ?>
    <p>
        <?= _('You never used the “Read Later” collection.') ?>
    </p>

    <form method="post" action="<?= url('create bookmarked') ?>">
        <?php if ($error): ?>
            <p class="form__error">
                <?= $error ?>
            </p>
        <?php endif; ?>

        <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />

        <button type="submit" class="button--primary">
            <?= _('Start using it') ?>
        </button>
    </form>
<?php endif; ?>
