<?php
    $current_tab = 'collections';
    if ($collection->type === 'feed') {
        $feed = [
            'url' => $collection->feed_url,
            'title' => _f('Syndication feed of %s', $collection->name),
        ];

        if ($beta_enabled) {
            $current_tab = 'feeds';
        }
    } else {
        $feed = [
            'url' => url_full('collection feed', ['id' => $collection->id]),
            'title' => _f('Syndication feed of %s', $collection->name),
        ];

        if ($beta_enabled) {
            $current_tab = 'links';
        }
    }

    if ($pagination->isCurrentFirstPage()) {
        $current_url_params = ['id' => $collection->id];
    } else {
        $current_url_params = [
            'id' => $collection->id,
            'page' => $pagination->currentPage(),
        ];
    }

    $this->layout('base.phtml', [
        'title' => $collection->name,
        'canonical' => url_full('collection', $current_url_params),
        'current_tab' => $current_tab,
        'feed' => $feed,
    ]);
?>

<div class="section">
    <?php if ($collection->image_filename): ?>
        <img
            class="section__image"
            alt=""
            src="<?= url_media('large', $collection->image_filename) ?>"
        />
    <?php endif; ?>

    <div class="section__title">
        <h1><?= protect($collection->name) ?></h1>
    </div>

    <?php if ($topics): ?>
        <p class="collection__topics">
            <?= implode('&nbsp;·&nbsp;', array_column($topics, 'label')) ?>
        </p>
    <?php endif; ?>

    <div class="collection__meta">
        <div class="collection__details">
            <p class="collection__owner">
                <?php if ($collection->is_public): ?>
                    <span class="collection__public sticker">
                        <?= _('public') ?>
                    </span>
                <?php endif; ?>

                <?= _f('created by <a href="%s">you</a>', url('profile', ['id' => $current_user->id])) ?>
            </p>
        </div>

        <div class="collection__actions">
            <details
                class="popup"
                data-controller="popup"
                data-action="click@window->popup#close"
            >
                <summary class="popup__opener" title="<?= _('Open the menu') ?>" tabindex="-1">
                    <button class="button--small" type="button" data-action="popup#toggle">
                        <?= icon('menu') ?>
                        <?= _('Actions') ?>
                    </button>
                </summary>

                <nav class="popup__container popup__container--left">
                    <button
                        class="popup__item popup__item--button"
                        data-controller="modal-opener"
                        data-action="modal-opener#fetch"
                        data-modal-opener-href-value="<?= url('edit collection', ['id' => $collection->id, 'from' => url('collection', $current_url_params)]) ?>"
                        aria-haspopup="dialog"
                        aria-controls="modal"
                    >
                        <?= icon('pencil') ?>
                        <?= _('Edit') ?>
                    </button>

                    <button
                        class="popup__item popup__item--button"
                        data-controller="modal-opener"
                        data-action="modal-opener#fetch"
                        data-modal-opener-href-value="<?= url('edit group collection', ['id' => $collection->id, 'from' => url('collection', $current_url_params)]) ?>"
                        aria-haspopup="dialog"
                        aria-controls="modal"
                    >
                        <?= icon('directory') ?>
                        <?= _('Put in a group') ?>
                    </button>

                    <button
                        class="popup__item popup__item--button"
                        data-controller="modal-opener"
                        data-action="modal-opener#fetch"
                        data-modal-opener-href-value="<?= url('edit image collection', ['id' => $collection->id, 'from' => url('collection', $current_url_params)]) ?>"
                        aria-haspopup="dialog"
                        aria-controls="modal"
                    >
                        <?= icon('image') ?>
                        <?= _('Change the illustration') ?>
                    </button>

                    <?php if ($collection->is_public): ?>
                        <div data-controller="copy-to-clipboard">
                            <input type="hidden" value="<?= url_full('collection', ['id' => $collection->id]) ?>" data-copy-to-clipboard-target="copyable" />

                            <button
                                class="popup__item popup__item--button share__button"
                                data-action="copy-to-clipboard#copy"
                                data-copy-to-clipboard-target="feedback"
                            >
                                <?= icon('copy-to-clipboard') ?>
                                <?= _('Copy the link') ?>
                            </button>
                        </div>
                    <?php endif; ?>
                </nav>
            </details>
        </div>
    </div>

    <?php if ($collection->description): ?>
        <p class="collection__description">
            <?= nl2br(protect($collection->description)) ?>
        </p>
    <?php endif; ?>

    <div class="cards">
        <div class="card card--action">
            <button
                class="card__button card__button--link"
                data-controller="modal-opener"
                data-action="modal-opener#fetch"
                data-modal-opener-href-value="<?= url('new link', ['collection_id' => $collection->id, 'from' => url('collection', $current_url_params)]) ?>"
                aria-haspopup="dialog"
                aria-controls="modal"
            >
                <?= icon('plus-circle') ?><br />
                <?= _('Add a link') ?>
            </button>
        </div>

        <?php foreach ($links as $link): ?>
            <?= $this->include('links/_link.phtml', [
                'link' => $link,
                'from' => url('collection', $current_url_params),
                'display_comments' => true,
                'display_hidden' => $collection->is_public && $link->is_hidden,
                'display_edit' => true,
                'display_mark_as_read' => !$link->is_read,
                'collections_mode' => 'managing',
            ]); ?>
        <?php endforeach; ?>

        <?php for ($i = 0; $i < (3 - ((count($links) + 1) % 3)); $i++): ?>
            <div class="card card--shadow no-mobile"></div>
        <?php endfor; ?>
    </div>

    <?= $this->include('_pagination.phtml', ['pagination' => $pagination, 'url' => url('collection', ['id' => $collection->id])]) ?>
</div>
