<?php
    $this->layout('base.phtml', [
        'title' => _('Link collections'),
        'canonical' => url_full('link collections', ['id' => $link->id]),
    ]);
?>

<div class="section">
    <div class="section__title section__title--nolowercase">
        <h1><?= _('Link collections') ?></h1>
    </div>

    <p class="section__intro">
        <?= $this->protect($link->title) ?><br />
        <?= $this->protect($link->url) ?>
    </p>

    <form method="post" action="<?= url('update link collections', ['id' => $link->id]) ?>">
        <fieldset>
            <legend><?= _('Collections') ?></legend>

            <p class="fieldset__caption">
                <?= _('You must place your link in at least one collection.') ?>
            </p>

            <?php if (isset($errors['collection_ids'])): ?>
                <p class="form-group__error">
                    <?= $errors['collection_ids'] ?>
                </p>
            <?php endif; ?>

            <?php foreach ($collections as $collection): ?>
                <div class="form-group">
                    <input
                        type="checkbox"
                        id="collection-<?= $collection->id ?>"
                        name="collection_ids[]"
                        value="<?= $collection->id ?>"
                        <?= in_array($collection->id, $collection_ids) ? 'checked' : '' ?>
                    />
                    <label class="label--checkbox" for="collection-<?= $collection->id ?>">
                        <?= $this->protect($collection->name()) ?>
                    </label>
                </div>
            <?php endforeach; ?>
        </fieldset>

        <div class="form__actions">
            <button type="submit" class="button--primary">
                <?= _('Update') ?>
            </button>

            <a href="<?= url('link', ['id' => $link->id]) ?>">
                <?= _('Cancel and go back to the link') ?>
            </a>
        </div>
    </form>
</div>
