<?php
    $this->layout('base.phtml', [
        'title' => _('Link collections'),
        'canonical' => url_full('link collections', ['id' => $link->id]),
        'back' => [
            'href' => url('link', ['id' => $link->id]),
            'label' => _('Link'),
        ],
    ]);
?>

<div class="section">
    <div class="section__title">
        <h1 id="modal-title"><?= _('Link collections') ?></h1>
    </div>

    <p class="section__intro">
        <?= $this->protect($link->title) ?>
    </p>

    <form method="post" action="<?= url('update link collections', ['id' => $link->id]) ?>">
        <fieldset>
            <legend><?= _('Collections') ?></legend>

            <?php if (isset($errors['collection_ids'])): ?>
                <p class="form-group__error">
                    <?= $errors['collection_ids'] ?>
                </p>
            <?php endif; ?>

            <div class="collections-selector" data-controller="collections-selector">
                <select
                    id="collection-ids"
                    class="collections-selector__data"
                    name="collection_ids[]"
                    data-target="collections-selector.data"
                    multiple
                    required
                    tabindex="-1"
                >
                    <?php foreach ($collections as $collection): ?>
                        <option <?= in_array($collection->id, $collection_ids) ? 'selected' : '' ?> value="<?= $collection->id ?>">
                            <?= $this->protect($collection->name()) ?>
                        </option>
                    <?php endforeach; ?>
                </select>

                <ul class="collections-selector__list" data-target="collections-selector.list"></ul>

                <select
                    data-target="collections-selector.select"
                    data-action="collections-selector#attach"
                    aria-label="<?= _('Select a collection') ?>"
                >
                    <option selected disabled>
                        <?= _('Select a collection') ?>
                    </option>
                </select>
            </div>
        </fieldset>

        <div class="form__actions">
            <button type="submit" class="button--primary">
                <?= _('Save changes') ?>
            </button>
        </div>
    </form>
</div>
