<?php
    $display_comments = $display_comments ?? false;
    $display_hidden = $display_hidden ?? false;
    $display_edit = $display_edit ?? false;
    $display_mark_as_read = $display_mark_as_read ?? false;
    $display_mark_as_unread = $display_mark_as_unread ?? false;
    $display_via = $display_via ?? false;
    if ($display_via && !$link->via_type) {
        $display_via = false;
    }
    $collections_mode = $collections_mode ?? '';
    $secondary_menu_mode = $secondary_menu_mode ?? 'default';

    $via_collection = $display_via ? $link->viaCollection() : null;
    $via_user = $display_via ? $link->viaUser() : null;
?>

<div class="card">
    <a
        class="anchor--hidden"
        target="_blank"
        rel="noopener noreferrer"
        tabindex="-1"
        href="<?= protect($link->url) ?>"
    >
        <img class="card__image" alt="" src="<?= url_media('cards', $link->image_filename) ?>" loading="lazy" />
    </a>

    <time class="card__image-overlay" datetime="<?= $link->published_at->format(DATE_ATOM) ?>" title="<?= _date($link->published_at, 'dd MMM Y, HH:mm') ?>">
        <?php if ($now->format('Y') === $link->published_at->format('Y')): ?>
            <?= _date($link->published_at, 'dd MMM') ?>
        <?php else: ?>
            <?= _date($link->published_at, 'dd MMM Y') ?>
        <?php endif; ?>
    </time>

    <div class="card__body">
        <h2 class="card__title">
            <a
                class="anchor--hidden"
                target="_blank"
                rel="noopener noreferrer"
                tabindex="-1"
                href="<?= protect($link->url) ?>"
            >
                <?= protect($link->title) ?>
            </a>
        </h2>

        <p class="card__text card__text--oneline">
            <?php if (!$link->fetched_at): ?>
                <span class="icon--spin">
                    <?= icon('sync') ?>
                    <?= _('ongoing synchronisation…') ?>
                </span>
            <?php else: ?>
                <span class="card__ellipsis"><?= protect($link->host()) ?></span>&nbsp;·&nbsp;<?= format_reading_time($link->reading_time) ?>
            <?php endif; ?>

            <?php if ($link->is_read): ?>
                &nbsp;<span title="<?= _('You read this link.') ?>"><?= icon('check') ?><span class="sr-only"><?= _('You read this link.') ?></span></span>
            <?php endif; ?>
        </p>

        <?php if ($display_via): ?>
            <p class="card__text news__via">
                <?php if ($link->via_type === 'bookmarks'): ?>
                    <?= _f('via your <strong><a class="anchor--hidden" href="%s">bookmarks</a></strong>', url('bookmarks')) ?>
                <?php elseif ($via_collection): ?>
                    <?php if ($via_collection->type === 'collection'): ?>
                        <?php $owner = $via_collection->owner(); ?>
                        <?= _f(
                            'via <strong><a class="anchor--hidden" href="%s">%s</a></strong> by <a class="anchor--hidden" href="%s">%s</a>',
                            url('collection', ['id' => $via_collection->id]),
                            protect($via_collection->name()),
                            url('profile', ['id' => $owner->id]),
                            protect($owner->username)
                        ) ?>
                    <?php else: ?>
                        <?= _f(
                            'via <strong><a class="anchor--hidden" href="%s">%s</a></strong>',
                            url('collection', ['id' => $via_collection->id]),
                            protect($via_collection->name())
                        ) ?>
                    <?php endif; ?>
                <?php elseif ($via_user): ?>
                    <?= _f(
                        'via <strong><a class="anchor--hidden" href="%s">%s</a></strong>',
                        url('profile', ['id' => $via_user->id]),
                        protect($via_user->username)
                    ) ?>
                <?php endif; ?>
            </p>
        <?php endif; ?>

        <?php if ($display_comments): ?>
            <p class="card__text">
                <a href="<?= url('link', ['id' => $link->id]) ?>">
                    <?= icon('comment') ?>
                    <?= _nf('%d comment', '%d comments', $link->number_comments, $link->number_comments) ?>
                </a>

                <?php if ($display_hidden): ?>
                    <span class="sticker sticker--right">
                        <?= _('hidden') ?>
                    </span>
                <?php endif; ?>
            </p>
        <?php endif; ?>
    </div>

    <div class="card__footer">
        <div class="card__footer-group">
            <?php if ($secondary_menu_mode === 'default'): ?>
                <details
                    class="popup"
                    data-controller="popup"
                    data-action="toggle->popup#update click@window->popup#closeOnClickOutside keydown->popup#closeOnEscape"
                >
                    <summary class="popup__opener" title="<?= _('Open the menu') ?>">
                        <span class="button button--ghost button--smaller">
                            <?= icon('menu') ?>
                            <span class="sr-only">
                                <?= _('Open the menu') ?>
                            </span>
                        </span>
                    </summary>

                    <nav class="popup__container popup__container--over" role="menu">
                        <?php if ($display_edit): ?>
                            <button
                                class="popup__item popup__item--button"
                                data-controller="modal-opener"
                                data-action="modal-opener#fetch"
                                data-modal-opener-href-value="<?= url('edit link', ['id' => $link->id, 'from' => $from]) ?>"
                                aria-haspopup="dialog"
                                aria-controls="modal"
                                role="menuitem"
                            >
                                <?= icon('pencil') ?>
                                <?= _('Edit') ?>
                            </button>
                        <?php endif; ?>

                        <div data-controller="copy-to-clipboard">
                            <input type="hidden" value="<?= protect($link->url) ?>" data-copy-to-clipboard-target="copyable" />

                            <button
                                class="popup__item popup__item--button share__button"
                                data-action="copy-to-clipboard#copy"
                                data-copy-to-clipboard-target="feedback"
                                role="menuitem"
                            >
                                <?= icon('copy-to-clipboard') ?>
                                <?= _('Copy the external link') ?>
                            </button>
                        </div>

                        <?php if ($display_mark_as_read): ?>
                            <form method="post" action="<?= url('mark link as read', ['id' => $link->id, 'from' => $from]) ?>" role="menuitem">
                                <input type="hidden" name="csrf" value="<?= $csrf_token ?>" />

                                <button class="popup__item popup__item--button">
                                    <?= icon('check') ?>
                                    <?= _('Mark as read') ?>
                                </button>
                            </form>
                        <?php endif; ?>

                        <?php if ($display_mark_as_unread): ?>
                            <div class="popup__separator"></div>

                            <form method="post" action="<?= url('mark link as unread', ['id' => $link->id, 'from' => $from]) ?>" role="menuitem">
                                <input type="hidden" name="csrf" value="<?= $csrf_token ?>" />

                                <button class="popup__item popup__item--button">
                                    <?= icon('times') ?>
                                    <?= _('Remove from read list') ?>
                                </button>
                            </form>
                        <?php endif; ?>
                    </nav>
                </details>
            <?php elseif ($secondary_menu_mode === 'news'): ?>
                <details
                    class="popup"
                    data-controller="popup"
                    data-action="toggle->popup#update click@window->popup#closeOnClickOutside keydown->popup#closeOnEscape"
                >
                    <summary class="popup__opener" title="<?= _('Remove from the news page') ?>">
                        <span class="button button--ghost button--smaller">
                            <?= icon('menu') ?>
                            <span class="sr-only">
                                <?= _('Remove from the news page') ?>
                            </span>
                        </span>
                    </summary>

                    <nav class="popup__container popup__container--over" role="menu">
                        <div class="popup__title">
                            <?= _('Remove from the news…') ?>
                        </div>

                        <form method="post" action="<?= url('mark link as read', ['id' => $link->id, 'from' => url('news')]) ?>" role="menuitem">
                            <input type="hidden" name="csrf" value="<?= $csrf_token ?>" />

                            <button class="popup__item popup__item--button">
                                <?= icon('check') ?>
                                <?= _('and mark as read') ?>
                            </button>
                        </form>

                        <form method="post" action="<?= url('read link later', ['id' => $link->id, 'from' => url('news')]) ?>" role="menuitem">
                            <input type="hidden" name="csrf" value="<?= $csrf_token ?>" />

                            <button class="popup__item popup__item--button">
                                <?= icon('bookmark') ?>
                                <?= _('and read later') ?>
                            </button>
                        </form>

                        <div class="popup__separator"></div>

                        <form method="post" action="<?= url('mark link to never read', ['id' => $link->id, 'from' => url('news')]) ?>" role="menuitem">
                            <input type="hidden" name="csrf" value="<?= $csrf_token ?>" />

                            <button class="popup__item popup__item--button">
                                <?= icon('times') ?>
                                <?= _('and never see again') ?>
                            </button>
                        </form>
                    </nav>
                </details>
            <?php endif; ?>

            <?php if ($collections_mode): ?>
                <button
                    class="button--ghost button--smaller"
                    data-controller="modal-opener"
                    data-action="modal-opener#fetch"
                    data-modal-opener-href-value="<?= url('link collections', ['id' => $link->id, 'mode' => $collections_mode, 'from' => $from]) ?>"
                    aria-haspopup="dialog"
                    aria-controls="modal"
                    title="<?= $collections_mode === 'managing' ? _('Manage collections'): _('Add to collections') ?>"
                >
                    <?php if ($collections_mode === 'managing'): ?>
                        <?= icon('collection') ?>
                        <span class="sr-only">
                            <?= _('Manage collections') ?>
                        </span>
                    <?php else: ?>
                        <?= icon('collection-plus') ?>
                        <span class="sr-only">
                            <?= _('Add to collections') ?>
                        </span>
                    <?php endif; ?>
                </button>
            <?php endif; ?>
        </div>

        <a
            class="anchor--action"
            target="_blank"
            rel="noopener noreferrer"
            href="<?= protect($link->url) ?>"
        >
            <?= icon('pop-out') ?>
            <?= _('read') ?>
        </a>
    </div>
</div>
