<?php
    $this->layout('base.phtml', [
        'title' => _('Link collections'),
        'canonical' => url_full('link collections', ['id' => $link->id]),
    ]);
?>

<div class="section">
    <div class="section__title section__title--nolowercase">
        <h1><?= _('Link collections') ?></h1>
    </div>

    <p class="section__intro">
        <?= $this->protect($link->url) ?>
    </p>

    <form method="post" action="<?= url('update link collections', ['id' => $link->id]) ?>">
        <fieldset>
            <legend><?= _('Collections') ?></legend>

            <p class="fieldset__caption">
                <?= _('You must place your link in at least one collection.') ?>
            </p>

            <?php if (isset($errors['collection_ids'])): ?>
                <p class="form-group__error">
                    <?= $errors['collection_ids'] ?>
                </p>
            <?php endif; ?>

            <div class="form-group">
                <?php foreach ($collections as $collection): ?>
                    <label>
                        <input
                            type="checkbox"
                            name="collection_ids[]"
                            value="<?= $collection->id ?>"
                            <?= $collection->attachedToLink ? 'checked' : '' ?>
                        />
                        <?= $this->protect($collection->name) ?>
                    </label>
                <?php endforeach; ?>
            </div>
        </fieldset>

        <div class="form__actions">
            <button type="submit" class="button--primary">
                <?= _('Update') ?>
            </button>

            <a href="<?= url('link', ['id' => $link->id]) ?>">
                <?= _('Cancel and go back to the link') ?>
            </a>
        </div>
    </form>
</div>
