<?php
    $this->layout('base.phtml', [
        'title' => _('Link edition'),
        'canonical' => url_full('edit link', ['id' => $link->id]),
    ]);
?>

<div class="section">
    <nav class="section__nav no-modal">
        <a class="anchor--action icon icon--anchor icon--undo" href="<?= url('link', ['id' => $link->id]) ?>">
            <?= _('Link') ?>
        </a>

        <div class="section__nav-separator"></div>
    </nav>

    <div class="section__title">
        <h1 id="modal-title"><?= _('Link edition') ?></h1>
    </div>

    <p class="section__intro">
        <?= $this->protect($link->title) ?>
    </p>

    <form method="post" action="<?= url('update link', ['id' => $link->id]) ?>">
        <?php if ($error): ?>
            <p class="form__error">
                <?= $error ?>
            </p>
        <?php endif; ?>

        <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />

        <div class="form-group <?= isset($errors['title']) ? 'form-group--invalid' : '' ?>">
            <label for="title">
                <?= _('The title of your link') ?>
            </label>

            <input
                id="title"
                name="title"
                type="text"
                value="<?= $title ?>"
                required
                autocomplete="off"
                autofocus
            />

            <?php if (isset($errors['title'])): ?>
                <p class="form-group__error">
                    <?= $errors['title'] ?>
                </p>
            <?php endif; ?>
        </div>

        <div class="form-group">
            <input
                type="checkbox"
                id="is_public"
                name="is_public"
                <?= $is_public ? 'checked' : '' ?>
            />

            <label class="label--checkbox" for="is_public">
                <?= _('Show the link publicly') ?>
            </label>
        </div>

        <div class="form__actions">
            <button type="submit" class="button--primary">
                <?= _('Save changes') ?>
            </button>
        </div>
    </form>

    <form
        class="form--danger"
        method="post"
        action="<?= url('delete link', ['id' => $link->id]) ?>"
        data-controller="confirmation"
        data-action="confirmation#confirm"
        data-message="<?= _('Are you sure that you want to remove this link?') ?>"
    >
        <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />
        <input type="hidden" name="from" value="<?= url('link', ['id' => $link->id]) ?>" />
        <input
            type="hidden"
            name="redirect_to"
            value="<?= url('home') ?>"
            data-controller="back-anchor"
            data-back-anchor-type="link"
            data-back-anchor-replace="value"
         />

        <button type="submit" class="button--danger icon icon--trash">
            <?= _('Delete the link') ?>
        </button>
    </form>
</div>
