<?php
    $this->layout('base.phtml', [
        'title' => _('Link edition'),
        'canonical' => url_full('edit link', ['id' => $link->id]),
    ]);
?>

<div class="section" id="modal-content">
    <div class="section__title">
        <h1 id="modal-title"><?= _('Link edition') ?></h1>
    </div>

    <p class="section__intro">
        <?= $this->protect($link->title) ?>
    </p>

    <form method="post" action="<?= url('update link', ['id' => $link->id]) ?>">
        <?php if ($error): ?>
            <p class="form__error">
                <?= $error ?>
            </p>
        <?php endif; ?>

        <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />

        <div class="form-group <?= isset($errors['title']) ? 'form-group--invalid' : '' ?>">
            <label for="title">
                <?= _('Title') ?>
            </label>

            <input
                id="title"
                name="title"
                type="text"
                value="<?= $title ?>"
                required
                autocomplete="off"
                autofocus
            />

            <?php if (isset($errors['title'])): ?>
                <p class="form-group__error">
                    <?= $errors['title'] ?>
                </p>
            <?php endif; ?>
        </div>

        <div class="form-group">
            <input
                type="checkbox"
                id="is_public"
                name="is_public"
                <?= $is_public ? 'checked' : '' ?>
            />

            <label class="label--checkbox" for="is_public">
                <?= _('Show the link publicly') ?>
            </label>
        </div>

        <div class="form__actions">
            <button type="submit" class="button--primary">
                <?= _('Update') ?>
            </button>

            <a href="<?= url('link', ['id' => $link->id]) ?>" data-action="modal#close">
                <?= _('Cancel and go back to the link') ?>
            </a>
        </div>
    </form>
</div>
