<?php
    $this->layout('base.phtml', [
        'title' => _('My links'),
        'canonical' => url_full('links'),
        'current_tab' => 'links',
        'current_page' => 'links',
    ]);
?>

<div class="section" data-controller="back-storage" data-back-storage-type-value="collection">
    <div class="section__title">
        <h1><?= _('My links') ?></h1>
    </div>

    <p class="section__intro">
        <?= _('Organize your links in your bookmarks and your collections.') ?>
    </p>

    <section class="group">
        <div class="cards">
            <div class="card card--action">
                <button
                    class="card__button"
                    data-controller="modal-opener"
                    data-action="modal-opener#fetch"
                    data-modal-opener-href-value="<?= url('new collection') ?>"
                    aria-haspopup="dialog"
                    aria-controls="modal"
                >
                    <?= icon('plus') ?><br />
                    <?= _('Create a collection') ?>
                </button>
            </div>

            <div class="card card--illustrated card--illustrated-alt" style="background-image: url('<?= url_static('bookmarks-card.png') ?>');">
                <a class="card__body" href="<?= url('bookmarks') ?>">
                    <div class="card__title">
                        <?= protect($bookmarks->name()) ?>
                    </div>

                    <p class="card__text">
                        <?= _('Your links to read later') ?>
                    </p>
                </a>
            </div>

            <div class="card card--illustrated card--illustrated-alt" style="background-image: url('<?= url_static('read-card.png') ?>');">
                <a class="card__body" href="<?= url('read list') ?>">
                    <div class="card__title">
                        <?= protect($read_list->name()) ?>
                    </div>

                    <p class="card__text">
                        <?= _('All your links marked as read') ?>
                    </p>
                </a>
            </div>
        </div>
    </section>

    <section class="group">
        <div class="cards">
            <?php foreach ($no_group_collections as $collection): ?>
                <div class="card card--illustrated" style="background-image: url('<?= url_media('covers', $collection->image_filename, 'collection-card.svg') ?>');">
                    <a class="card__body" href="<?= url('collection', ['id' => $collection->id]) ?>">
                        <div class="card__title">
                            <?= protect($collection->name) ?>
                        </div>

                        <p class="card__text">
                            <?php if ($collection->number_links === 0): ?>
                                <?= _('no links') ?>
                            <?php else: ?>
                                <?= _nf('%d link', '%d links', $collection->number_links, $collection->number_links) ?>
                            <?php endif; ?>

                            <?php if ($collection->is_public): ?>
                                <span class="sticker sticker--right">
                                    <?= _('public') ?>
                                </span>
                            <?php endif; ?>
                        </p>
                    </a>
                </div>
            <?php endforeach; ?>

            <?php for ($i = 0; $i < (3 - (count($no_group_collections) % 3)); $i++): ?>
                <div class="card card--shadow no-mobile"></div>
            <?php endfor; ?>
        </div>
    </section>

    <?php foreach ($groups as $group): ?>
        <section class="group">
            <header class="group__header">
                <div class="group__icon">
                    <?= icon('directory') ?>
                </div>

                <h2 class="group__title">
                    <?= protect($group->name) ?>
                </h2>

                <div class="group__separator"></div>

                <button
                    class="button--small button--ghost no-mobile"
                    type="button"
                    data-controller="modal-opener"
                    data-action="modal-opener#fetch"
                    data-modal-opener-href-value="<?= url('edit group', ['id' => $group->id, 'from' => url('collections')]) ?>"
                    aria-haspopup="dialog"
                    aria-controls="modal"
                >
                    <?= icon('pencil') ?>
                    <?= _('Edit') ?>
                </button>

                <button
                    class="button--smaller button--ghost only-mobile"
                    type="button"
                    data-controller="modal-opener"
                    data-action="modal-opener#fetch"
                    data-modal-opener-href-value="<?= url('edit group', ['id' => $group->id, 'from' => url('collections')]) ?>"
                    aria-haspopup="dialog"
                    aria-controls="modal"
                >
                    <?= icon('pencil') ?>
                    <span class="sr-only">
                        <?= _('Edit') ?>
                    </span>
                </button>
            </header>

            <turbo-frame id="group-<?= $group->id ?>" src="<?= url('group collections', ['id' => $group->id, 'only' => 'owned']) ?>" target="_top">
                <div class="spinner"></div>
            </turbo-frame>
        </section>
    <?php endforeach; ?>

    <img
        class="illustration illustration--centered"
        alt=""
        src="<?= url_static('illustrations/my_collections.svg') ?>"
        height="250"
    />
</div>
