<?php
    $this->layout('base.phtml', [
        'title' => _('My links'),
        'canonical' => url_full('links'),
        'current_tab' => 'links',
        'current_page' => 'links',
        'enable_back' => false,
    ]);
?>

<div class="section">
    <div class="section__title">
        <h1><?= _('My links') ?></h1>
    </div>

    <p class="section__intro">
        <?= _('Organize your links in your bookmarks and your collections.') ?>
    </p>

    <section class="group">
        <div class="cards">
            <div class="card card--action">
                <button
                    class="card__button"
                    data-controller="modal-opener"
                    data-action="modal-opener#fetch"
                    data-modal-opener-href-value="<?= url('new collection') ?>"
                    aria-haspopup="dialog"
                    aria-controls="modal"
                >
                    <?= icon('plus') ?><br />
                    <?= _('Create a collection') ?>
                </button>
            </div>

            <div class="card card--illustrated card--illustrated-alt" style="background-image: url('<?= url_static('bookmarks-card.png') ?>');">
                <a class="card__body" href="<?= url('bookmarks') ?>">
                    <div class="card__title">
                        <?= protect($bookmarks->name()) ?>
                    </div>

                    <p class="card__text">
                        <?= _('Your links to read later') ?>
                    </p>
                </a>
            </div>

            <div class="card card--illustrated card--illustrated-alt" style="background-image: url('<?= url_static('read-card.png') ?>');">
                <a class="card__body" href="<?= url('read list') ?>">
                    <div class="card__title">
                        <?= protect($read_list->name()) ?>
                    </div>

                    <p class="card__text">
                        <?= _('All your links marked as read') ?>
                    </p>
                </a>
            </div>
        </div>
    </section>

    <?php $collections = $groups_to_collections[null] ?? []; ?>
    <?php if ($collections): ?>
        <section class="group">
            <div class="cards">
                <?php foreach ($collections as $collection): ?>
                    <?= $this->include('collections/_collection.phtml', [
                        'display_mode' => 'owned',
                        'collection' => $collection,
                    ]) ?>
                <?php endforeach; ?>

                <?php for ($i = 0; $i < (3 - (count($collections) % 3)); $i++): ?>
                    <div class="card card--shadow no-mobile"></div>
                <?php endfor; ?>
            </div>
        </section>
    <?php endif; ?>

    <?php foreach ($groups as $group): ?>
        <?php if (isset($groups_to_collections[$group->id])): ?>
            <?= $this->include('groups/_group.phtml', [
                'display_mode' => 'owned',
                'group' => $group,
                'collections' => $groups_to_collections[$group->id],
                'from' => url('links'),
            ]) ?>
        <?php endif; ?>
    <?php endforeach; ?>

    <img
        class="illustration illustration--centered"
        alt=""
        src="<?= url_static('illustrations/my_collections.svg') ?>"
        height="250"
    />
</div>
