<?php
    $this->layout('base.phtml', [
        'title' => _('New link'),
        'current_tab' => 'new link',
        'back' => [
            'href' => url('news'),
            'label' => _('Back'),
            'js-back-anchor-type' => 'link',
        ],
    ]);
?>

<div class="section">
    <div class="section__title">
        <h1 id="modal-title"><?= _('New link') ?></h1>
    </div>

    <form method="post" action="<?= url('create link') ?>">
        <?php if ($error): ?>
            <p class="form__error">
                <?= $error ?>
            </p>
        <?php endif; ?>

        <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />

        <div class="form-group <?= isset($errors['url']) ? 'form-group--invalid' : '' ?>">
            <label for="url">
                <?= _('What’s the <abbr>URL</abbr> of the link?') ?>
            </label>

            <p class="form-group__caption">
                <?= _('It can be copy-paste from the <abbr>URL</abbr> bar, at the top of your browser.') ?>
            </p>

            <input
                id="url"
                name="url"
                type="url"
                required
                value="<?= $url ?>"
                autocomplete="off"
                autofocus
            />

            <?php if (isset($errors['url'])): ?>
                <p class="form-group__error">
                    <?= $errors['url'] ?>
                </p>
            <?php endif; ?>
        </div>

        <fieldset class="no-modal">
            <legend><?= _('Collections') ?></legend>

            <?php if (isset($errors['collection_ids'])): ?>
                <p class="form-group__error">
                    <?= $errors['collection_ids'] ?>
                </p>
            <?php endif; ?>

            <div class="collections-selector" data-controller="collections-selector">
                <select
                    id="collection-ids"
                    class="collections-selector__data"
                    name="collection_ids[]"
                    data-target="collections-selector.data"
                    multiple
                    required
                    tabindex="-1"
                >
                    <?php foreach ($collections as $collection): ?>
                        <option <?= in_array($collection->id, $collection_ids) ? 'selected' : '' ?> value="<?= $collection->id ?>">
                            <?= $this->protect($collection->name()) ?>
                        </option>
                    <?php endforeach; ?>
                </select>

                <ul class="collections-selector__list" data-target="collections-selector.list"></ul>

                <select
                    data-target="collections-selector.select"
                    data-action="collections-selector#attach"
                    aria-label="<?= _('Select a collection') ?>"
                >
                    <option selected disabled>
                        <?= _('Select a collection') ?>
                    </option>
                </select>
            </div>
        </fieldset>

        <div class="form-group">
            <input
                type="checkbox"
                id="is_public"
                name="is_public"
                <?= $is_public ? 'checked' : '' ?>
            />

            <label class="label--checkbox" for="is_public">
                <?= _('Show the link publicly') ?>
            </label>
        </div>

        <div class="form__actions">
            <button type="submit" class="button--primary">
                <?= _('Add the link') ?>
            </button>
        </div>
    </form>

    <p class="paragraph--secondary no-extension no-modal no-mobile">
        <small>
            <?= _('Make your life easier by using the Web extension on') ?>
            <a
                target="_blank"
                rel="noopener noreferrer"
                href="https://addons.mozilla.org/fr/firefox/addon/flus/"
            >Firefox</a>
            <?= _('or') ?>
            <a
                target="_blank"
                rel="noopener noreferrer"
                href="https://chrome.google.com/webstore/detail/flus/gikjpohbbimicecbndkefebbpjobokjd?hl=fr"
            >Chrome</a>
        </small>
    </p>
</div>
