<?php
    $this->layout('base.phtml', [
        'title' => _('Link sharing'),
        'canonical' => url_full('sharing link', ['id' => $link->id]),
        'back' => [
            'href' => url('link', ['id' => $link->id]),
            'label' => _('Link'),
        ],
    ]);
?>

<div class="section">
    <div class="section__title">
        <h1><?= _('Link sharing') ?></h1>
    </div>

    <p class="section__intro">
        <?= $this->protect($link->title) ?>
    </p>

    <?php if ($link->is_public): ?>
        <p>
            <?= _('You can copy the following link to share your comments with people on other social media:') ?>
        </p>

        <div class="share" data-controller="copy-to-clipboard">
            <span class="share__text" data-target="copy-to-clipboard.copyable"><?= url_full('link', ['id' => $link->id]) ?></span>

            <button
                type="button"
                class="share__button icon icon--copy-to-clipboard"
                data-action="copy-to-clipboard#copy"
                data-target="copy-to-clipboard.feedback"
            >
                <?= _('copy') ?>
            </button>
        </div>
    <?php else: ?>
        <form
            method="post"
            action="<?= url('update link visibility', ['id' => $link->id]) ?>"
            class="form--centered"
        >
            <p>
                <?= _('This link is actually private. To share the link and its associated comments, you have to make it public.') ?>
            </p>

            <?php if ($error): ?>
                <p class="form__error">
                    <?= $error ?>
                </p>
            <?php endif; ?>

            <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />
            <input type="hidden" name="visibility" value="public" />

            <div class="form-group">
                <button type="submit" class="button--primary">
                    <?= _('Make it public') ?>
                </button>
            </div>
        </form>
    <?php endif; ?>

    <img
        class="illustration illustration--centered"
        alt=""
        src="<?= url_static('illustrations/share_link.svg') ?>"
        height="250"
    />
</div>
