<?php
    $this->layout('base.phtml', [
        'title' => $link->title,
        'canonical' => url_full('link', ['id' => $link->id]),
        'feed' => [
            'url' => url('link feed', ['id' => $link->id]),
            'title' => _f('Syndication feed of comments on %s', $link->title),
        ],
        'back' => [
            'href' => url('home'),
            'label' => _('Back'),
            'js-back-anchor-type' => 'link',
            'js-back-anchor-mode' => 'hide-if-none',
        ],
    ]);
?>

<div class="section">
    <?php if ($link->image_filename): ?>
        <img
            class="section__image"
            alt=""
            src="<?= url_link_image('large', $link->image_filename) ?>"
        />
    <?php endif; ?>

    <div class="section__title">
        <h1><?= $this->protect($link->title) ?></h1>
    </div>

    <section class="link__meta">
        <p class="link__details">
            <?= $this->protect($link->host()) ?>&nbsp;·&nbsp;<?= format_reading_time($link->reading_time) ?>
        </p>

        <ul class="link__actions">
            <li class="link__action">
                <a
                    class="anchor--action icon icon--anchor icon--pop-out"
                    target="_blank"
                    rel="noopener noreferrer"
                    href="<?= $link->url ?>"
                >
                    <?= _('read') ?>
                </a>
            </li>
        </ul>
    </section>

    <?php if ($messages): ?>
        <section class="subsection subsection--small" id="messages">
            <?php foreach ($messages as $message): ?>
                <?php $user = $message->user(); ?>
                <article class="message" id="message-<?= $message->id ?>">
                    <header class="message__header header">
                        <div class="header__container header__container--centered">
                            <img class="message__avatar" src="<?= url_avatar($user->avatar_filename) ?>" alt="" />

                            <div class="message__author">
                                <?= $this->protect($user->username) ?>
                            </div>

                            <div class="header__separator"></div>

                            <time class="message__date" datetime="<?= $message->created_at->format(DATE_ATOM) ?>">
                                <?= format_message_date($message->created_at) ?>
                            </time>
                        </div>
                    </header>

                    <div class="message__content">
                        <?= nl2br($this->protect($message->content)) ?>
                    </div>
                </article>
            <?php endforeach; ?>
        </section>
    <?php else: ?>
        <p class="paragraph--placeholder">
            <?= _f('%s didn’t comment on this link.', $this->protect($link->owner()->username)) ?>
        </p>
    <?php endif; ?>
</div>
