<?php
    $owner = $link->owner();
    $owner_is_current_user = $current_user && $current_user->id === $owner->id;

    $open_graph = [
        'title' => _f('Shared on %s: %s', get_app_configuration('brand'), $link->title),
        'description' => _f('A link shared by %s on %s.', $owner->username, get_app_configuration('brand')),
        'locale' => $owner->locale,
        'url' => url_full('link', ['id' => $link->id]),
    ];
    if ($link->image_filename) {
        $open_graph['image'] = url_media_full('cards', $link->image_filename);
    }

    $this->layout('base.phtml', [
        'title' => $link->title,
        'canonical' => url_full('link', ['id' => $link->id]),
        'alternates' => [
            [
                'type' => 'application/atom+xml',
                'url' => url_full('link feed', ['id' => $link->id]),
                'title' => _f('Syndication feed of notes on %s', $link->title),
            ],
        ],
        'open_graph' => $open_graph,
        'has_errors' => $error || $errors,
    ]);
?>

<div class="section">
    <?php if ($link->image_filename): ?>
        <a
            target="_blank"
            rel="noopener noreferrer"
            href="<?= protect($link->url) ?>"
            tabindex="-1"
        >
            <img
                class="section__image"
                alt="<?= protect($link->title) ?>"
                src="<?= url_media('large', $link->image_filename) ?>"
            />
        </a>
    <?php endif; ?>

    <div class="section__title">
        <h1>
            <a
                class="anchor--hidden"
                target="_blank"
                rel="noopener noreferrer"
                href="<?= protect($link->url) ?>"
                tabindex="-1"
            >
                <?= protect($link->title) ?>
            </a>
        </h1>
    </div>

    <?php if ($link->tags): ?>
        <div class="link__tags link__tags--center">
            <?php foreach ($link->tags as $tag): ?>
                <a class="tag" href="<?= url('links', ['q' => "#{$tag}"]) ?>">
                    #<?= $tag ?>
                </a>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <p class="section__intro">
        <?php if (!$link->fetched_at): ?>
            <span>
                <?= icon('sync', 'spin') ?>
                <?= _('ongoing synchronisation…') ?>
            </span>
        <?php else: ?>
            <?= protect($link->host()) ?>&nbsp;·&nbsp;<?= format_reading_time($link->reading_time) ?>
        <?php endif; ?>
    </p>

    <section class="section__meta">
        <p class="section__details">
            <?php $username = $owner_is_current_user ? _('you') : protect($owner->username); ?>
            <?= _f('Added by <a href="%s">%s</a>', url('profile', ['id' => $owner->id]), $username) ?>
        </p>

        <div class="section__actions">
            <a
                class="anchor--action"
                target="_blank"
                rel="noopener noreferrer"
                href="<?= protect($link->url) ?>"
            >
                <?= icon('pop-out') ?>
                <?= _('read') ?>
                <span class="sr-only">
                    <?= _('(open a new window)') ?>
                </span>
            </a>
        </div>
    </section>

    <section class="subsection subsection--small" id="notes">
        <hr>

        <h2 class="text--center text--normal">
            <?= _('Notepad') ?>
        </h2>

        <?php foreach ($notes as $note): ?>
            <?php $user = $note->user(); ?>
            <article class="note" id="note-<?= $note->id ?>">
                <header class="note__header header">
                    <div class="header__container header__container--centered">
                        <a tabindex="-1" href="<?= url('profile', ['id' => $user->id]) ?>">
                            <img class="note__avatar" src="<?= url_avatar($user->avatar_filename) ?>" alt="" />
                        </a>

                        <div class="note__author">
                            <a class="anchor--hidden" href="<?= url('profile', ['id' => $user->id]) ?>">
                                <?= protect($user->username) ?>
                            </a>
                        </div>

                        <div class="header__separator"></div>

                        <a class="note__date" href="#note-<?= $note->id ?>">
                            <time datetime="<?= $note->created_at->format(DATE_ATOM) ?>">
                                <?= _d($note->created_at, 'dd MMM y, HH:mm') ?>
                            </time>
                        </a>

                        <?php if ($current_user && $user->id === $current_user->id): ?>
                            <details
                                class="popup"
                                data-controller="popup"
                                data-action="toggle->popup#update click@window->popup#closeOnClickOutside keydown->popup#closeOnEscape"
                            >
                                <summary class="popup__opener" title="<?= _('Actions') ?>">
                                    <span class="button button--ghost button--smaller">
                                        <?= icon('menu') ?>
                                        <span class="sr-only">
                                            <?= _('Actions') ?>
                                        </span>
                                    </span>
                                </summary>

                                <nav class="popup__container popup__container--left" role="menu">
                                    <button
                                        class="popup__item popup__item--button"
                                        data-controller="modal-opener"
                                        data-action="modal-opener#fetch"
                                        data-modal-opener-href-value="<?= url('edit note', ['id' => $note->id, 'from' => url('link', ['id' => $link->id])]) ?>"
                                        aria-haspopup="dialog"
                                        aria-controls="modal"
                                        role="menuitem"
                                    >
                                        <?= icon('pencil') ?>
                                        <?= _('Edit') ?>
                                    </button>

                                    <div class="popup__separator"></div>

                                    <form
                                        data-turbo-preserve-scroll
                                        method="post"
                                        action="<?= url('delete note', ['id' => $note->id]) ?>"
                                        data-turbo-confirm="<?= _('Are you sure that you want to delete this note?') ?>"
                                        role="menuitem"
                                    >
                                        <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />
                                        <input type="hidden" name="redirect_to" value="<?= url('link', ['id' => $link->id]) ?>" />

                                        <button type="submit" class="popup__item popup__item--button">
                                            <?= icon('trash') ?>
                                            <?= _('Delete') ?>
                                        </button>
                                    </form>
                                </nav>
                            </details>
                        <?php endif; ?>
                    </div>
                </header>

                <div class="note__content">
                    <?= $note->contentAsHtml() ?>
                </div>
            </article>
        <?php endforeach; ?>

        <?php if ($can_update): ?>
            <form
                data-turbo-preserve-scroll
                method="post"
                action="<?= url('links/create note', ['link_id' => $link->id]) ?>"
                data-controller="autosave"
                data-action="turbo:submit-start@document->autosave#clear"
            >
                <?= $this->include('alerts/_error.phtml', ['message' => $error]) ?>

                <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />

                <div class="form-group <?= isset($errors['content']) ? 'form-group--invalid' : '' ?>">
                    <label for="content">
                        <?= _('What do you retain from this content?') ?>
                    </label>

                    <textarea
                        id="content"
                        name="content"
                        required
                        data-controller="text-editor"
                        data-action="text-editor#refresh keyup->autosave#save"
                        aria-describedby="content-desc"
                    ><?= $content ?></textarea>

                    <div id="content-desc">
                        <?php if (isset($errors['content'])): ?>
                            <p class="form-group__error">
                                <span class="sr-only"><?= _('Error') ?></span>
                                <?= $errors['content'] ?>
                            </p>
                        <?php endif; ?>

                        <p class="form-group__caption">
                            <?= _('You can format the content in Markdown and use #tags.') ?>
                        </p>
                    </div>
                </div>

                <?php if ($mastodon_configured): ?>
                    <div class="form-group">
                        <input
                            type="checkbox"
                            id="share-on-mastodon"
                            name="share_on_mastodon"
                            <?= $share_on_mastodon ? 'checked' : '' ?>
                        />

                        <label class="label--checkbox" for="share-on-mastodon">
                            <?= _('Share on Mastodon') ?>
                        </label>
                    </div>
                <?php endif; ?>

                <div class="form__actions">
                    <button type="submit" class="button--primary">
                        <?= _('Add a note') ?>
                    </button>
                </div>
            </form>

            <?php if ($link->is_hidden): ?>
                <p class="paragraph--centered paragraph--secondary">
                    <?= _('This link being hidden, the notes are private.') ?>
                </p>
            <?php endif; ?>
        <?php endif; ?>
    </section>
</div>
