<?php
    $owner = $link->owner();
    $open_graph = [
        'title' => _f('Shared on %s: %s', $brand, $link->title),
        'description' => _f('A link shared by %s on %s.', $owner->username, $brand),
        'locale' => $owner->locale,
        'url' => url_full('link', ['id' => $link->id]),
    ];
    if ($link->image_filename) {
        $open_graph['image'] = url_media_full('cards', $link->image_filename);
    }

    $this->layout('base.phtml', [
        'title' => $link->title,
        'canonical' => url_full('link', ['id' => $link->id]),
        'feed' => [
            'url' => url_full('link feed', ['id' => $link->id]),
            'title' => _f('Syndication feed of comments on %s', $link->title),
        ],
        'open_graph' => $open_graph,
    ]);
?>

<div class="section">
    <?php if ($link->image_filename): ?>
        <img
            class="section__image"
            alt=""
            src="<?= url_media('large', $link->image_filename) ?>"
        />
    <?php endif; ?>

    <div class="section__title">
        <h1><?= protect($link->title) ?></h1>
    </div>

    <section class="link__meta">
        <p class="link__details">
            <?php if (!$link->fetched_at): ?>
                <span class="icon--spin">
                    <?= icon('sync') ?>
                    <?= _('ongoing synchronisation…') ?>
                </span>
            <?php else: ?>
                <span class="card__ellipsis"><?= protect($link->host()) ?></span>&nbsp;·&nbsp;<?= format_reading_time($link->reading_time) ?>
            <?php endif; ?>
        </p>

        <ul class="link__actions">
            <li class="link__action">
                <a
                    class="anchor--action"
                    target="_blank"
                    rel="noopener noreferrer"
                    href="<?= protect($link->url) ?>"
                >
                    <?= icon('pop-out') ?>
                    <?= _('read') ?>
                </a>
            </li>
        </ul>
    </section>

    <?php if ($messages): ?>
        <section class="subsection subsection--small" id="messages">
            <?php foreach ($messages as $message): ?>
                <?php $user = $message->user(); ?>
                <article class="message" id="message-<?= $message->id ?>">
                    <header class="message__header header">
                        <div class="header__container header__container--centered">
                            <a tabindex="-1" href="<?= url('profile', ['id' => $user->id]) ?>">
                                <img class="message__avatar" src="<?= url_avatar($user->avatar_filename) ?>" alt="" />
                            </a>

                            <div class="message__author">
                                <a class="anchor--hidden" href="<?= url('profile', ['id' => $user->id]) ?>">
                                    <?= protect($user->username) ?>
                                </a>
                            </div>

                            <div class="header__separator"></div>

                            <time class="message__date" datetime="<?= $message->created_at->format(DATE_ATOM) ?>">
                                <?= format_message_date($message->created_at) ?>
                            </time>
                        </div>
                    </header>

                    <div class="message__content">
                        <?= nl2br(protect($message->content)) ?>
                    </div>
                </article>
            <?php endforeach; ?>
        </section>
    <?php else: ?>
        <p class="paragraph--placeholder">
            <?= _f('%s didn’t comment on this link.', protect($owner->username)) ?>
        </p>
    <?php endif; ?>
</div>
