<?php
    $this->layout('base.phtml', [
        'title' => _('News'),
        'canonical' => url_full('news'),
        'current_tab' => 'news',
        'current_page' => 'news',
        'back_options' => [
            'reset' => true,
        ],
        'has_errors' => $error || $errors,
    ]);
?>

<div class="section section--longbottom">
    <div class="section__title">
        <h1><?= _('News') ?></h1>
    </div>

    <?php if ($links): ?>
        <div class="cards cards--centered">
            <?php foreach ($links as $link): ?>
                <?= $this->include('links/_link.phtml', [
                    'link' => $link,
                    'from' => \Minz\Url::for('news'),
                    'display_edit' => true,
                    'display_repair' => true,
                    'display_via' => true,
                    'display_read_later' => true,
                    'display_mark_as_read' => true,
                    'display_never' => true,
                    'storing_must_mark_as_read' => true,
                ]); ?>
            <?php endforeach; ?>
        </div>

        <div class="news__postpone">
            <details
                class="popup news__postpone-popup"
                data-controller="popup"
                data-action="toggle->popup#update click@window->popup#closeOnClickOutside keydown->popup#closeOnEscape"
            >
                <summary class="popup__opener">
                    <span class="button news__postpone-button">
                        <?= icon('recycle') ?>
                        <?= _('Empty the news') ?>
                    </span>
                </summary>

                <nav class="popup__container popup__container--bottom" role="menu">
                    <form method="post" action="<?= url('mark collection as read', ['id' => $news->id]) ?>" role="menuitem">
                        <input type="hidden" name="csrf" value="<?= $csrf_token ?>" />
                        <input type="hidden" name="from" value="<?= url('news') ?>" />

                        <button class="popup__item popup__item--button">
                            <?= icon('check') ?>
                            <?= _('Mark all as read') ?>
                        </button>
                    </form>

                    <form method="post" action="<?= url('read collection later', ['id' => $news->id]) ?>" role="menuitem">
                        <input type="hidden" name="csrf" value="<?= $csrf_token ?>" />
                        <input type="hidden" name="from" value="<?= url('news') ?>" />

                        <button class="popup__item popup__item--button">
                            <?= icon('bookmark') ?>
                            <?= _('Read the links later') ?>
                        </button>
                    </form>

                    <div class="popup__separator"></div>

                    <form
                        method="post"
                        action="<?= url('never read collection', ['id' => $news->id]) ?>"
                        data-turbo-confirm="<?= _('You’ll remove all the news links, this action cannot be canceled. Are you sure?') ?>"
                        role="menuitem"
                    >
                        <input type="hidden" name="csrf" value="<?= $csrf_token ?>" />
                        <input type="hidden" name="from" value="<?= url('news') ?>" />

                        <button class="popup__item popup__item--button">
                            <?= icon('times') ?>
                            <?= _('Never see the links again') ?>
                        </button>
                    </form>
                </nav>
            </details>
        </div>
    <?php else: ?>
        <p class="section__intro">
            <?= _('Fill the news with…') ?>
        </p>

        <?php if ($no_news): ?>
            <?= $this->include('alerts/_info.phtml', ['message' => no_news_sentence()]) ?>
        <?php endif; ?>

        <form method="post" action="<?= url('fill news') ?>">
            <?= $this->include('alerts/_error.phtml', ['message' => $error]) ?>

            <input type="hidden" name="csrf" value="<?= $csrf_token ?>" />

            <div class="cards cards--centered">
                <div class="card card--action">
                    <button class="card__button news-selection__button" name="type" value="newsfeed">
                        <img
                            class="card__image news-selection__image"
                            alt=""
                            src="<?= url_static('illustrations/newspaper.svg') ?>"
                            height="200"
                        />

                        <div class="news-selection__description">
                            <strong class="news-selection__title"><?= _('the latest publications') ?></strong>
                            <small class="text--secondary"><?= _('from your followed feeds') ?></small>
                        </div>
                    </button>
                </div>

                <div class="card card--action">
                    <button class="card__button news-selection__button" name="type" value="short">
                        <img
                            class="card__image news-selection__image"
                            alt=""
                            src="<?= url_static('illustrations/reading.svg') ?>"
                            height="200"
                        />

                        <div class="news-selection__description">
                            <strong class="news-selection__title"><?= _('3 links of -10 minutes') ?></strong>
                            <small class="text--secondary"><?= _('from your bookmarks') ?></small>
                        </div>
                    </button>
                </div>

                <div class="card card--action">
                    <button class="card__button news-selection__button" name="type" value="long">
                        <img
                            class="card__image news-selection__image"
                            alt=""
                            src="<?= url_static('illustrations/cup-of-tea.svg') ?>"
                            height="200"
                        />

                        <div class="news-selection__description">
                            <strong class="news-selection__title"><?= _('1 link of +10 minutes') ?></strong>
                            <small class="text--secondary"><?= _('from your bookmarks') ?></small>
                        </div>
                    </button>
                </div>
            </div>
        </form>
    <?php endif; ?>
</div>
