<?php
    $this->layout('base.phtml', [
        'title' => _('News'),
        'current_tab' => 'news',
        'current_page' => 'news',
    ]);
?>

<div class="section section--longbottom" data-controller="back-storage" data-back-storage-type="link,collection">
    <div class="section__title">
        <h1><?= _('News') ?></h1>
    </div>

    <?php if ($links): ?>
        <div class="cards cards--centered">
            <?php foreach ($links as $link): ?>
                <?php
                    $news_link = $link->newsLink();
                    $via_collection = $news_link->viaCollection();
                ?>
                <div class="card">
                    <a
                        class="anchor--hidden"
                        target="_blank"
                        rel="noopener noreferrer"
                        tabindex="-1"
                        href="<?= protect($link->url) ?>"
                    >
                        <img class="card__image" alt="" src="<?= url_media('cards', $link->image_filename) ?>" />
                    </a>

                    <time class="card__image-overlay" datetime="<?= format_date($link->created_at, '%Y-%m-%d') ?>">
                        <?= format_date($link->created_at, '%d %b') ?>
                    </time>

                    <div class="card__body">
                        <h2 class="card__title">
                            <a
                                class="anchor--hidden"
                                target="_blank"
                                rel="noopener noreferrer"
                                tabindex="-1"
                                href="<?= protect($link->url) ?>"
                            >
                                <?= protect($link->title) ?>
                            </a>
                        </h2>

                        <p class="card__text card__text--oneline">
                            <span class="card__ellipsis"><?= protect($link->host()) ?></span>&nbsp;·&nbsp;<?= format_reading_time($link->reading_time) ?>
                        </p>

                        <p class="card__text news__via">
                            <?php if ($news_link->via_type === 'bookmarks'): ?>
                                <?= _f('via your <strong><a class="anchor--hidden" href="%s">bookmarks</a></strong>', url('bookmarks')) ?>
                            <?php elseif ($news_link->via_type === 'followed' && $via_collection): ?>
                                <?php if ($via_collection->type === 'collection'): ?>
                                    <?= _f('via <strong><a class="anchor--hidden" href="%s">%s</a></strong> by %s', url('collection', ['id' => $via_collection->id]), protect($via_collection->name()), protect($via_collection->owner()->username)) ?>
                                <?php else: ?>
                                    <?= _f('via <strong><a class="anchor--hidden" href="%s">%s</a></strong>', url('collection', ['id' => $via_collection->id]), protect($via_collection->name())) ?>
                                <?php endif; ?>
                            <?php elseif ($news_link->via_type === 'followed'): ?>
                                <?= _('via a <strong>followed collection</strong> (deleted)') ?>
                            <?php endif; ?>
                        </p>

                        <?php if (!$via_collection || $via_collection->type !== 'feed'): ?>
                            <p class="card__text">
                                <a href="<?= url('link', ['id' => $link->id]) ?>">
                                    <?= icon('comment') ?>
                                    <?= _nf('%d comment', '%d comments', $link->number_comments, $link->number_comments) ?>
                                </a>
                            </p>
                        <?php endif; ?>
                    </div>

                    <div class="card__footer">
                        <div class="card__footer-group">
                            <details
                                class="popup"
                                data-controller="popup"
                                data-action="click@window->popup#close"
                            >
                                <summary class="popup__opener" title="<?= _('Remove from the news page') ?>" tabindex="-1">
                                    <button class="button--ghost button--smaller" type="button" data-action="popup#toggle">
                                        <?= icon('menu') ?>
                                        <span class="sr-only">
                                            <?= _('Remove from the news page') ?>
                                        </span>
                                    </button>
                                </summary>

                                <nav class="popup__container popup__container--over">
                                    <div class="popup__title">
                                        <?= _('Remove from the news…') ?>
                                    </div>

                                    <form method="post" action="<?= url('mark news as read', ['id' => $link->news_link_id]) ?>">
                                        <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />

                                        <button class="popup__item popup__item--button">
                                            <?= icon('check') ?>
                                            <?= _('and mark as read') ?>
                                        </button>
                                    </form>

                                    <form method="post" action="<?= url('read news later', ['id' => $link->news_link_id]) ?>">
                                        <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />

                                        <button class="popup__item popup__item--button">
                                            <?= icon('bookmark') ?>
                                            <?= _('and read later') ?>
                                        </button>
                                    </form>
                                </nav>
                            </details>

                            <?php if ($has_collections): ?>
                                <button
                                    class="button--ghost button--smaller"
                                    data-controller="modal-opener"
                                    data-action="modal-opener#fetch"
                                    data-modal-opener-href="<?= url('add news', ['id' => $link->news_link_id]) ?>"
                                    aria-haspopup="dialog"
                                    aria-controls="modal"
                                    title="<?= _('Add to collections') ?>"
                                >
                                    <?= icon('collection') ?>
                                    <span class="sr-only">
                                        <?= _('Add to collections') ?>
                                    </span>
                                </button>
                            <?php endif; ?>
                        </div>

                        <a
                            class="anchor--action"
                            target="_blank"
                            rel="noopener noreferrer"
                            href="<?= protect($link->url) ?>"
                        >
                            <?= icon('pop-out') ?>
                            <?= _('read') ?>
                        </a>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>

        <div class="news__postpone">
            <details
                class="popup news__postpone-popup"
                data-controller="popup"
                data-action="click@window->popup#close"
            >
                <summary class="popup__opener" tabindex="-1">
                    <button class="news__postpone-button" type="button" data-action="popup#toggle">
                        <?= icon('recycle') ?>
                        <?= _('Empty the news') ?>
                    </button>
                </summary>

                <nav class="popup__container popup__container--bottom">
                    <form
                        method="post"
                        action="<?= url('mark news as read', ['id' => 'all']) ?>"
                        data-controller="confirmation"
                        data-action="confirmation#confirm"
                        data-message="<?= _('You’ll mark all the news links as read, this action cannot be canceled. Are you sure?') ?>"
                    >
                        <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />

                        <button class="popup__item popup__item--button">
                            <?= icon('check') ?>
                            <?= _('Mark all as read') ?>
                        </button>
                    </form>

                    <form method="post" action="<?= url('read news later', ['id' => 'all']) ?>">
                        <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />

                        <button class="popup__item popup__item--button">
                            <?= icon('bookmark') ?>
                            <?= _('Read the links later') ?>
                        </button>
                    </form>
                </nav>
            </details>
        </div>
    <?php else: ?>
        <?php if ($no_news): ?>
            <div class="section__intro">
                <p><?= _('We haven’t found any relevant links for the moment.') ?></p>
                <p class="text--secondary"><small><?= random_no_news_sentence() ?></small></p>
            </div>
        <?php else: ?>
            <p class="section__intro">
                <?= _('Fill the news with…') ?>
            </p>
        <?php endif; ?>

        <form method="post" action="<?= url('fill news') ?>">
            <?php if ($error): ?>
                <p class="form__error">
                    <?= $error ?>
                </p>
            <?php endif; ?>

            <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />

            <div class="cards cards--centered">
                <div class="card card--action">
                    <button class="card__button" name="type" value="newsfeed">
                        <img
                            class="card__image"
                            alt=""
                            src="<?= url_static('illustrations/newspaper.svg') ?>"
                            height="200"
                        />

                        <strong class="news-selection__title"><?= _('the latest publications') ?></strong>
                        <small class="text--secondary"><?= _('from your followed collections') ?></small>
                    </button>
                </div>

                <div class="card card--action">
                    <button class="card__button" name="type" value="short">
                        <img
                            class="card__image"
                            alt=""
                            src="<?= url_static('illustrations/reading.svg') ?>"
                            height="200"
                        />

                        <strong class="news-selection__title"><?= _('3 links of -10 minutes') ?></strong>
                        <small class="text--secondary"><?= _('from your bookmarks') ?></small>
                    </button>
                </div>

                <div class="card card--action">
                    <button class="card__button" name="type" value="long">
                        <img
                            class="card__image"
                            alt=""
                            src="<?= url_static('illustrations/cup-of-tea.svg') ?>"
                            height="200"
                        />

                        <strong class="news-selection__title"><?= _('1 link of +10 minutes') ?></strong>
                        <small class="text--secondary"><?= _('from your bookmarks') ?></small>
                    </button>
                </div>
            </div>
        </form>
    <?php endif; ?>
</div>
