<?php
    $this->layout('base.phtml', [
        'title' => _('News'),
        'current_tab' => 'news',
        'current_page' => 'news',
    ]);
?>

<div class="section" data-controller="back-storage" data-back-storage-type="link">
    <div class="section__title">
        <h1><?= _('News') ?></h1>
    </div>

    <?php if (!$news_links): ?>
        <div class="section__intro">
            <p>
                <?= format_news_preferences($news_preferences) ?>
            </p>

            <p>
                <button
                    data-controller="modal-opener"
                    data-action="modal-opener#fetch"
                    data-modal-opener-href="<?= url('news preferences') ?>"
                    aria-haspopup="dialog"
                    aria-controls="modal"
                    title="<?= _('Add to collections') ?>"
                >
                    <?= _('Configure') ?>
                </button>
            </p>
        </div>
    <?php endif; ?>

    <?php if ($news_links): ?>
        <div class="cards cards--centered">
            <?php foreach ($news_links as $news_link): ?>
                <?php
                    $via_collection = null;
                    if ($news_link->via_collection_id) {
                        $via_collection = $news_link->viaCollection();
                    }
                ?>
                <div class="card">
                    <a
                        class="anchor--hidden"
                        target="_blank"
                        rel="noopener noreferrer"
                        tabindex="-1"
                        href="<?= protect($news_link->url) ?>"
                    >
                        <img class="card__image" alt="" src="<?= url_link_image('cards', $news_link->image_filename) ?>" />
                    </a>

                    <div class="card__body">
                        <h2 class="card__title">
                            <a
                                class="anchor--hidden"
                                target="_blank"
                                rel="noopener noreferrer"
                                tabindex="-1"
                                href="<?= protect($news_link->url) ?>"
                            >
                                <?= protect($news_link->title) ?>
                            </a>
                        </h2>

                        <p class="card__text card__text--oneline">
                            <span class="card__ellipsis"><?= protect($news_link->host()) ?></span>&nbsp;·&nbsp;<?= format_reading_time($news_link->reading_time) ?>
                        </p>

                        <p class="card__text news__via">
                            <?php if ($news_link->via_type === 'bookmarks'): ?>
                                <?= _('via your <strong>bookmarks</strong>') ?>
                            <?php elseif ($news_link->via_type === 'topics' && $news_link->via_link_id): ?>
                                <?php $via_link = $news_link->viaLink(); ?>
                                <?= _f('via your <strong>points of interest</strong>, added by %s', protect($via_link->owner()->username)) ?>
                            <?php elseif ($news_link->via_type === 'topics'): ?>
                                <?= _('via your <strong>points of interest</strong>') ?>
                            <?php elseif ($news_link->via_type === 'followed' && $via_collection): ?>
                                <?php if ($via_collection->type === 'collection'): ?>
                                    <?= _f('via <strong>%s</strong> by %s', protect($via_collection->name()), protect($via_collection->owner()->username)) ?>
                                <?php else: ?>
                                    <?= _f('via <strong>%s</strong>', protect($via_collection->name())) ?>
                                <?php endif; ?>
                            <?php elseif ($news_link->via_type === 'followed'): ?>
                                <?= _('via a <strong>followed collection</strong> (now deleted)') ?>
                            <?php endif; ?>
                        </p>

                        <?php if ($news_link->via_link_id && !($via_collection && $via_collection->type === 'feed')): ?>
                            <p class="card__text">
                                <a href="<?= url('link', ['id' => $news_link->via_link_id]) ?>">
                                    <?= icon('comment') ?>
                                    <?= _nf('%d comment', '%d comments', $news_link->number_comments, $news_link->number_comments) ?>
                                </a>
                            </p>
                        <?php endif; ?>
                    </div>

                    <div class="card__footer">
                        <div class="card__footer-group">
                            <details
                                class="popup"
                                data-controller="popup"
                                data-action="click@window->popup#close"
                            >
                                <summary class="popup__opener" title="<?= _('Remove from the news page') ?>" tabindex="-1">
                                    <button class="button--ghost button--smaller" type="button" data-action="popup#toggle">
                                        <?= icon('menu') ?>
                                        <span class="sr-only">
                                            <?= _('Remove from the news page') ?>
                                        </span>
                                    </button>
                                </summary>

                                <nav class="popup__container popup__container--over">
                                    <div class="popup__title">
                                        <?= _('Remove from the news…') ?>
                                    </div>

                                    <form method="post" action="<?= url('mark news as read', ['id' => $news_link->id]) ?>">
                                        <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />

                                        <button class="popup__item popup__item--button">
                                            <?= icon('check') ?>
                                            <?= _('and mark as read') ?>
                                        </button>
                                    </form>

                                    <form method="post" action="<?= url('read news later', ['id' => $news_link->id]) ?>">
                                        <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />

                                        <button class="popup__item popup__item--button">
                                            <?= icon('bookmark') ?>
                                            <?= _('and read later') ?>
                                        </button>
                                    </form>
                                </nav>
                            </details>

                            <?php if ($has_collections): ?>
                                <button
                                    class="button--ghost button--smaller"
                                    data-controller="modal-opener"
                                    data-action="modal-opener#fetch"
                                    data-modal-opener-href="<?= url('add news', ['id' => $news_link->id]) ?>"
                                    aria-haspopup="dialog"
                                    aria-controls="modal"
                                    title="<?= _('Add to collections') ?>"
                                >
                                    <?= icon('collection') ?>
                                    <span class="sr-only">
                                        <?= _('Add to collections') ?>
                                    </span>
                                </button>
                            <?php endif; ?>
                        </div>

                        <a
                            class="anchor--action"
                            target="_blank"
                            rel="noopener noreferrer"
                            href="<?= protect($news_link->url) ?>"
                        >
                            <?= icon('pop-out') ?>
                            <?= _('read') ?>
                        </a>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>

        <div class="news__postpone">
            <p class="paragraph--centered">
                <?= _('Did you read everything? Or do you want to postpone your reading?') ?>
            </p>

            <details
                class="popup news__postpone-popup"
                data-controller="popup"
                data-action="click@window->popup#close"
            >
                <summary class="popup__opener" tabindex="-1">
                    <button class="news__postpone-button" type="button" data-action="popup#toggle">
                        <?= icon('recycle') ?>
                        <?= _('Recycle the news') ?>
                    </button>
                </summary>

                <nav class="popup__container popup__container--bottom">
                    <form
                        method="post"
                        action="<?= url('mark news as read', ['id' => 'all']) ?>"
                        data-controller="confirmation"
                        data-action="confirmation#confirm"
                        data-message="<?= _('You’ll mark all the news links as read, this action cannot be canceled. Are you sure?') ?>"
                    >
                        <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />

                        <button class="popup__item popup__item--button">
                            <?= icon('check') ?>
                            <?= _('Mark all as read') ?>
                        </button>
                    </form>

                    <form method="post" action="<?= url('read news later', ['id' => 'all']) ?>">
                        <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />

                        <button class="popup__item popup__item--button">
                            <?= icon('bookmark') ?>
                            <?= _('Read the links later') ?>
                        </button>
                    </form>
                </nav>
            </details>
        </div>
    <?php else: ?>
        <?php if ($no_news): ?>
            <p class="paragraph--centered">
                <em><?= _('We found no relevant news for you, what can you do?') ?></em>
            </p>

            <?php $tip_number = random_int(0, 2); ?>
            <?php if ($tip_number === 0): ?>
                <p class="paragraph--centered">
                    <strong><?= _('As you’re navigating on the Internet, bookmark the links you would like to read later.') ?></strong>
                </p>

                <p class="paragraph--centered">
                    <a href="<?= url('news') ?>">
                        <?= _('Ok, fine') ?>
                    </a>
                </p>
            <?php elseif ($tip_number === 1): ?>
                <p class="paragraph--centered">
                    <strong><?= _('Take a break, disconnect from Internet and go for a walk; news can wait.') ?></strong>
                </p>

                <p class="paragraph--centered">
                    <a href="<?= url('news') ?>">
                        <?= _('Ok, fine') ?>
                    </a>
                </p>
            <?php else: ?>
                <p class="paragraph--centered">
                    <strong><?= _('Discover collections created by the community and follow the ones you are interested in.') ?></strong>
                </p>

                <p class="paragraph--centered">
                    <a class="anchor--action" href="<?= url('discover collections') ?>">
                        <?= _('Discover collections') ?>
                    </a>
                </p>
            <?php endif; ?>
        <?php else: ?>
            <form class="form--centered" method="post" action="<?= url('fill news') ?>">
                <?php if ($error): ?>
                    <p class="form__error">
                        <?= $error ?>
                    </p>
                <?php endif; ?>

                <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />

                <div class="form__actions">
                    <button type="submit" class="button--primary">
                        <?= _('Get new suggestions') ?>
                    </button>
                </div>
            </form>

            <img
                class="illustration illustration--centered"
                alt=""
                src="<?= url_static('illustrations/reading.svg') ?>"
                height="250"
            />
        <?php endif; ?>
    <?php endif; ?>
</div>
