<?php
    $this->layout('base.phtml', [
        'title' => _('Share collection'),
        'canonical' => url_full('share collection', ['id' => $collection->id]),
        'has_errors' => $form->isInvalid(),
        'modal_enabled' => true,
    ]);
?>

<div class="section">
    <div class="section__title">
        <h1 id="modal-title"><?= _f('Share “%s”', protect($collection->name)) ?></h1>
    </div>

    <p class="section__intro">
        <?php if ($collection->is_public): ?>
            <?= _('This collection is public, anyone can access it.') ?>
        <?php else: ?>
            <?= _('This collection is private, you can share access to other users.') ?>
        <?php endif; ?>
    </p>

    <form method="post" action="<?= url('share collection', ['id' => $collection->id]) ?>">
        <?= $this->include('alerts/_error.phtml', ['message' => $form->error('@base')]) ?>

        <div class="form-group">
            <label for="user-id">
                <?= _('Share access with') ?>
            </label>

            <?php if ($form->isInvalid('user_id')): ?>
                <p id="user-id-error" class="form-group__error">
                    <?= _('Error:') ?>
                    <?= $form->error('user_id') ?>
                </p>
            <?php endif; ?>

            <div class="form-group__stack">
                <input
                    id="user-id"
                    name="user_id"
                    type="text"
                    required
                    value="<?= protect($form->user_id) ?>"
                    aria-describedby="user-id-caption"
                    placeholder="<?= url_full('profile', ['id' => $current_user->id]) ?>"
                    <?php if ($form->isInvalid('user_id')): ?>
                        aria-errormessage="user-id-error"
                        aria-invalid="true"
                    <?php endif; ?>
                />

                <button type="submit" class="button--primary">
                    <?= _('Share') ?>
                </button>
            </div>

            <p id="user-id-caption" class="form-group__caption">
                <?= _('Copy and paste the <abbr>URL</abbr> of a user’s profile.') ?>
            </p>
        </div>

        <div class="form-group" data-controller="caption-switcher">
            <?php if ($form->isInvalid('type')): ?>
                <p id="type-error" class="form-group__error">
                    <?= _('Error:') ?>
                    <?= $form->error('type') ?>
                </p>
            <?php endif; ?>

            <div>
                <input
                    type="radio"
                    id="type-read"
                    name="type"
                    value="read"
                    <?= $form->type === 'read' ? 'checked' : '' ?>
                    aria-describedby="type-caption"
                    data-action="caption-switcher#switch"
                    data-caption-switcher-target="switch"
                    <?php if ($form->isInvalid('type')): ?>
                        aria-errormessage="type-error"
                        aria-invalid="true"
                    <?php endif; ?>
                />

                <label class="label--radio" for="type-read">
                    <?= _('Read access') ?>
                </label>

                <input
                    type="radio"
                    id="type-write"
                    name="type"
                    value="write"
                    <?= $form->type === 'write' ? 'checked' : '' ?>
                    aria-describedby="type-caption"
                    data-action="caption-switcher#switch"
                    data-caption-switcher-target="switch"
                    <?php if ($form->isInvalid('type')): ?>
                        aria-errormessage="type-error"
                        aria-invalid="true"
                    <?php endif; ?>
                />

                <label class="label--radio" for="type-write">
                    <?= _('Read and write access') ?>
                </label>
            </div>

            <p id="type-caption" class="form-group__caption" aria-live="polite">
                <span data-caption-switcher-target="caption" data-caption-value="read">
                    <?= _('Sharing read access with other users gives them access to the whole collection, <strong>including their hidden links,</strong> but they can’t modify it.') ?>
                </span>

                <span data-caption-switcher-target="caption" data-caption-value="write">
                    <?= _('Sharing read and write access with other users gives them access to the whole collection, <strong>including their hidden links,</strong> and they can modify information or add links.') ?>
                </span>
            </p>
        </div>

        <input type="hidden" name="csrf_token" value="<?= csrf_token($form) ?>" />
    </form>

    <?php $collection_shares = $collection->shares(); ?>
    <?php if ($collection_shares): ?>
        <h2 class="title title--small"><?= _('Shared with:') ?></h2>

        <ul class="list list--no-style">
            <?php foreach ($collection_shares as $collection_share): ?>
                <?php $user = $collection_share->user(); ?>
                <li class="list__item line">
                    <span class="line__item">
                        <img class="avatar" src="<?= url_avatar($user->avatar_filename) ?>" alt="" />
                    </span>

                    <span class="line__item line__item--extend">
                        <a class="anchor--hidden" href="<?= url('profile', ['id' => $user->id]) ?>">
                            <?= protect($user->username) ?>
                        </a>
                    </span>

                    <span class="line__item text--secondary">
                        <?php if ($collection_share->type === 'read'): ?>
                            <?= _('read only') ?>
                        <?php else: ?>
                            <?= _('read / write') ?>
                        <?php endif; ?>
                    </span>

                    <form class="line__item" method="post" action="<?= url('unshare collection', ['id' => $collection->id]) ?>">
                        <button type="submit" class="button--ghost button--small">
                            <?= icon('times') ?>
                            <span class="no-mobile">
                                <?= _('Revoke') ?>
                            </span>
                        </button>

                        <input type="hidden" name="user_id" value="<?= protect($user->id) ?>" />
                        <input type="hidden" name="csrf_token" value="<?= csrf_token('collections\\UnshareCollection') ?>" />
                    </form>
                </li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>

    <div class="share" data-controller="copy-to-clipboard">
        <span class="share__text" data-copy-to-clipboard-target="copyable"><?= url_full('collection', ['id' => $collection->id]) ?></span>

        <button
            class="share__button"
            data-action="copy-to-clipboard#copy"
            data-copy-to-clipboard-target="feedback"
        >
            <?= icon('copy-to-clipboard') ?>
            <?= _('Copy') ?>
        </button>
    </div>
</div>
