<turbo-stream action="replace" target="modal-collections-shares-index">
    <template>
        <?= $this->include('collections/shares/_index.phtml', [
            'collection' => $collection,
            'type' => $this->safe('type'),
            'user_id' => $this->safe('user_id'),
            'from' => $this->safe('from'),
            'errors' => $errors,
            'error' => $this->safe('error'),
        ]); ?>
    </template>
</turbo-stream>
