<?php
    $this->layout('base.phtml', [
        'title' => _('Share collection'),
        'canonical' => url_full('share collection', ['id' => $collection->id]),
        'has_errors' => $error || $errors,
    ]);
?>

<?= $this->include('collections/shares/_index.phtml', [
    'collection' => $collection,
    'type' => $this->safe('type'),
    'user_id' => $this->safe('user_id'),
    'from' => $this->safe('from'),
    'errors' => $errors,
    'error' => $this->safe('error'),
]); ?>
