<?php
    $this->layout('base.phtml', [
        'title' => _('Discover collections'),
        'canonical' => url_full('discovery'),
        'current_tab' => $beta_enabled ? 'feeds' : 'collections',
        'open_graph' => [
            'title' => _('Discover collections'),
            'description' => _f('Discover the public collections on %s.', $brand),
            'locale' => $current_locale,
            'url' => url_full('discovery'),
        ],
        'back' => $current_user ? true : false,
    ]);
?>

<div class="section section--longbottom">
    <div class="section__title">
        <h1><?= _('Discover collections') ?></h1>
    </div>

    <?php if ($topics): ?>
        <p class="section__intro"><?= _('Choose a topic…') ?></p>

        <div class="cards cards--centered">
            <?php foreach ($topics as $topic): ?>
                <div class="card card--illustrated" style="background-image: url('<?= url_media('cards', $topic->image_filename) ?>');">
                    <a class="card__body" href="<?= url('topic', ['id' => $topic->id]) ?>">
                        <h2 class="card__title">
                            <?= protect($topic->label) ?>
                        </h2>

                        <p class="card__text card__text--small-margin">
                            <?php $number_collections = $topic->countPublicCollections(); ?>
                            <?php if ($number_collections > 0): ?>
                                <?= _nf('%d collection', '%d collections', $number_collections, $number_collections) ?>
                            <?php else: ?>
                                <?= _('No collections') ?>
                            <?php endif; ?>
                        </p>
                    </a>
                </div>
            <?php endforeach; ?>
        </div>
    <?php else: ?>
        <p class="paragraph--placeholder">
            <?= _('There’s no topics to show.') ?>
        </p>
    <?php endif; ?>
</div>
