<?php
    $back = null;
    if ($current_user) {
        $back = [
            'href' => url('collections'),
            'label' => _('Your collections'),
        ];
    }

    $this->layout('base.phtml', [
        'title' => _('Discover collections'),
        'current_tab' => 'collections',
        'back' => $back,
    ]);
?>

<div class="section section--longbottom">
    <div class="section__title">
        <h1><?= _('Discover collections') ?></h1>
    </div>

    <?php if ($topics): ?>
        <p class="section__intro"><?= _('Choose a topic…') ?></p>

        <div class="topics">
            <?php foreach ($topics as $topic): ?>
                <div class="topic">
                    <a class="topic__anchor" href="<?= url('topic', ['id' => $topic->id]) ?>">
                        <img class="topic__image" alt="" src="<?= url_media('cards', $topic->image_filename) ?>" />
                        <span class="topic__info">
                            <span class="topic__title">
                                <?= protect($topic->label) ?>
                            </span>

                            <span class="topic__collections">
                                <?php $number_collections = $topic->countPublicCollections(); ?>
                                <?php if ($number_collections > 0): ?>
                                    <?= _nf('%d collection', '%d collections', $number_collections, $number_collections) ?>
                                <?php else: ?>
                                    <?= _('No collections') ?>
                                <?php endif; ?>
                            </span>
                        </span>
                    </a>
                </div>
            <?php endforeach; ?>
        </div>
    <?php else: ?>
        <p class="paragraph--placeholder">
            <?= _('There’s no topics to show.') ?>
        </p>
    <?php endif; ?>
</div>
