<?php
    $this->layout('base.phtml', [
        'title' => _('Profile'),
        'canonical' => url_full('edit profile'),
        'current_page' => 'profile',
        'has_errors' => $form_profile->isInvalid() || $form_avatar->isInvalid(),
        'modal_enabled' => true,
    ]);
?>

<div class="section section--small">
    <div class="section__title">
        <h1><?= _('Profile') ?></h1>
    </div>

    <form
        method="post"
        action="<?= url('update avatar') ?>"
        class="form-avatar"
        data-controller="autosubmit form-file"
        enctype="multipart/form-data"
    >
        <img class="avatar avatar--banner" src="<?= url_avatar($current_user->avatar_filename) ?>" alt="" />

        <?= $this->include('alerts/_error.phtml', ['message' => $form_avatar->error('@base')]) ?>

        <?php if ($form_avatar->isInvalid('avatar')): ?>
            <p id="avatar-error" class="form-group__error text--center">
                <?= _('Error:') ?>
                <?= $form_avatar->error('avatar') ?>
            </p>
        <?php endif; ?>

        <input
            type="file"
            name="avatar"
            id="avatar"
            class="form-avatar__input"
            accept="<?= $form_avatar->imageAcceptedMimetypes() ?>"
            data-action="autosubmit#submit"
            data-form-file-target="file"
            hidden
        />

        <div class="form__actions">
            <button
                type="button"
                class="button--small"
                data-action="form-file#openFile"
                data-autosubmit-target="actionButton"
                aria-describedby="avatar-desc"
            >
                <?= _('Upload a photo') ?>
            </button>
        </div>

        <div id="avatar-desc">
            <?php if (isset($errors['avatar'])): ?>
                <p class="form-group__error">
                    <span class="sr-only"><?= _('Error') ?></span>
                    <?= $errors['avatar'] ?>
                </p>
            <?php endif; ?>

            <p class="form-group__caption text--centered">
                <?= _('<abbr>PNG</abbr> or <abbr>JPG</abbr> images only, a 150x150 image is recommended.') ?>
            </p>
        </div>

        <input type="hidden" name="csrf_token" value="<?= csrf_token($form_avatar) ?>" />
    </form>

    <form method="post" action="<?= url('update profile') ?>">
        <?= $this->include('alerts/_error.phtml', ['message' => $form_profile->error('@base')]) ?>

        <div class="form-group">
            <label for="username">
                <?= _('Your name') ?>
                <span class="label__help">
                    <?= _f('(public, max. %d characters)', $form_profile->username_max_length) ?>
                </span>
            </label>

            <?php if ($form_profile->isInvalid('username')): ?>
                <p id="username-error" class="form-group__error">
                    <?= _('Error:') ?>
                    <?= $form_profile->error('username') ?>
                </p>
            <?php endif; ?>

            <input
                type="text"
                name="username"
                id="username"
                value="<?= protect($form_profile->username) ?>"
                maxlength="<?= $form_profile->username_max_length ?>"
                required
                <?php if ($form_profile->isInvalid('username')): ?>
                    aria-errormessage="username-error"
                    aria-invalid="true"
                <?php endif; ?>
            />
        </div>

        <div class="form__actions">
            <button type="submit" class="button--primary">
                <?= _('Save changes') ?>
            </button>
        </div>

        <input type="hidden" name="csrf_token" value="<?= csrf_token($form_profile) ?>" />
    </form>
</div>
