<?php
    $this->layout('base.phtml', [
        'title' => _('Preferences'),
        'canonical' => url_full('preferences'),
        'current_page' => 'preferences',
        'has_errors' => $form->isInvalid(),
    ]);
?>

<div class="section section--small">
    <div class="section__title">
        <h1><?= _('Preferences') ?></h1>
    </div>

    <form method="post" action="<?= url('update preferences') ?>">
        <?= $this->include('alerts/_error.phtml', ['message' => $form->error('@base')]) ?>

        <div class="form-group">
            <label for="locale">
                <?= icon('language') ?>
                <?= _('Your language') ?>
            </label>

            <?php if ($form->isInvalid('locale')): ?>
                <p id="locale-error" class="form-group__error">
                    <?= _('Error:') ?>
                    <?= $form->error('locale') ?>
                </p>
            <?php endif; ?>

            <select
                id="locale"
                name="locale"
                <?php if ($form->isInvalid('locale')): ?>
                    aria-errormessage="locale-error"
                    aria-invalid="true"
                <?php endif; ?>
            >
                <?php foreach ($form->localesValues() as $locale_value => $locale_name): ?>
                    <option
                        value="<?= $locale_value ?>"
                        <?= $locale_value === $form->locale ? 'selected' : '' ?>
                    >
                        <?= $locale_name ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>

        <div class="form-group">
            <input
                type="checkbox"
                id="option-compact-mode"
                name="option_compact_mode"
                aria-describedby="option-compact-mode-caption"
                <?= $form->option_compact_mode ? 'checked' : '' ?>
            />

            <label class="label--checkbox" for="option-compact-mode">
                <?= _('Enable compact mode') ?>
            </label>

            <p class="form-group__caption" id="option-compact-mode-caption">
                <?= _('In compact mode, you see more links at a glance, but you may feel overwhelmed by the information.') ?>
            </p>
        </div>

        <div class="form-group">
            <input
                type="checkbox"
                id="accept-contact"
                name="accept_contact"
                <?= $form->accept_contact ? 'checked' : '' ?>
            />

            <label class="label--checkbox" for="accept-contact">
                <?= _('Accept to be contacted by email to help improve the service (optional).') ?>
            </label>
        </div>

        <div class="form-group">
            <input
                type="checkbox"
                id="beta-enabled"
                name="beta_enabled"
                aria-describedby="beta-enabled-caption"
                <?= $form->beta_enabled ? 'checked' : '' ?>
            />

            <label class="label--checkbox" for="beta-enabled">
                <?= _('Enable beta features') ?>
            </label>

            <p class="form-group__caption" id="beta-enabled-caption">
                <?= _('With beta features you test some features before everyone else, but you enter a turbulent zone.') ?>
            </p>
        </div>

        <div class="form__actions">
            <button type="submit" class="button--primary">
                <?= _('Save changes') ?>
            </button>
        </div>

        <input type="hidden" name="csrf_token" value="<?= csrf_token($form) ?>" />
    </form>
</div>
