<?php
    $this->layout('base.phtml', [
        'title' => _('Bookmarks'),
        'current_tab' => 'bookmarks',
        'current_page' => 'bookmarks',
    ]);
?>

<div class="section" data-controller="back-storage" data-back-storage-type="link">
    <div class="section__title">
        <h1><?= protect($collection->name()) ?></h1>
    </div>

    <p class="section__intro">
        <?= _('Place here the links you want to consult later on.') ?>
    </p>

    <div class="cards">
        <div class="card card--action">
            <button
                class="card__button card__button--link"
                data-controller="modal-opener"
                data-action="modal-opener#fetch"
                data-modal-opener-href="<?= url('new link', ['collection' => $collection->id, 'from' => url('bookmarks')]) ?>"
                aria-haspopup="dialog"
                aria-controls="modal"
            >
                <?= icon('plus-circle') ?><br />
                <?= _('Add a link') ?>
            </button>
        </div>

        <?php foreach ($links as $link): ?>
            <div class="card">
                <a
                    class="anchor--hidden"
                    target="_blank"
                    rel="noopener noreferrer"
                    tabindex="-1"
                    href="<?= protect($link->url) ?>"
                >
                    <img class="card__image" alt="" src="<?= url_link_image('cards', $link->image_filename) ?>" />
                </a>

                <div class="card__body">
                    <h2 class="card__title">
                        <a
                            class="anchor--hidden"
                            target="_blank"
                            rel="noopener noreferrer"
                            tabindex="-1"
                            href="<?= protect($link->url) ?>"
                        >
                            <?= protect($link->title) ?>
                        </a>
                    </h2>

                    <p class="card__text card__text--oneline">
                        <span class="card__ellipsis"><?= protect($link->host()) ?></span>&nbsp;·&nbsp;<?= format_reading_time($link->reading_time) ?>
                    </p>

                    <p class="card__text">
                        <a href="<?= url('link', ['id' => $link->id]) ?>">
                            <?= icon('comment') ?>
                            <?= _nf('%d comment', '%d comments', $link->number_comments, $link->number_comments) ?>
                        </a>
                    </p>
                </div>

                <div class="card__footer">
                    <div class="card__footer-group">
                        <details
                            class="popup"
                            data-controller="popup"
                            data-action="click@window->popup#close"
                        >
                            <summary class="popup__opener" title="<?= _('Open the menu') ?>" tabindex="-1">
                                <button class="button--ghost button--smaller" type="button" data-action="popup#toggle">
                                    <?= icon('menu') ?>
                                    <span class="sr-only">
                                        <?= _('Open the menu') ?>
                                    </span>
                                </button>
                            </summary>

                            <nav class="popup__container popup__container--over">
                                <button
                                    class="popup__item popup__item--button"
                                    data-controller="modal-opener"
                                    data-action="modal-opener#fetch"
                                    data-modal-opener-href="<?= url('edit link', ['id' => $link->id, 'from' => url('bookmarks')]) ?>"
                                    aria-haspopup="dialog"
                                    aria-controls="modal"
                                >
                                    <?= icon('pencil') ?>
                                    <?= _('Edit') ?>
                                </button>

                                <div data-controller="copy-to-clipboard">
                                    <input type="hidden" value="<?= protect($link->url) ?>" data-target="copy-to-clipboard.copyable" />

                                    <button
                                        class="popup__item popup__item--button share__button"
                                        data-action="copy-to-clipboard#copy"
                                        data-target="copy-to-clipboard.feedback"
                                    >
                                        <?= icon('copy-to-clipboard') ?>
                                        <?= _('Copy the external link') ?>
                                    </button>
                                </div>

                                <form method="post" action="<?= url('mark link as read', ['id' => $link->id]) ?>">
                                    <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />

                                    <button class="popup__item popup__item--button">
                                        <?= icon('check') ?>
                                        <?= _('Mark as read') ?>
                                    </button>
                                </form>
                            </nav>
                        </details>

                        <button
                            class="button--ghost button--smaller"
                            data-controller="modal-opener"
                            data-action="modal-opener#fetch"
                            data-modal-opener-href="<?= url('link collections', ['id' => $link->id, 'from' => url('bookmarks')]) ?>"
                            aria-haspopup="dialog"
                            aria-controls="modal"
                            title="<?= _('Manage collections') ?>"
                        >
                            <?= icon('collection') ?>
                            <span class="sr-only">
                                <?= _('Manage collections') ?>
                            </span>
                        </button>
                    </div>


                    <a
                        class="anchor--action"
                        target="_blank"
                        rel="noopener noreferrer"
                        href="<?= protect($link->url) ?>"
                    >
                        <?= icon('pop-out') ?>
                        <?= _('read') ?>
                    </a>
                </div>
            </div>
        <?php endforeach; ?>

        <?php for ($i = 0; $i < (3 - ((count($links) + 1) % 3)); $i++): ?>
            <div class="card card--shadow no-mobile"></div>
        <?php endfor; ?>
    </div>

    <img
        class="illustration illustration--centered"
        alt=""
        src="<?= url_static('illustrations/save_to_bookmarks.svg') ?>"
        height="250"
    />
</div>
