<?php
    $this->layout('base.phtml', [
        'title' => _('Collection illustration'),
        'canonical' => url_full('edit image collection', ['id' => $collection->id]),
        'has_errors' => $form->isInvalid(),
        'modal_enabled' => true,
    ]);
?>

<div class="section">
    <div class="section__title">
        <h1 id="modal-title"><?= _('Collection illustration') ?></h1>
    </div>

    <div class="section__intro">
        <p>
            <?= protect($collection->name) ?>
        </p>

        <p>
            <?= _('Illustrations help to distinguish your collection among the others.') ?>
        </p>
    </div>

    <form
        method="post"
        action="<?= url('update image collection', ['id' => $collection->id]) ?>"
        data-controller="autosubmit form-file"
        enctype="multipart/form-data"
    >
        <?= $this->include('alerts/_error.phtml', ['message' => $form->error('@base')]) ?>

        <?php if ($form->isInvalid('image')): ?>
            <p id="image-error" class="form-group__error text--center">
                <?= _('Error:') ?>
                <?= $form->error('image') ?>
            </p>
        <?php endif; ?>

        <input
            type="file"
            name="image"
            id="image"
            accept="<?= $form->imageAcceptedMimetypes() ?>"
            data-action="autosubmit#submit"
            data-form-file-target="file"
            hidden
        />

        <div class="form__actions">
            <button
                type="button"
                class="button--primary"
                data-action="form-file#openFile"
                data-autosubmit-target="actionButton"
                aria-describedby="file-caption"
                <?php if ($form->isInvalid('image')): ?>
                    aria-errormessage="image-error"
                    aria-invalid="true"
                <?php endif; ?>
            >
                <?= _('Upload an image') ?>
            </button>
        </div>

        <p id="file-caption" class="form-group__caption text--centered">
            <?= _('<abbr>PNG</abbr>, <abbr>JPG</abbr> and <abbr>WEBP</abbr> images only.') ?><br />
            <?= _('The minimum recommended dimensions are 1100x400px.') ?>
        </p>

        <input type="hidden" name="csrf_token" value="<?= csrf_token($form) ?>" />
    </form>
</div>
