<?php
    $this->layout('base.phtml', [
        'title' => _('Account deletion'),
        'canonical' => url_full('account deletion'),
        'back_options' => [
            'track' => false,
        ],
        'has_errors' => $form->isInvalid(),
    ]);
?>

<div class="section section--small section--longbottom">
    <div class="section__title">
        <h1><?= _('Account deletion') ?></h1>
    </div>

    <div class="section__intro">
        <p>
            <strong><?= _f('You’re connected as %s.', protect($current_user->username)) ?></strong>
        </p>

        <p>
            <?= _('You’re about to delete your account and your data will be lost. This can’t be canceled!') ?>
        </p>
    </div>

    <form method="post" action="<?= url('delete account') ?>">
        <?= $this->include('alerts/_error.phtml', ['message' => $form->error('@base')]) ?>

        <div class="form-group">
            <label for="password">
                <?= _('Your password') ?>
            </label>

            <?php if ($form->isInvalid('password')): ?>
                <p id="password-error" class="form-group__error">
                    <?= _('Error:') ?>
                    <?= $form->error('password') ?>
                </p>
            <?php endif; ?>

            <div class="form-group__stack" data-controller="input-password">
                <input
                    id="password"
                    name="password"
                    type="password"
                    autofocus
                    required
                    data-input-password-target="input"
                    aria-describedby="password-caption"
                    <?php if ($form->isInvalid('password')): ?>
                        aria-errormessage="password-error"
                        aria-invalid="true"
                    <?php endif; ?>
                />

                <button
                    type="button"
                    class="no-mobile js-only"
                    data-action="input-password#toggle"
                    data-input-password-target="button"
                    aria-label="<?= _('Show password as plain text. Note: this will visually expose your password.') ?>"
                >
                    <?= icon('eye') ?>
                    <?= _('Show') ?>
                </button>
            </div>

            <p id="password-caption" class="form-group__caption">
                <?= _('You must type your password so we can confirm your identity.') ?>
            </p>
        </div>

        <div class="form__actions">
            <button type="submit" class="button--danger">
                <?= _('Delete your account') ?>
            </button>
        </div>

        <input type="hidden" name="csrf_token" value="<?= csrf_token($form) ?>" />
    </form>
</div>
