<?php
    $this->layout('base.phtml', [
        'title' => _('Account deletion'),
        'back' => [
            'href' => url('account'),
            'label' => _('Account'),
        ],
    ]);
?>

<div class="section section--small section--longbottom">
    <div class="section__title">
        <h1><?= _('Account deletion') ?></h1>
    </div>

    <p class="section__intro">
        <?= _('You’re about to delete your account and your data will be lost. This can’t be canceled!') ?>
    </p>

    <form method="post" action="<?= url('delete account') ?>">
        <?php if ($error): ?>
            <p class="form__error">
                <?= $error ?>
            </p>
        <?php endif; ?>

        <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />

        <div class="form-group <?= isset($errors['password_hash']) ? 'form-group--invalid' : '' ?>">
            <label for="password">
                <?= _('Your password') ?>
            </label>

            <div class="form-group__stack" data-controller="input-password">
                <input
                    id="password"
                    name="password"
                    type="password"
                    autofocus
                    required
                    data-target="input-password.input"
                    aria-describedby="password-caption"
                />

                <button
                    type="button"
                    class="no-mobile js-only"
                    data-action="input-password#toggle"
                    data-target="input-password.button"
                    aria-label="<?= _('Show password as plain text. Note: this will visually expose your password.') ?>"
                >
                    <?= icon('eye') ?>
                    <?= _('Show') ?>
                </button>
            </div>

            <?php if (isset($errors['password_hash'])): ?>
                <p class="form-group__error">
                    <?= icon('error') ?>
                    <?= $errors['password_hash'] ?>
                </p>
            <?php endif; ?>

            <p class="form-group__caption" id="password-caption">
                <?= _('You must type your password so we can confirm your identity.') ?>
            </p>
        </div>

        <div class="form__actions">
            <button type="submit" class="button--danger">
                <?= _('Delete your account') ?>
            </button>
        </div>
    </form>
</div>
