<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
    </head>

    <body style="font-size: 18px; line-height: 1.3; margin: 0; color: #0c3b34; font-family: Lucida, Arial, sans-serif; background-color: #f7f6f4;">
        <div style="margin: 30px; text-align: center;">
            <img src="cid:<?= $logo_cid ?>" alt="<?= get_app_configuration('brand') ?>" width="200" height="40" style="height: auto; max-width: 200px;">
        </div>

        <div style="max-width: 525px; margin: 20px auto; padding: 30px; background-color: #ffffff; border-radius: 5px;">
            <p>
                <?= _f('Hello %s,', $username) ?>
            </p>

            <?= $this->safe('content') ?>

            <p>
                <?= _('Best regards,') ?>
            </p>

            <p>
                <?= _f('The %s robot', get_app_configuration('brand')) ?>
            </p>
        </div>

        <p style="text-align: center; color: #4f4e5e; font-size: 14px;">
            <?= _f('This email has been sent by <a href="%s" style="color: #4f4e5e;">%s</a>.', url_full('home'), get_app_configuration('brand')) ?>
        </p>
    </body>
</html>
