<?php
    $this->layout('base.phtml', [
        'title' => _('Mastodon authorization'),
        'canonical' => url_full('mastodon auth'),
        'has_errors' => $error || $errors,
    ]);
?>

<div class="section">
    <div class="section__title">
        <h1><?= _('Mastodon authorization') ?></h1>
    </div>

    <?php if ($error): ?>
        <?= $this->include('alerts/_error.phtml', ['message' => $error]) ?>

        <form method="post" action="<?= url('authorize mastodon') ?>">
            <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />
            <input type="hidden" name="code" value="<?= $code ?>" />

            <button type="submit" class="button--primary">
                <?= _('Check authorization') ?>
            </button>
        </form>
    <?php else: ?>
        <p class="paragraph--featured">
            <?= _('Please wait while we’re verifying access to Mastodon…') ?>
        </p>

        <div class="spinner"></div>

        <form
             method="post"
             action="<?= url('authorize mastodon') ?>"
             data-controller="autosubmit"
             data-autosubmit-mode-value="timeout"
         >
            <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />
            <input type="hidden" name="code" value="<?= $code ?>" />
        </form>
    <?php endif; ?>
</div>
