<?php
    $this->layout('base.phtml', [
        'title' => _('Mastodon authorization'),
        'canonical' => url_full('mastodon auth'),
        'has_errors' => $form->isInvalid(),
    ]);
?>

<div class="section">
    <div class="section__title">
        <h1><?= _('Mastodon authorization') ?></h1>
    </div>

    <?php if ($form->isInvalid()): ?>
        <form method="post" action="<?= url('authorize mastodon') ?>">
            <?= $this->include('alerts/_error.phtml', ['message' => implode(' ', $form->errors())]) ?>

            <button type="submit" class="button--primary">
                <?= _('Check authorization') ?>
            </button>

            <input type="hidden" name="csrf_token" value="<?= csrf_token($form) ?>" />
            <input type="hidden" name="code" value="<?= protect($form->code) ?>" />
        </form>
    <?php else: ?>
        <p class="paragraph--featured">
            <?= _('Please wait while we’re verifying access to Mastodon…') ?>
        </p>

        <div class="spinner"></div>

        <form
             method="post"
             action="<?= url('authorize mastodon') ?>"
             data-controller="autosubmit"
             data-autosubmit-mode-value="timeout"
         >
            <input type="hidden" name="csrf_token" value="<?= csrf_token($form) ?>" />
            <input type="hidden" name="code" value="<?= protect($form->code) ?>" />
        </form>
    <?php endif; ?>
</div>
