<?php
    $this->layout('base.phtml', [
        'title' => _('Configure sharing to Mastodon'),
        'canonical' => url_full('mastodon'),
        'back_options' => [
            'track' => false,
        ],
        'has_errors' => $form->isInvalid(),
    ]);
?>

<div class="section section--small section--longbottom">
    <div class="section__title">
        <h1><?= _('Configure sharing to Mastodon') ?></h1>
    </div>

    <p class="section__intro">
        <?= _f('%s lets you edit a thread of posts to share your links and notes on Mastodon.', get_app_configuration('brand')) ?>
    </p>

    <?= $this->include('alerts/_error.phtml', ['message' => $error]) ?>

    <?php if ($mastodon_account && $mastodon_account->isSetup()): ?>
        <form method="post" action="<?= url('update mastodon account') ?>">
            <?= $this->include('alerts/_error.phtml', ['message' => $form->error('@base')]) ?>

            <div class="form-group">
                <input
                    type="checkbox"
                    id="prefill-with-notes"
                    name="prefill_with_notes"
                    <?= $form->prefill_with_notes ? 'checked' : '' ?>
                />

                <label class="label--checkbox" for="prefill-with-notes">
                    <?= _('Pre-fill the thread with the contents of your notes') ?>
                </label>
            </div>

            <div class="form-group">
                <input
                    type="checkbox"
                    id="link-to-notes"
                    name="link_to_notes"
                    <?= $form->link_to_notes ? 'checked' : '' ?>
                />

                <label class="label--checkbox" for="link-to-notes">
                    <?= _('Add a link to your notes in the first post of the thread') ?>
                </label>
            </div>

            <div class="form-group">
                <label for="post-scriptum">
                    <?= _('Something to add to the first post of the thread? (postscript)') ?>
                    <span class="label__help">
                        <?= _f('(max. %d characters)', $form->post_scriptum_max_length) ?>
                    </span>
                </label>

                <?php if ($form->isInvalid('post_scriptum')): ?>
                    <p id="post-scriptum-error" class="form-group__error">
                        <?= _('Error:') ?>
                        <?= $form->error('post_scriptum') ?>
                    </p>
                <?php endif; ?>

                <input
                    id="post-scriptum"
                    name="post_scriptum"
                    type="text"
                    value="<?= protect($form->post_scriptum) ?>"
                    maxlength="<?= $form->post_scriptum_max_length ?>"
                    placeholder="<?= _('#monitoring') ?>"
                    <?php if ($form->isInvalid('post_scriptum')): ?>
                        aria-errormessage="post-scriptum-error"
                        aria-invalid="true"
                    <?php endif; ?>
                />
            </div>

            <div class="form-group">
                <input
                    type="checkbox"
                    id="post-scriptum-on-all-posts"
                    name="post_scriptum_in_all_posts"
                    <?= $form->post_scriptum_in_all_posts ? 'checked' : '' ?>
                />

                <label class="label--checkbox" for="post-scriptum-on-all-posts">
                    <?= _('Add the postscript in all the posts of the thread') ?>
                </label>
            </div>

            <div class="form__actions">
                <button type="submit" class="button--primary">
                    <?= _('Save changes') ?>
                </button>
            </div>

            <input type="hidden" name="csrf_token" value="<?= csrf_token($form) ?>" />
        </form>

        <hr>

        <div class="panel cols cols--center cols--gap-small text--small">
            <p class="col--extend">
                <?= _f('Connected with account <em>%s</em>', protect($mastodon_account->username)) ?>
            </p>

            <form
                method="post"
                action="<?= url('disconnect mastodon') ?>"
                data-turbo-confirm="<?= _('Are you sure that you want to disconnect your Mastodon account?') ?>"
            >
                <button type="submit" class="button--smaller">
                    <?= _('disconnect') ?>
                </button>

                <input type="hidden" name="csrf_token" value="<?= csrf_token('mastodon\\DeleteMastodonAccount') ?>" />
            </form>
        </div>
    <?php else: ?>
        <form method="post" action="<?= url('request mastodon access') ?>" data-turbo="false">
            <?= $this->include('alerts/_error.phtml', ['message' => $form->error('@base')]) ?>

            <div class="form-group">
                <label for="host">
                    <?= _('What’s the address of your Mastodon server?') ?>
                </label>

                <?php if ($form->isInvalid('host')): ?>
                    <p id="host-error" class="form-group__error">
                        <?= _('Error:') ?>
                        <?= $form->error('host') ?>
                    </p>
                <?php endif; ?>

                <input
                    id="host"
                    name="host"
                    type="url"
                    placeholder="https://…"
                    required
                    value="<?= protect($form->host) ?>"
                    aria-describedby="host-caption"
                    <?php if ($form->isInvalid('host')): ?>
                        aria-errormessage="host-error"
                        aria-invalid="true"
                    <?php endif; ?>
                />

                <p id="host-caption" class="form-group__caption">
                    <?= _('Not using Mastodon yet? <a target="_blank" rel="noopener noreferrer" href="https://joinmastodon.org/servers">Let’s choose a server.</a>') ?>
                </p>
            </div>

            <div class="form__actions">
                <button type="submit" class="button--primary">
                    <?= _('Connect to Mastodon') ?>
                </button>
            </div>

            <input type="hidden" name="csrf_token" value="<?= csrf_token($form) ?>" />
        </form>
    <?php endif; ?>
</div>
