<?php
    $this->layout('base.phtml', [
        'title' => _('Configure sharing to Mastodon'),
        'canonical' => url_full('mastodon'),
        'back_options' => [
            'track' => false,
        ],
        'has_errors' => $form->isInvalid(),
    ]);
?>

<div class="section section--small section--longbottom">
    <div class="section__title">
        <h1><?= _('Configure sharing to Mastodon') ?></h1>
    </div>

    <p class="section__intro">
        <?= _f('%s lets you share your links and notes on Mastodon.', get_app_configuration('brand')) ?>
    </p>

    <?= $this->include('alerts/_error.phtml', ['message' => $error]) ?>

    <?php if ($mastodon_account && $mastodon_account->isSetup()): ?>
        <form method="post" action="<?= url('update mastodon account') ?>">
            <?= $this->include('alerts/_error.phtml', ['message' => $form->error('@base')]) ?>

            <div class="form-group">
                <label for="link-to-note">
                    <?= _('When to link to your notes?') ?>
                </label>

                <?php if ($form->isInvalid('link_to_comment')): ?>
                    <p id="link-to-comment-error" class="form-group__error">
                        <?= _('Error:') ?>
                        <?= $form->error('link_to_comment') ?>
                    </p>
                <?php endif; ?>

                <select
                    id="link-to-note"
                    name="link_to_comment"
                    aria-describedby="link-to-comment-caption"
                    <?php if ($form->isInvalid('link_to_comment')): ?>
                        aria-errormessage="link-to-comment-error"
                        aria-invalid="true"
                    <?php endif; ?>
                 >
                     <option <?= $form->link_to_comment === 'auto' ? 'selected' : '' ?> value="auto">
                        <?= _('Only when you post a note') ?>
                    </option>

                    <option <?= $form->link_to_comment === 'always' ? 'selected' : '' ?> value="always">
                        <?= _('Always') ?>
                    </option>

                    <option <?= $form->link_to_comment === 'never' ? 'selected' : '' ?> value="never">
                        <?= _('Never') ?>
                    </option>
                </select>

                <p id="link-to-comment-caption" class="form-group__caption">
                    <?= _f('Your Mastodon posts can include a link to your notes on %s.', get_app_configuration('brand')) ?>
                </p>
            </div>

            <div class="form-group">
                <label for="post-scriptum">
                    <?= _('Always something to add to your posts?') ?>
                    <span class="label__help">
                        <?= _f('(max. %d characters)', $form->post_scriptum_max_length) ?>
                    </span>
                </label>

                <?php if ($form->isInvalid('post_scriptum')): ?>
                    <p id="post-scriptum-error" class="form-group__error">
                        <?= _('Error:') ?>
                        <?= $form->error('post_scriptum') ?>
                    </p>
                <?php endif; ?>

                <input
                    id="post-scriptum"
                    name="post_scriptum"
                    type="text"
                    value="<?= protect($form->post_scriptum) ?>"
                    maxlength="<?= $form->post_scriptum_max_length ?>"
                    <?php if ($form->isInvalid('post_scriptum')): ?>
                        aria-errormessage="post-scriptum-error"
                        aria-invalid="true"
                    <?php endif; ?>
                />
            </div>

            <div class="form__actions">
                <button type="submit" class="button--primary">
                    <?= _('Save changes') ?>
                </button>
            </div>

            <input type="hidden" name="csrf_token" value="<?= csrf_token($form) ?>" />
        </form>

        <div class="paragraph--centered paragraph--secondary">
            <small>
                <?= _f('connected with account <em>%s</em>', protect($mastodon_account->username)) ?>
            </small>

            <form
                method="post"
                action="<?= url('disconnect mastodon') ?>"
                data-turbo-confirm="<?= _('Are you sure that you want to disconnect your Mastodon account?') ?>"
            >
                <small>
                    <button type="submit" class="button--ghost button--smaller">
                        <?= _('disconnect') ?>
                    </button>
                </small>

                <input type="hidden" name="csrf_token" value="<?= csrf_token('mastodon\\DeleteMastodonAccount') ?>" />
            </form>
        </div>
    <?php else: ?>
        <form method="post" action="<?= url('request mastodon access') ?>" data-turbo="false">
            <?= $this->include('alerts/_error.phtml', ['message' => $form->error('@base')]) ?>

            <div class="form-group">
                <label for="host">
                    <?= _('What’s the address of your Mastodon server?') ?>
                </label>

                <?php if ($form->isInvalid('host')): ?>
                    <p id="host-error" class="form-group__error">
                        <?= _('Error:') ?>
                        <?= $form->error('host') ?>
                    </p>
                <?php endif; ?>

                <input
                    id="host"
                    name="host"
                    type="url"
                    placeholder="https://…"
                    required
                    value="<?= protect($form->host) ?>"
                    aria-describedby="host-caption"
                    <?php if ($form->isInvalid('host')): ?>
                        aria-errormessage="host-error"
                        aria-invalid="true"
                    <?php endif; ?>
                />

                <p id="host-caption" class="form-group__caption">
                    <?= _('Not using Mastodon yet? <a target="_blank" rel="noopener noreferrer" href="https://joinmastodon.org/servers">Let’s choose a server.</a>') ?>
                </p>
            </div>

            <div class="form__actions">
                <button type="submit" class="button--primary">
                    <?= _('Connect to Mastodon') ?>
                </button>
            </div>

            <input type="hidden" name="csrf_token" value="<?= csrf_token($form) ?>" />
        </form>
    <?php endif; ?>
</div>
