<?php
    $this->layout('base.phtml', [
        'title' => _('Downloading your data'),
        'canonical' => url_full('exportation'),
        'back_options' => [
            'track' => false,
        ],
        'has_errors' => $form->isInvalid(),
    ]);

    $exportation = $form->currentExportation();
?>

<div class="section section--small section--longbottom">
    <div class="section__title">
        <h1><?= _('Downloading your data') ?></h1>
    </div>

    <p class="section__intro">
        <?= _('You can download your data in order to migrate to a different tool.') ?>
    </p>

    <?= $this->include('alerts/_error.phtml', ['message' => $form->error('@base')]) ?>

    <?php if ($exportation && $exportation->isOngoing()): ?>
        <p class="paragraph--featured" role="alert">
            <?= _('We’re creating your archive…') ?>
        </p>

        <div class="spinner"></div>

        <p class="paragraph--placeholder">
            <?= _('This might take several minutes, please wait.') ?>
        </p>

        <form
             method="get"
             action="<?= url('exportation') ?>"
             data-controller="autosubmit"
             data-autosubmit-mode-value="timeout"
             data-autosubmit-timeout-value="4000"
        >
        </form>
    <?php elseif ($exportation && $exportation->isFinished()): ?>
        <p class="paragraph--featured">
            <a class="anchor--action" href="<?= url('download exportation') ?>" data-turbo="false">
                <?= _('Download your archive') ?>
            </a>
        </p>

        <p class="paragraph--centered paragraph--secondary">
            <i>
                <?= _f('generated on %s', _date($exportation->created_at, 'dd MMMM Y')) ?>
            </i>
        </p>

        <?= $this->include('exportations/_form.phtml', ['form' => $form]) ?>
    <?php elseif ($exportation && $exportation->isInError()): ?>
        <?= $this->include('alerts/_error.phtml', ['message' => protect($exportation->error)]) ?>

        <?= $this->include('exportations/_form.phtml', ['form' => $form]) ?>
    <?php else: ?>
        <?= $this->include('exportations/_form.phtml', ['form' => $form]) ?>
    <?php endif; ?>
</div>
