<?php
    $this->layout('base.phtml', [
        'title' => _('Organise your reading list more easily'),
        'canonical' => url_full('showcase', ['id' => 'reading']),
        'modal_enabled' => true,
    ]);
?>

<div class="section section--small">
    <div class="section__title">
        <h1><?= _('Organise your reading list more easily') ?></h1>
    </div>

    <p class="section__intro">
        <?= _('Something has changed!') ?>
    </p>

    <p>
        <?= _('<strong>A new “Reading” tab is now available in the main navigation menu.</strong> It brings together all the features related to reading: “News”, “Bookmarks” and “Links read” are accessible in one click.') ?>
    </p>

    <img
        class="illustration illustration--centered"
        alt="<?= _('The screenshot of the Reading menu. It shows three elements: News, Bookmarks and Links read.') ?>"
        src="<?= url_static("onboarding/reading_menu.{get_current_locale()}.webp") ?>"
    />

    <p>
        <?= _('Don’t hesitate <strong>to give feedback</strong> from the “Help & support” menu!') ?>
    </p>

    <form method="get" action="">
        <div class="form__actions">
            <button type="submit" class="button--primary">
                <?= _('Got it!') ?>
            </button>
        </div>
    </form>
</div>
