<?php
    $this->layout('base.phtml', [
        'title' => _('Links have been improved'),
        'canonical' => url_full('showcase', ['id' => 'navigation']),
        'modal_enabled' => true,
    ]);
?>

<div class="section section--small">
    <div class="section__title">
        <h1><?= _('Links have been improved') ?></h1>
    </div>

    <p class="section__intro">
        <?= _('Something has changed!') ?>
    </p>

    <p>
        <?= _('<strong>The link interface is now more consistent and practical.</strong> You can mark a link as read, or add it to your bookmarks in one click. The “read” link has been removed, but don’t worry: you still can click on titles to read your links!') ?>
    </p>

    <img
        class="illustration illustration--centered"
        alt="<?= _('The screenshot of a link card. The actions at its bottom allow to mark as read, add to bookmarks and store the link.') ?>"
        src="<?= url_static("showcases/link.{$current_locale}.webp") ?>"
    />

    <p>
        <?= _('The look of the links on mobile has also been improved to save space.') ?>
    </p>

    <p>
        <?= _('Don’t hesitate <strong>to give feedback</strong> from the “Help & support” menu!') ?>
    </p>

    <form method="get" action="">
        <div class="form__actions">
            <button type="submit" class="button--primary">
                <?= _('Got it!') ?>
            </button>
        </div>
    </form>
</div>
